### ISSUE TITLE
issues with GUI

### ISSUE THREAD

**Issue by octoshrimpy** [martinet101/WinGetUI#1]
minimum screen size is larger than monitor, cuts off text everywhere and UI elements when attempting upgrade/reinstall

![Screenshot (1)](https://user-images.githubusercontent.com/7097172/135132838-43f69f2b-fddc-4b09-943b-7987c3ef07f7.png)

**Comment by martinet101** [comment]
Oh, I see. I'll add a QScrollableWidget to add a scrollbar and avoid weird text compressions :). Thanks for letting me know

**Comment by martinet101** [comment]
I've fixed that, the fix will be rolled out with v0.4 soon.

**Comment by martinet101** [comment]
Release 0.4 is now available with the fix
