### ISSUE TITLE
Feature request: Fade away successful installs automatically/clean up progressing installs

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#10]
This could be done in different ways.

One way is to keep it as is and just fade away completed installs after a few seconds; unsuccessful installs are interesting, successful aren't as much.

Another way is to have a sidebar or equivalent where all install progress is kept to keep it away from the main view.

1.  [x] Have a way to hide/show the installs list
2.  [x] Auto hide the correct ones
3.  [x] Leave the failed ones
4.  [x] Add a scrollbar for when the installations pass x amount to don't overload the main window

**Comment by martinet101** [comment]
Yes, this could be implemented in the following way:
1. Have a way to hide/show the installs list
2. Auto hide the correct ones
3. Leave the failed ones
4. Add a scrollbar for when the installations pass x amount to don't overload the main window

**Comment by RavenMacDaddy** [comment]
Sounds good, great progress.

Thanks for the software by the way.

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/169548548-f3020ea0-d09a-4f6f-84ab-58fee7e0a919.png)
This little guy here will now let you hide the installs list

**Comment by RavenMacDaddy** [comment]
Nice, does it have a little sliding animation and the arrow direction switching as well?

**Comment by martinet101** [comment]
The arrow switches, but animations are not a thing yet (they are planned)

**Comment by RavenMacDaddy** [comment]
Understood, glad that will also become a reality eventually.

**Comment by RavenMacDaddy** [comment]
Just to express what I'm visualizing, I see two different elements; the button with an arrow and the sliding animation of the panel if you will.

The arrow I see (quickly) fading from pointing up to pointing down and vice versa, depending on the original position of the progressing installs-list of course.

The sliding animation I visualize a lot like animations in iOS where a panel comes up as a result of the user's interaction, the corresponding panel slides into view and vice versa.

These two elements ideally animate independent from each other - which in itself creates an aesthetic dynamic.

**Comment by martinet101** [comment]
> 4\. Add a scrollbar for when the installations pass x amount to don't overload the main window

Done!
