### ISSUE TITLE
Antivirus Warning - "Trojan-Downloader.Win32.Alien.gnj" Found

### ISSUE THREAD

**Issue by ChristianMoritz** [martinet101/WingetUI#100]
Ill hope this is a false positive,

my Antivirus (CheckPoint Endpoint Security) found in the download of the Windows exe Package the trojan and deletes the File.

Tested with the newest Signature Update for the AV.
Signature Version:
 202207260355
AV Version: E84.50.7526

**Comment by martinet101** [comment]
Hi @ChristianMoritz,

It is a false positive. To prove it, you can upload both the installer and the executable file into virustotal.

I have done that myself, but sending a screenshot wouldn't guarantee you that I am not sending an edited pic
