### ISSUE TITLE
Improvement: Allow the user to use lower case letters for (Scoop) apps

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#101]
Yep, Scoop is following classic terminal traditions by using lower case letters by default when used through a CLI (obviously you could run something like `scoop install Cnc-ddraw` and that would be used as the app's folder name, but exhibit A are all of Scoop's folders like `apps` and `persist`).

Having the option to install apps from package managers with lower case would be a nice addition.

**Comment by martinet101** [comment]
I'm sorry, I am not understanding what you mean

**Comment by RavenMacDaddy** [comment]
So, let's say I want to install the app in question, `cnc-ddraw`.

If I install it through WingetUI, the first letter will always be uppercase, e.g. Cnc-ddraw in this case.

In order to have everything match up, as well as keeping the typography of scoop, it would be a neat little option to install apps with only lowercase, so it does install as `cnc-ddraw`.

**Comment by martinet101** [comment]
Ok, i guess I understand it now

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/187732066-e18523ef-84e8-43c8-9f3b-bfedb95a91b5.png)
