### ISSUE TITLE
Scoop error.

### ISSUE THREAD

**Issue by Hellements** [martinet101/WingetUI#104]
Hello there,
I downloaded and installed the WingetUI v1.2.0 on my win10pro 21H2 19044.1826.
When opened, it shows 4 available updates, as you can see on the picture. I click upgrade all packages and I get 4 popup errors and nothing gets updated. Tried again with same results. Also tried to uninstall and install again with no luck.

![scoop](https://user-images.githubusercontent.com/88634350/182729495-2e564d8f-457c-418e-8a65-2380f3eb626a.jpg)

Thanks in advance.

**Comment by martinet101** [comment]
Hi,

do you have scoop installed in your system?

**Comment by Hellements** [comment]
Hello,
I did not manually install Scoop. Wasn't WingetUI supposed to install Scoop during its installation process?
Thank you.

**Comment by martinet101** [comment]
It is, but it might eventually fail. In the about section you will find a table regarding the status of winget and scoop. There you will find if they are installed or not.

**Comment by Hellements** [comment]
Hi,
So I guess I'll just wait for the next update, hopefully you guys can fix this Scoop fail on installation.
Again, thank you.

**Comment by martinet101** [comment]
If you want, you can manually install scoop and see if that fixes the issue

**Comment by martinet101** [comment]
Hi, 

quick question: is you scoop installation a custom one or is it the _standard_ one?

**Comment by martinet101** [comment]
@Hellements,

is this true for you?

**Comment by Spacellary** [comment]
**Scoop | Not Found | Unknown**

![image](https://user-images.githubusercontent.com/39604793/188646812-32591600-0db6-45ef-b783-f266b467f794.png)

I do have scoop properly installed as it works from the Terminal but it is still "Not Found" in the Components.

I also did install WingetUI from scoop but that didn't work aswell.

**Comment by Spacellary** [comment]
> Ok nvm, It showed unknown, but now it's showing fine after I ran `scoop update` through command line and then ran ran wingetui. Not sure if doing the above steps resulted in it working again, but these were the steps that I did before it started working

That did not work for me unfortunately.

> But if I right click on the start menu icon, click open file location and then run wingetui from the shorcut in windows explorer, It runs fine and detects scoop.

Not even that worked for me. I'm cursed.

**Comment by martinet101** [comment]
If you try fully removing WingetUI and then installing WingetUI from the installer or from winget, does it work better?

**Comment by martinet101** [comment]
Also, if you run Scoop-installed WingetUI as admin, does it work better?

**Comment by martinet101** [comment]
Yes, the PR to update is waiting for approval

**Comment by martinet101** [comment]
It'll come soon

**Comment by Spacellary** [comment]
Reporting back: Installing using scoop or the installer for me neither work, with or without admin running directly from each .exe after uninstalling all versions present.

**Comment by martinet101** [comment]
Hi guys, 

those .exe that you can find on the start menu where are they placed? How did they appear? Because I can't find them nowhere.

**Comment by Spacellary** [comment]
In my case I just browsed to the installation directory to find them.

**Comment by martinet101** [comment]
This issue should have been fixed (for users who are still experiencing it) and will be available in WingetUI 1.4

**Comment by newborne** [comment]
对于“Scoop显示未安装或者无法检测到”的问题；
直接运行开始菜单WingetUI的快捷方式，无法检测到Scoop；
定位到wingetui.exe运行，可以检测到Scoop；
手动创建wingetui.exe的快捷方式运行，可以检测到Scoop；
通过对比两个快捷方式发现是用户权限不一样导致的；
解决办法：开始菜单WingetUI快捷方式——右键——属性——安全——赋予【当前用户】允许全部权限——问题解决
