### ISSUE TITLE
UI - Improvement: Instead of saying "installed" say "updated" when updating an app

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#105]
Currently, when an app is updated, it says `<app> was installed`.

Is it possible to separate the executed action by instead saying `<app> was updated`?

**Comment by martinet101** [comment]
I guess yes

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/187730522-88bd9b1e-80e9-480b-ad7a-384e22653c6b.png)
