### ISSUE TITLE
Bug - app Edge WebView2 Runtime: Fails to update

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#106]
Even if the update is run with admin it fails to update.

The cause could be if the user first attempts to update without admin so it erroneously fails even when admin is used afterwards (WingetUI says it was successful, but it's not).

Running `winget upgrade --all` in PowerShell works consistently.

**Comment by martinet101** [comment]
This is a winget thing, and much can't be done about that

![image](https://user-images.githubusercontent.com/53119851/187726195-9c92e3e1-77e3-4114-8276-8985de479a06.png)
