### ISSUE TITLE
Bug - Update apps (Winget): Doesn't detect all apps (last time Firefox)

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#107]
Firefox is installed through Winget.

The package for version 103.0.2 was released 3 days ago at the time of writing.

Running `winget upgrade --all`, this was one of the apps that got updated (the other two were Edge WebView2 (mentioned in issue #106) and erroneously Windows Desktop Runtime 5 (I've Runtime 6 installed and it's a known issue [here](https://github.com/microsoft/winget-cli/issues/2345))).

**Comment by martinet101** [comment]
Has this happened again?

Because this can be some winget temporary cache bug

**Comment by RavenMacDaddy** [comment]
I'll close this for the moment, simply because the need or occurrence hasn't repeated.
