### ISSUE TITLE
WingetUI always shows loading UI components...in win 11 22621

### ISSUE THREAD

**Issue by DiXuanAoYi** [martinet101/WingetUI#108]
![image](https://user-images.githubusercontent.com/39654103/185773882-0fbb6f23-6175-4ecd-a88c-47562f9ec1c5.png)

**Comment by martinet101** [comment]
Will try to run in dev channel and study what happens

**Comment by sunshe35** [comment]
me too and I cann't know what to do.

**Comment by sunshe35** [comment]
![image](https://user-images.githubusercontent.com/16757906/188294775-29d06c95-8c36-47b7-9390-01e76e8cc16c.png)

i have install winget through scoop in  my win10.

**Comment by sunshe35** [comment]
my win10  version
![image](https://user-images.githubusercontent.com/16757906/188294815-742f8eae-e834-4c0d-b80d-d378e83821ee.png)

**Comment by martinet101** [comment]
This might be related with some uncaught error somewhere.

I'll try to sort that and ley tiu know

**Comment by martinet101** [comment]
With the next version any error should be detailed

**Comment by Spacellary** [comment]
Stuck on **Loading UI components...** after running as Admin.

![WingetUI_L92lKyQj9m](https://user-images.githubusercontent.com/39604793/188475264-1544e008-eef5-4f40-8cf1-12a8763eeaee.png)

Installed from the Github  release page Windows installer.

Running Windows 11 22H2 22622.590 (Officially Supported Hardware)

**Comment by martinet101** [comment]
If you run WingetUI without admin what happens?

**Comment by Spacellary** [comment]
> If you run WingetUI without admin what happens?

Then it does launch but for example when I try to winget update something, say, foobar2000, it wont work. As in the "progress" bar at the bottom doesnt move or gets stuck.

**Comment by martinet101** [comment]
Can you please attach a video of the behaviour, as well as attach a screenshot of the "About WingetUI -> Component status" section?

Thanks!

**Comment by martinet101** [comment]
You don't have any error window pop up in your browser, right?

**Comment by Spacellary** [comment]
Nothing pops up, no errors afaik.

**Comment by Spacellary** [comment]
Actually I had that one error as can be seen in the video with TreeSize Free, but I was able to do it with --force in Powershell 7 as follows...
![WindowsTerminal_4zK5KpamCz](https://user-images.githubusercontent.com/39604793/188503028-fffe16d3-2816-4992-b740-ed98ebf86619.png)
...and I believe it is unrelated.


-  [https://youtu.be/xCx79jgto9k](Video or non-admin and admin runs...)

**Comment by martinet101** [comment]
You can use the --force ar on WingetUI, using the "Skip hash check" from the context menu/app info window

**Comment by Spacellary** [comment]
> When running WingetUI as admin, could your hang issue be related to #114?

Actually it is that exact issue! Well looks like we're getting there!

**Comment by martinet101** [comment]
Hi @sunshe35 @DiXuanAoYi, are you running WingetUI as administrator also?

**Comment by sunshe35** [comment]
> Hi @sunshe35 @DiXuanAoYi, are you running WingetUI as administrator also?


yes
I find the new version 1.3.1 works correctly. 
The version 1.3.0.0 is bad.
