### ISSUE TITLE
Bug - Update apps: Pressing Upgrade all packages results in an attempt to install already updated apps

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#109]
For example, let's say when WingetUI has finished loading that it detected something like 5 apps that have updates available, so the user presses Upgrade all packages - but one of them fails to update, so the user attempts to fix the last one easily by pressing Upgrade all packages again.

That will result in the app not only attempting to update the app that's left - but all the apps that were detected during that session.

See the video below.

https://user-images.githubusercontent.com/67732686/185784126-2906dcfa-1c1e-47f6-b497-bcde0d755b28.mp4

**Comment by martinet101** [comment]
Could you please show the error shown in the error boxes?

**Comment by RavenMacDaddy** [comment]
https://user-images.githubusercontent.com/67732686/187735453-32170d4f-b3a7-4077-a0e8-685e7ab9460e.mp4

**Comment by martinet101** [comment]
Done!

Additionally, the button won't update the unknown versions if they were not selected to be shown
