### ISSUE TITLE
Windows: Only the top window can be dragged around

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#110]
Let's say there are error windows present, well only the top window of all the windows present in WingetUI is draggable.

This makes the user unable to for example move any particular window to the position they want, independent of how many are present.

https://user-images.githubusercontent.com/67732686/185785113-f3f94c84-b426-4825-b776-d10275e719ed.mp4

**Comment by martinet101** [comment]
This feature will be fixed with the better warnings issue #39
