### ISSUE TITLE
Add example i18n file

### ISSUE THREAD

**Issue by txyyh** [martinet101/WingetUI#113]
I want to add Simplified Chinese to this project, but I can't find English i18n lanuage file.

How can I contribute i18n lanuage support ?

**Comment by ppvnf** [comment]
Cool, please also contact me if you want help with Portuguese (Brazil)

**Comment by ppvnf** [comment]
It's now possible to translate WingetUI!

**Comment by martinet101** [comment]
Yes, @ppvnf is right. (and I forgot to post that here)

You can find details on how to translate in the wiki
