### ISSUE TITLE
notice Dialog for running WingetUI with admin rights behind the splash/loading screen

### ISSUE THREAD

**Issue by uDEV2019** [martinet101/WingetUI#114]
When launching WingetUI with admin rights, then a notice that this is not recommend appears.
But the notice dialog is hidden behind the splash screen.
You just can hit Enter to confirm the dialog to proceed with the start of WingetUI.

As it is not clear when you got stuck at loading WingetUI, i've used ALT+TAB to see the notice dialog.

![image](https://user-images.githubusercontent.com/51911097/188503401-dc7aa7ec-f21d-49e4-bcef-244de662d0e3.png)

Maybe it's better to bring that notice in front of the splash screen.

Appears with Version 1.3.0

**Comment by martinet101** [comment]
Yes, this would definitely better

**Comment by martinet101** [comment]
Fixed!
