### ISSUE TITLE
why scoop cleanup not working in WingetUI 1.3.0.0

### ISSUE THREAD

**Issue by candrapersada** [martinet101/WingetUI#116]

**Comment by martinet101** [comment]
I disabled it because it was a time-consuming operation (it would delay the launch for a while), and since it is not strictly required in order to have uncached apps and manifests, I didn't thought it was needed.

Anyway, i'll add a switch on the settings

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/188574358-f481d40e-9c6a-456e-bd10-d1746a4344ca.png)
