### ISSUE TITLE
Some packages constantly update or say there is an update - is there an option to clean install over them?

### ISSUE THREAD

**Issue by ROBYER1** [martinet101/WingetUI#118]
See the packages below, I had this issue with OBS Studio package also installed through WingetUI - These packages will continuously say there are updates, when I install all they will install fine and install the correct version but WingetUI insists the wrong version is installed even after restarting the PC and WingetUI.

I wonder if this issue is due to me being on a work laptop where I am not signed in as the admin user, I am a regular non-admin user but using the UAC admin password prompts that show up on install to install packages - I am suspecting that WingetUI may install the packages for the local user only but keep checking the scope of packages installed for all users so there are actually multiple packages installed on the machine due to this.

![image](https://user-images.githubusercontent.com/10745594/188610190-54cb1c5b-bc86-4487-9f19-9d8f06cc9e70.png)

If my assumption is correct, what would you suggest? Is there an option to install packages for all users rather than the current user (when signed in as non-admin user)

**Comment by ROBYER1** [comment]
Seems with any Microsoft Visual C++ distributable or Windows Software Development Kit, the install/update adds a new version but still leaves the old versions installed erroneously. This is probably more down to per-package installer behaviour. 

Other packages like Logitech G Hub always say a new version is available despite only one version of the software being installed 
![image](https://user-images.githubusercontent.com/10745594/188613275-72328ca7-8223-421b-8772-935db1af9dc2.png)

**Comment by ROBYER1** [comment]
I'll have to see if ignore updates persists for this but will close this issue

**Comment by martinet101** [comment]
Yes, it did for me (i faced the same issue hehe)
