### ISSUE TITLE
Winget Python 3.10 unable to install... Where can I specify the right package using the GUI?

### ISSUE THREAD

**Issue by Spacellary** [martinet101/WingetUI#119]
**Winget Python 3.10 unable to install... Where can I specify the right package using the GUI?
Error:**

- 

    1024 KB / 8.82 MB
    2.00 MB / 8.82 MB
    3.00 MB / 8.82 MB
    4.00 MB / 8.82 MB
    5.00 MB / 8.82 MB
    6.00 MB / 8.82 MB
    7.00 MB / 8.82 MB
    8.00 MB / 8.82 MB
    8.82 MB / 8.82 MB
                                                              
Multiple packages found matching input criteria. Please refine the input.
Name     Id                 Source
----------------------------------
Python 3 Python.Python.3.9  winget
Python 3 Python.Python.3.8  winget
Python 3 Python.Python.3.7  winget
Python 3 Python.Python.3.6  winget
Python 3 Python.Python.3.5  winget
Python 3 Python.Python.3.4  winget
Python 3 Python.Python.3.3  winget
Python 3 Python.Python.3.2  winget
Python 3 Python.Python.3.10 winget
Python 3 Python.Python.3.1  winget
Python 3 Python.Python.3.0  winget

![WingetUI_nptAvx26KB](https://user-images.githubusercontent.com/39604793/188643576-29e3ad6c-52b0-476d-be18-abfe110933f0.png)

**Comment by martinet101** [comment]
Ugh, they changed the versioning. This needs to be fixed

**Comment by martinet101** [comment]
Fixed!
