### ISSUE TITLE
v1.3.1: Lots of 'scoop.WARN' entries in the Update section (scoop status/checkup returns nothing)

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#120]
![image](https://user-images.githubusercontent.com/67732686/188707092-a00de5d7-81c5-4211-a7cf-ea5ca33876d8.png)

![image](https://user-images.githubusercontent.com/67732686/188707106-d900522e-e0f8-4410-8c46-57e9cd48e143.png)

Notice also the entry for `bsnes-mt` that's in the list and just says 'Manifest' presented as the new version. (In actuality there's no new version for that app as can be seen in the second screenshot; only Yuzu is mentioned as expected.)

Another one is 'scoop.Name', third one from the bottom.

**Comment by martinet101** [comment]
This issue should have been fixed
