### ISSUE TITLE
Available Updates displays strange records

### ISSUE THREAD

**Issue by Khaos66** [martinet101/WingetUI#122]
Hi! I'm German. 
Maybe this is due to some language differences?
<img width="961" alt="image" src="https://user-images.githubusercontent.com/4013009/188870487-6f3b9744-ee00-442e-b533-cba0e0055911.png">

What command are you running to discover updates? `winget upgrade` returns this on my German system:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/4013009/188870819-acebb9c4-8278-4f5c-a00e-0656b44638de.png">

Are you parsing this using English constants?

**Comment by TSGblue** [comment]
> Hi! I'm German. Maybe this is due to some language differences? <img alt="image" width="961" src="https://user-images.githubusercontent.com/4013009/188870487-6f3b9744-ee00-442e-b533-cba0e0055911.png">
> 
> What command are you running to discover updates? `winget upgrade` returns this on my German system: <img alt="image" width="830" src="https://user-images.githubusercontent.com/4013009/188870819-acebb9c4-8278-4f5c-a00e-0656b44638de.png">
> 
> Are you parsing this using English constants?

Hi Khaos!

I'm spanish and I have the same issue :/

Thanks for reporting it.

**Comment by martinet101** [comment]
No, this is an issue with scoop, and not with winget. If you see, the Winget store updates look fine on the pic you sent

What happens when you run `scoop status` on a cmd window?

**Comment by TSGblue** [comment]
> No, this is an issue with scoop, and not with winget. If you see, the Winget store updates look fine on the pic you sent
> 
> What happens when you run `scoop status` on a cmd window?

Hi @martinet101 ,

First of all, specials thanks for your work ;).

This is the `scoop status` output:
```
PS C:\Users\username> scoop status
WARN  Scoop out of date. Run 'scoop update' to get the latest changes.
PS C:\Users\username> scoop update
Updating Scoop...
Updating 'main' bucket...
 Converting 'main' bucket to git repo...
Checking repo... OK
The main bucket was added successfully.
Scoop was updated successfully!
```
This is the `winget upgrade` output:
```
PS C:\Users\username> winget upgrade
No se encontró ningún paquete que coincida con los criterios de entrada.
1 el paquete tiene un número de versión que no se puede determinar. El uso de "--include-unknown" puede mostrar más resultados.
```
And this is the WingetUI screenshot:
![image](https://user-images.githubusercontent.com/55045958/188886693-b5d628ad-f5bb-4336-8040-badaa4bf19f6.png)

Thanks again and regards.

**Comment by Khaos66** [comment]
`scoop update` returns
<img width="258" alt="image" src="https://user-images.githubusercontent.com/4013009/188897514-453d55d5-e898-427a-b2a7-0cb20191181e.png">

And after closing and opening the UI it looks kind of better.
<img width="756" alt="image" src="https://user-images.githubusercontent.com/4013009/188897729-5b23d1aa-c9be-42fb-af1e-fbde48f23190.png">

There is just this one issue left with `Installed Version` beeing `<`

<img width="820" alt="image" src="https://user-images.githubusercontent.com/4013009/188898031-64ca1e81-a36c-4068-acc5-a542c6912097.png">

**Comment by TSGblue** [comment]
All it's OK after restart for me too.

Thanks both ;)

**Comment by maicol07** [comment]
@martinet101 I have a similar issue: in my case, the window is like this:

![](https://user-images.githubusercontent.com/9463142/188942186-c106a6f1-34fa-4d7b-870f-d7603bcbc28c.png)

Restarting WingetUI fixes the issue, however, it shouldn't bug itself like this after a refresh...

**Comment by maicol07** [comment]
@martinet101 I have a similar issue: in my case, the window is like this:

![](https://user-images.githubusercontent.com/9463142/188942186-c106a6f1-34fa-4d7b-870f-d7603bcbc28c.png)

Restarting WingetUI fixes the issue, however, it shouldn't bug itself like this after a refresh...

**Comment by martinet101** [comment]
This issue has been fixed
