### ISSUE TITLE
Discussion: The described available updates after everything has been updated (still says the initial amount, e.g., 3)

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#124]
![image](https://user-images.githubusercontent.com/67732686/189195713-5e2ea932-6083-47b1-8b43-3426882923ce.png)

What's detected still says _3_ after what was available has been updated in this case.

It isn't reset to _0_ after successfully installing all the available updates.

I do get the potential reasoning behind it (there were X amounts of updates available to begin with), but it risks being misleading in the long-run - especially when taking a look at the tray menu;

![image](https://user-images.githubusercontent.com/67732686/189195241-8c71f214-9e1f-4034-842d-cc8c29df6140.png)

**Comment by martinet101** [comment]
Whoops... 

This gotta be fixed

**Comment by martinet101** [comment]
Done!
