### ISSUE TITLE
[Bug] Right-clicking an empty Update section points to an app that was detected previously (see video)

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#125]
https://user-images.githubusercontent.com/67732686/189194558-d621ba1b-f3d2-4b57-80bb-1c23927570b5.mp4

So Signal had an update available previously that was installed, but right-clicking the Update section that's now empty will still point to that app.

That also means that you could attempt to "update" it again, which will obviously just return errors.

**Comment by martinet101** [comment]
Fixed!
