### ISSUE TITLE
Clarification: How do you view and manage ignored packages (in the Update section)?

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#126]
![image](https://user-images.githubusercontent.com/67732686/189197476-72216c8a-622c-4203-90c1-19306a9d5b41.png)

Related to #125 where I already ignored the Signal package by mistake before making the video.

Also related to #120 where I'm ignoring the erroneous packages that are detected.

How do you actually manage the ignored packages?

Is it currently available, and if so, is it possible to make the feature more prominent as users (e.g., me) were unable to find it?

**Comment by martinet101** [comment]
You have a button in the about section to reset blacklisted apps. 

However, it is quite hidden, and this must be improved. (i was planning to implement a toolbar on the top of each section with some shortcuts instead of a list of pushbuttons, do you think a "reset blacklisted apps" shortcut there could work?)

**Comment by RavenMacDaddy** [comment]
What's described is definitely an improvement. 

If possible, a list where you can manually select what to remove from the Ignore-list is ideal.

Especially since a user potentially has a lot of apps that have been ignored, which they then have to go through every time they use the reset option.

**Comment by martinet101** [comment]
Whis will be slightly more difficult but i'll try to do it.

**Comment by martinet101** [comment]
It does definitely work.

**Comment by RavenMacDaddy** [comment]
Appreciate it @martinet101

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/193116397-aee3471e-cfcb-4790-91ea-c1003dbeacbe.png)
Done!
