### ISSUE TITLE
[Feature Request] A Switch for Theme

### ISSUE THREAD

**Issue by Satanarious** [martinet101/WingetUI#128]
Like the title says, a simple switch to switch between dark or light themes without having to depend on the windows default app theme.
Something like this:

![image](https://user-images.githubusercontent.com/42642682/189463734-4e3a35e8-7005-4f22-9ac3-a7988b89af24.png)

**Comment by martinet101** [comment]
I guess why not

**Comment by ppvnf** [comment]
Related to https://github.com/martinet101/WingetUI/issues/117

**Comment by martinet101** [comment]
Done!
