### ISSUE TITLE
Request: Ability to control autostart (in tray)

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#129]
As one of the options under About.

I do see it's added in the registry, however I don't see an explicit option to control this behavior in the UI.

Obviously, starting the app in the tray (and not throwing up the main window every time the user has logged in) makes the most sense.

![image](https://user-images.githubusercontent.com/67732686/189471774-e9e922ee-457e-45a4-8de1-afc905cf115b.png)

**Comment by martinet101** [comment]
The option to control this is tyhe option that rules the taskbar icon tray.

**Comment by RavenMacDaddy** [comment]
Maybe it could also say "(enables autostart)".

Interestingly it didn't

**Comment by martinet101** [comment]
> Interestingly, disabling the option doesn't actually remove the startup entry;

Nope, it does not, (honestly I prefer not to mess with windows registry). Instead, at the very start of the script the app will exit if it was launched with the `--daemon` argument (this agrument triggers the system tray icon without the UI)

**Comment by RavenMacDaddy** [comment]
So, it only adds an entry - but the user has to dig in the registry to actually remove it?

How about adding an entry to the startup folder, then? (run `shell:startup`)

**Comment by martinet101** [comment]
It was actually the first thing I did, but i couldn't get the parameters to work with Inno setup. 

Regarding a full enable/disabe, It still can be fully disabled from Task manager and from startup apps settings, so there's not a big issue with this.

**Comment by RavenMacDaddy** [comment]
I do agree that it's not hard for a user with somewhat of a computer interest, however the phrase as it's now, I personally interpret as "keep the app running during this session", if I have that option selected. 

Combine that with the fact that unchecking the option _doesn't_ actually remove the startup entry _that's_ created - sends mixed messages.

**Comment by martinet101** [comment]
Yes, this would make more sense.

**Comment by martinet101** [comment]
Done!
