### ISSUE TITLE
Bug: Window title doesn't blend in with the background

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#13]
![image](https://user-images.githubusercontent.com/67732686/169354011-b0e1ff46-be99-4a0c-aad5-53f9deadc612.png)

Notice how there's a black text background present, while the actual window is dark grey.

This is on Windows 11.

**Comment by martinet101** [comment]
That's a windows bug that will be fixed on Windows 11 22h2, and much can't be done about that.

With Windows 11 on beta channel it looks as it should
![image](https://user-images.githubusercontent.com/53119851/169376329-c5be16a7-0e29-4d86-afd3-0a1cb657a592.png)

**Comment by RavenMacDaddy** [comment]
Understood, thanks for the info.
