### ISSUE TITLE
Bug: Flickering icon in the About section - or completely unable to load (causes glitches)

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#131]
The cup up to the right, as it always reloads media upon showing the element.

This also makes the text to the left of it move back and forth.

https://user-images.githubusercontent.com/67732686/189471243-61583607-2f2b-4347-8966-0f16696a4acb.mp4

When unable to load (notice how this makes the supposed fixed text at the top cut-off and a scrollbar appearing; resizing the window to make it larger doesn't remedy this):

![image](https://user-images.githubusercontent.com/67732686/189471794-c0d5d438-e195-4cf6-833c-4979f60f2842.png)

**Comment by martinet101** [comment]
This is web-based content (not HTML) but rather text and an image. It is loaded every time after the UI shows to be able to adapt to the available size of the window. I'll try to make the icon persistent though

**Comment by martinet101** [comment]
Fixed!
