### ISSUE TITLE
Request – Update: Add a button at the top for “Ignore the selected packages”

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#132]
![image](https://user-images.githubusercontent.com/67732686/189519353-7043c510-08cc-4e98-aaae-e1ef60d60c0f.png)

**Comment by martinet101** [comment]
Yep

**Comment by RavenMacDaddy** [comment]
If possible, slightly separating it horizontally from the other two would work better, as the actions are in two different categories.

**Comment by ppvnf** [comment]
After reading https://github.com/martinet101/WingetUI/issues/111 I had this idea (adding a select all button). I made a concept image, although I'm no artist: 
![189519353-7043c510-08cc-4e98-aaae-e1ef60d60c0f](https://user-images.githubusercontent.com/73800734/191320344-faa11f8e-d73c-4550-b305-264f37c0f598.png)

**Comment by martinet101** [comment]
Yeah, something like this.

I was thinking in something like a toolbar, but it will work anyways

**Comment by martinet101** [comment]
Done! (the toolbar will come in a future)
