### ISSUE TITLE
Bug: Even if the app is periodically checking for updates, it's doing so without updating the repositories

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#133]
I could literally see the Update section refresh coincidentally as I was doing other stuff (since periodically checking for updates is enabled in the About section).

However, it's not updating the repositories, e.g., for Winget and Scoop, so obviously nothing shows up.

![image](https://user-images.githubusercontent.com/67732686/189519457-2ff218fe-e426-40dc-8cbd-78ef35794e12.png)

![image](https://user-images.githubusercontent.com/67732686/189519459-69892fd2-12e1-46d0-9326-f2169ef16f40.png)

After manually updating through CLI:

![image](https://user-images.githubusercontent.com/67732686/189519606-79f72d5a-3728-4a54-8b40-14d9a976902e.png)

…and then refreshing in WingetUI:

![image](https://user-images.githubusercontent.com/67732686/189519622-2b3468f3-7a9d-40f8-84e1-cd59721ebb61.png)

**Comment by martinet101** [comment]
I see the issue on scoop, but Winget does automatically do that before listing the updates, if the inex is older than x hour(s)

**Comment by RavenMacDaddy** [comment]
Good, that's part of the issue solved then. :)

**Comment by martinet101** [comment]
Done!
