### ISSUE TITLE
Request: Use GSudo from Scoop when available (more up-to-date)

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#134]
![image](https://user-images.githubusercontent.com/67732686/189520706-1c9687b7-bb7a-4da4-a7a5-3ca48412066c.png)

![image](https://user-images.githubusercontent.com/67732686/189520713-f38f6c3d-d69b-40e1-818e-42dba50e7517.png)

Either that or somehow keeping the GSudo component of WingetUI in line with the release.

**Comment by martinet101** [comment]
Honestly, i'd prefer to stick it with the installer, for the same reason as winget is also bundled appart. To prevent api changes that massively break the app and require urgent fix releases.

However, a switch for this behaviour could be added

**Comment by martinet101** [comment]
Done!
