### ISSUE TITLE
wrong update version

### ISSUE THREAD

**Issue by HarkTu** [martinet101/WingetUI#135]
getting wrong update notification
![resim](https://user-images.githubusercontent.com/46054251/190153119-5a076ccd-f974-4144-9160-2eb06a2a4574.png)

**Comment by martinet101** [comment]
Hi, 

Does this still happen when you reload?

**Comment by HarkTu** [comment]
after reload
![resim](https://user-images.githubusercontent.com/46054251/190219066-9703fdff-1cc0-4f43-ab20-ce3b073fe5ad.png)
still not what I expect but got the reason. I can ignore it but that way I wont receive updates for jdk11 also :/

**Comment by martinet101** [comment]
Hi,

The glitch shown in the first pic is a known issue and will be fixed soon.

However, the issues with apps not updating are winget errors, and much can't be done about it. I'm sorry

**Comment by martinet101** [comment]
The issue has been fixed and the fix will come with the next release
