### ISSUE TITLE
Error "0x80190194 : Not found (404)" for updates

### ISSUE THREAD

**Issue by reaseno** [martinet101/WingetUI#137]
I just installed WingetGUI and now wanted to do some updates of already installed software. But so far I get the error message for all tested programs:

An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).

I have never used winget before. Is that maybe the problem?

WingetGUI 1.3.1

EDIT: I also tried this with winget in the command line and get the same error there. So it is not a problem of the WingetGUI.

**Comment by martinet101** [comment]
> EDIT: I also tried this with winget in the command line and get the same error there. So it is not a problem of the WingetGUI

I guess so. There might be some kind of issue with the installer's URL, but, as you said, i can't do much about that
