### ISSUE TITLE
strange scoop messages in update tab

### ISSUE THREAD

**Issue by reaseno** [martinet101/WingetUI#138]
Errors after refresh in update tab:
![image](https://user-images.githubusercontent.com/3628985/190376155-82375f88-ac2e-49ad-8b89-1efeb81d3f2e.png)

Had that error two times now.

WingetGUI 1.3.1
No scoop installed

**Comment by raingros** [comment]
Same here on Windows 10 21H2 Build 19044.2006.
![2022-09-15_144917-wingetui](https://user-images.githubusercontent.com/7615357/190408185-f9a64143-e902-42e2-ad14-5076bc524a27.png)

**Comment by reaseno** [comment]
This happens every time I click the Update/Reload button in the Software Updates tab.

**Comment by reaseno** [comment]
Duplicate to #120

**Comment by ppvnf** [comment]
I also had a similar issue [#92](https://github.com/martinet101/WingetUI/issues/92). As a workaround I am running WingetUI as admin

**Comment by martinet101** [comment]
Hi @reaseno and @raingros, do you have scoop installed?

**Comment by JonathanPitre** [comment]
I'm not able to check any options in the About section, even when I run the tool as an admin

**Comment by martinet101** [comment]
Can you please try removing a folder called .WingetUI placed in your user home directory?

**Comment by JonathanPitre** [comment]
Yes I've tried that but the issue remains. I can't check any of the options. I even did a clean installation yesterday. I did install the software in C:\Program Files\WinGetUI instead of %localappdata%. Do you think that could be the issue ?

**Comment by martinet101** [comment]
It _shouldn't_, but it might actually be. Can you please try installing in the default location?

**Comment by JonathanPitre** [comment]
yes same result

**Comment by reaseno** [comment]
> Hi @reaseno and @raingros, do you have scoop installed?

I had this problem before I installed the scoop. Now that it is installed, I can no longer see the issue.

**Comment by martinet101** [comment]
I suppose this issue can be closed then, right?

**Comment by reaseno** [comment]
> I suppose this issue can be closed then, right?

If you have fixed it by not running scoop when it is not found in the system, then it can be closed. Otherwise, the error persists for people who have not installed scoop and have not disabled it in the WingetUI settings.

**Comment by martinet101** [comment]
The thing is that scoop was supposed to be installed automatically, and now the issue preventing it from being installed should be fixed

**Comment by reaseno** [comment]
Ah, I didn't know that. I don't think it's a good idea to install scoop automatically.

It would be better if scoop were only an optional additional source, because then there would be duplicate packages, which could confuse some people. And not everyone wants to deal with scoop, which also has a different philosophy than winget. Besides, your programme is called WingetUI and not General Windows Package Manager UI or Winget/scoopUI.

**Comment by martinet101** [comment]
> BTW, when will the next version of WingetUI be released?

It has been released (v1.4.1)
