### ISSUE TITLE
ideas for admin handling

### ISSUE THREAD

**Issue by reaseno** [martinet101/WingetUI#141]
I think it would be better if the information that the program is running with admin rights is displayed only once. Instead, there could be an indicator that makes it visible in the program that it is running with admin rights. Maybe an icon. Currently I already set in the linkage that it should be started with admin rights, because it makes sense for most of my installations. Alternatively, it would need to allow setups to ask for admin rights. If that can be done, that would be ok for me too.

Otherwise, it would help to have an option, with which you can set, even if you started the program with admin rights, that scoop gets only normal rights, because it is rather undesirable there.

**Comment by martinet101** [comment]
> Alternatively, it would need to allow setups to ask for admin rights. If that can be done, that would be ok for me too.

This can be done if you right-click any package





Anyway, what you say makes sense

**Comment by reaseno** [comment]
> This can be done if you right-click any package

This way it takes too many clicks and so I can forget about it more easily 😅

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/191275202-c9dfd68d-1ef6-4135-b13a-43f6eb604f99.png)

Done!

A disctinctive will be shown in the top-left section when wingetUI is ran as admin

**Comment by candrapersada** [comment]
will there be support for installing, updating and removing packages as admin+global like `sudo scoop install <manifest> -g` `sudo scoop update <manifest> -g` `sudo scoop uninstall <manifest> -g` `sudo scoop uninstall -p <manifest> -g` `sudo scoop cleanup -g *`
