### ISSUE TITLE
Design inconsistency in the search bar

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#143]
I think the border line shoud be higher in order to surround the black bar above "Undo":
![Captura de tela 2022-09-17 100339](https://user-images.githubusercontent.com/73800734/190860065-a4b703ec-6244-4e05-bd41-62bbda427d7b.png)
Also, I think the greyed out text color (in dark mode) is misleading when you are able to use the button and vice versa:
![Captura de tela 2022-09-17 100414](https://user-images.githubusercontent.com/73800734/190860104-a95c0080-c46c-4a3a-afbd-ee59aaa4eeeb.png)

**Comment by martinet101** [comment]
Yes, it looks like those menus need to get fixed

**Comment by martinet101** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/53119851/191208393-90502eab-b780-4764-bfb3-5c7cf2afe44d.png)
