### ISSUE TITLE
Unable to completely see package version in "Discover Software"

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#146]
In "Installed applications" it's possible to fully see the app version, but in "Discover Software" it's not possible depending on the version length. Example:
![Captura de tela 2022-09-20 132423](https://user-images.githubusercontent.com/73800734/191313596-513eb4ea-6d8a-4610-bdec-8cbe8aa82daf.png)
![Captura de tela 2022-09-20 132445](https://user-images.githubusercontent.com/73800734/191313605-7fd8b748-12d5-4e09-afca-9712589dd4c3.png)

**Comment by martinet101** [comment]
Hi @ppvnf, if you expand the column, does the full version show or it still apperas with the three dots?

**Comment by ppvnf** [comment]
> Hi @ppvnf, if you expand the column, does the full version show or it still apperas with the three dots?

I am unable to expand any column (I can only move the columns and this has no effect in the amount of text shown). 

In "discover software" and "software updates" the three dots always appear after 8 characters in the version field. And in "Installed applications" the column is automatically expanded to show the full version number. I tried clicking "show info" to find out the package version, but this information was not displayed.

I noticed another thing that is not possible to be shown because of the three dots: the package name and ID. While in "discover software" and "software updates" this is not an issue because you can click "show info" and see it, in "installed applications" you cannot fully see the package name and id as the "show info" option is not avaiable in the context menu:

![Captura de tela 2022-09-20 144045](https://user-images.githubusercontent.com/73800734/191327161-2a3ae2f4-f6df-4f88-b3dd-f3c5df294d2d.png)

So, an option to solve the issue of not being able to completely see the version number, besides automatically expanding the version field in "discover software" and "software updates" like "Installed applications" already does, would be to show the app version when you click "show info". Also, "show info" should be enabled in "Installed applications" to be possible to fully see the package name and ID.

**Comment by martinet101** [comment]
> Also, "show info" should be enabled in "Installed applications" to be possible to fully see the package name and ID.

That's a major issue with winget. winget lists every package installed on the system, regardless if it came from winget or not, and it reports the name and id regiestered on the _system registry_, which makes it impossible for it to retrieve package info from winget servers. 

Regarding the version tab, i'll just make it a little bit wider and i'll also try to make it resizable also

**Comment by ppvnf** [comment]
> 
Thanks, would it be possible to enable "show info" just for scoop packages installed then?

**Comment by martinet101** [comment]
I guess so

**Comment by martinet101** [comment]
Done!
