### ISSUE TITLE
Improve the ability to copy inside "show info"

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#147]
It's possible to copy some information inside "show info" menu using ctrl+c, but there's no button to copy when you right click (the only option to copy is the keyboard shortcut). Also, not every information is possible to be copied this way. It would also be helpful if you could add the package version inside "show info" and be able to copy it. I will highlight what is not possible to be copied:

![Captura de tela 2022-09-20 153535 - Copia](https://user-images.githubusercontent.com/73800734/191340168-7509a262-9eb3-44f0-9596-d19597326c40.png)

**Comment by martinet101** [comment]
I guess some kind of context menu can be added...

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/192149701-cf1912d4-2fe4-4446-ab4e-096e48886a33.png)

Done!
