### ISSUE TITLE
Firefox Dev Edition Name Bug

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#149]
This package has a bug in the name displayed by WingetUI in the install tab. 

![Captura de tela 2022-09-23 221817](https://user-images.githubusercontent.com/73800734/192076204-1651ae9e-cf39-43ac-b526-80141109edf8.png)

As a result WingetUI doesn't allow it to be uninstalled. 

![Captura de tela 2022-09-23 222208](https://user-images.githubusercontent.com/73800734/192076221-0353f9b4-0e36-4830-bf57-e117e41ac717.png)

However in the Discover Software tab the package name is correct. 

![Captura de tela 2022-09-23 221802](https://user-images.githubusercontent.com/73800734/192076242-b79750c9-df0f-4070-837b-55930164090c.png)

PowerShell worked just fine though. 

![Captura de tela 2022-09-23 222319](https://user-images.githubusercontent.com/73800734/192076219-ffcbbefa-f577-43ae-b5e5-ac59c8a8e6d6.png)

**Comment by ppvnf** [comment]
Maybe related https://github.com/microsoft/winget-pkgs/issues/79299

**Comment by martinet101** [comment]
This is a winget bug, where installed apps don't get registered with their proper app id/names, and then updates get messed up.
