### ISSUE TITLE
[UI] Window title background is black

### ISSUE THREAD

**Issue by tippf3hlr** [martinet101/WingetUI#150]
![grafik](https://user-images.githubusercontent.com/46620049/192093783-afeca641-fb1a-4a53-910a-43cc51dc3b39.png)

Is this intentional?
If not, I think it would look better without it.

**Comment by martinet101** [comment]
Hi,

This is a bug with Windows 11 21h2. 

If you update to W11 22h2 (the update is aleady available), you'll see this fixed
