### ISSUE TITLE
Improvements to info view

### ISSUE THREAD

**Issue by martinet101** [martinet101/WingetUI#154]
- [x] Make it draggable
 - [ ] Show the installed version (if present)
 - [x] Faster scoop load by doubling the query

**Comment by ppvnf** [comment]
I think the info view, besides showing the installed version (if present), should also show the latest version available, at least in Discover Software. If I am not mistaken your answer in https://github.com/martinet101/WingetUI/issues/146#issuecomment-1252759355 was just regarding showing the latest version in installed applications.

**Comment by martinet101** [comment]
It will show the latest version available

**Comment by martinet101** [comment]
Done!
