### ISSUE TITLE
Feature Request: Usability of Software Updates screen (Select All / None, keyboard)

### ISSUE THREAD

**Issue by gerardog** [martinet101/WingetUI#155]
Hi !
Good Job Martí ! This is a very promising tool !

Found a few usability issues that you may want to address:

### 1. Add Select All, Select None buttons. 
- Context: First time user, wants to update several apps, with fewer clicks/keystrokes as possible.
   - But I want to select which ones.
   - I would click `Select None`, then manually select a few.
- Improve Keyboard navigation: Space should check/uncheck.
- Maybe button `Upgrade All` not needed if  `Upgrade selected` and `Select All` exists.
![image](https://user-images.githubusercontent.com/3901474/192180977-6d89b473-0e69-4d80-99d5-23ce0a9db20c.png)

### 3. Right click should have uninstall option.
- Context: 
    - Looking for software to upgrade.
    - Found Garbage v1.0 is outdated and v2.0 is available.
    - No thanks, uninstall right now.
    - (right click, no uninstall option)

Thanks for making this tool!

**Comment by martinet101** [comment]
Done!

**Comment by martinet101** [comment]
Done!
