### ISSUE TITLE
Add the toolbar

### ISSUE THREAD

**Issue by martinet101** [martinet101/WingetUI#156]
Because the updates section (mainly) needs it, and maybe extend it to the uninstall section.

This toolbar was discussed in (#155) (#126) and (#132) and somewhere else that i couldn't find.

TODO:
 - [x] Add the toolbar
 - [x] Implement already present buttons (update all, update selected, blacklist selected apps)
 - [x] Implement button to reset blacklist (proper UI will come later (see #126))
 - [x] Implement select none/all buttons (#155)
 - [x] Add clear button to the text boxes

**Comment by ppvnf** [comment]
We also discussed it in https://github.com/martinet101/WingetUI/issues/132
Thanks for all your hard work already done and planned, @martinet101

**Comment by martinet101** [comment]
Yep!

**Comment by martinet101** [comment]
Done!
