### ISSUE TITLE
Silent install / install parameter (global)

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#157]
I dislike seeing the installer when installing a Winget package, so my suggestion is to add an option in the settings to enable global silent install/uninstall/update option. An alternative would be to add a global install parameter. 

By the way, `--silent` alone is enough for a silent install and `--accept-package-agreements` `--accept-source-agreements` are useless since Winget agrees with everything by default, right?

Related:
https://github.com/martinet101/WingetUI/issues/140 (for individual packages I believe)
https://github.com/martinet101/WingetUI/issues/44 (I didn't quite understand the discussion there about unattended/silent install. I know installation through WingetUI is unattended, why can't it be silent also?)

**EDIT**:

I think I figured out what you mean in https://github.com/martinet101/WingetUI/issues/44. WingetUI uses `--silent`, but this command sometimes doesn't work properly, isn't it?

I've tested updating Pinta directly through Winget and through WingetUI. Both display a pop-up. However, this [script ](https://github.com/Romanitho/Winget-AutoUpdate) apparently uses a workaround to have completely silent updates (I also found this [comment](https://github.com/microsoft/winget-cli/issues/2265#issuecomment-1161420413) interesting).

Would launching a hidden powershell/cmd window be enough to accomplish this or do you think it is a problem for Microsoft to fix? 

On a second thought, I don't think a global install parameter would be useful to achieve a silent install. So, unless there's a reason, you may ignore it.

**Comment by martinet101** [comment]
It seems to work, at least partially.
