### ISSUE TITLE
Clicking the update notification should open "Software updates"

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#158]
I think clicking the update notification should open WingetUI "Software updates" tab instead of "Discover Software".

If it is possible, what do you think about adding a button in the notification to install updates? 

Mac also has an option for delaying updates, but I don't think it makes much sense if WingetUI is able to configure the interval for checking updates https://github.com/martinet101/WingetUI/issues/44:

![](https://en.freedownloadmanager.org/img_howto/0/239/updates_available.jpg)

**Comment by martinet101** [comment]
> If it is possible, what do you think about adding a button in the notification to install updates?

Adding interactive notifications is not possible in Win32 apps, because they require the WinUI/XAML api.



> I think clicking the update notification should open WingetUI "Software updates" tab instead of "Discover Software".

Yes, makes sense

**Comment by martinet101** [comment]
Done!

**Comment by ppvnf** [comment]
Thanks. Just to clarify https://github.com/martinet101/WingetUI/commit/33bb443086a9d0f56fcba9f5a05fab13021b0204, clicking the notification itself will also open the update section, right? And I think clicking the tray icon should only open the update section when there's an update available.

**Comment by martinet101** [comment]
> clicking the notification itself will also open the update section

yes, since the show function is the same



> clicking the tray icon only opens the update section when there's an update available?

Gotta do that

**Comment by martinet101** [comment]
Done!
