### ISSUE TITLE
Show the number of available updates when hovering the systray icon

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#159]
Just after you fixed the previous issue I had this idea, but I created a new one to make things more organized. 

It's also a very small detail. When you hover the WingetUI icon in the system tray it will always shows "WingetUI", even if there are updates available.  What do you think about replacing "WingetUI" with the number of available updates?

[Mailspring](https://github.com/Foundry376/Mailspring) does something like this for the number of unread messages (in cases there's no update available I believe it's better to show the app name though):

![Captura de tela 2022-09-27 161642](https://user-images.githubusercontent.com/73800734/192616006-b4829e7a-ba58-4652-afff-97fd0e3f4e1a.png)

Related:
#124
https://github.com/martinet101/WingetUI/issues/158
https://github.com/martinet101/WingetUI/issues/44

**Comment by martinet101** [comment]
I guess this has more to do with #124...

**Comment by martinet101** [comment]
Done!
