### ISSUE TITLE
Feature request: Pressing Tab to switch between sections

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#16]
Basically pressing Tab to switch to the next section to the right and Shift-Tab to go left; vice versa.  

Either that or involving CTRL similar to web browsers. 

Hopefully wrap-around doesn't present any issues.

**Comment by martinet101** [comment]
I don't think Tab/Shift tab can be an option, since they are used to switch focus between widgets. However, Ctrl+Tab/Ctrl+Shift+Tab would be a better idea, since they are the common toggle to change tabs in most applications

**Comment by RavenMacDaddy** [comment]
Agree

**Comment by martinet101** [comment]
Done!
