### ISSUE TITLE
Just installed WingetUI in the update tab there are some unidentified items. Image attached.

### ISSUE THREAD

**Issue by oooooooooooooooo** [martinet101/WingetUI#161]
OS: Windows 11 22h2 22622

![image](https://user-images.githubusercontent.com/8386495/192892076-bd928cea-59fb-43d9-a90c-63cd60e91665.png)

For now, just leaving them unchecked. Apologise if this is known, I did try looking through the closed issues to see if this was reported before. Didn't see anything about these on the Homepage unless they're part of "scoop bucket add extras"

**Comment by ppvnf** [comment]
Hello, I also faced a similar issue. If I am not mistaken this error should be fixed when WingetUI 1.4 is released: https://github.com/martinet101/WingetUI/issues/104#issuecomment-1261148602

Another user reported a possible solution to this problem: https://github.com/martinet101/WingetUI/issues/138#issuecomment-1261403442

Related:

https://github.com/martinet101/WingetUI/issues/92, https://github.com/martinet101/WingetUI/issues/104, https://github.com/martinet101/WingetUI/issues/120, https://github.com/martinet101/WingetUI/issues/122 and #138
