### ISSUE TITLE
Visual indicator for new/installed versions

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#164]
In available updates there are visual indicators for new/installed versions:

![Captura de tela 2022-09-29 114957](https://user-images.githubusercontent.com/73800734/193065099-eed6a359-3071-48f5-90a1-e949323234f7.png)

I think this should be improved: In installed packages there is a visual indicator only for the installed version (the new version appears without the icon):

![Captura de tela 2022-09-29 114943](https://user-images.githubusercontent.com/73800734/193065105-51908b22-5149-4e9e-bcf1-4e49edf22a9c.png)

Also, in the discovery tab, would it be possible to show what's the installed version or just show an icon to indicate that it was installed?

![Captura de tela 2022-09-29 120110](https://user-images.githubusercontent.com/73800734/193068442-47b171d1-0bda-4771-9f55-246444dcddaa.png)

**Comment by martinet101** [comment]
> Also, in the discovery tab, would it be possible to show what's the installed version or just show an icon to indicate that it was installed?

Thst would mean an intensive iteration on the installed apps for each available package, while some installed packages don't share the same ID that the one provided by winget, and for updates you can really Ctrl+Tab to the Updates section.

I don't think this feature should be in WingetUI

**Comment by ppvnf** [comment]
@martinet101 Yes, I get it that adding this feature to the "discovery" tab isn't worth it. But look at the second screenshot. I didn't modify it. WingetUI already shows the new version number in Installed applications. However, there's no indication that it's a new version. So the first time I saw it I mistakenly thought it was the current version.

**Comment by martinet101** [comment]
> Edit: I just noticed that scoop apps in the install section do not display the new version number. So, is it a bug for Winget packages to display the new version in the uninstall section?

I think it is, actually.

**Comment by ppvnf** [comment]
1.4 fixes this bug, thanks!
