### ISSUE TITLE
"add bucket to scoop" "not" working by default

### ISSUE THREAD

**Issue by ianalexis** [martinet101/WingetUI#165]
When im installing WingetUI from winget the "add bucket to scoop" is not working by default.
When a bucket is added it shows the "Done" message but it wont work. 
To solve it i needed to install git for it.

Maybe a git check when add a bucket whit a little message could solve it.

**Comment by martinet101** [comment]
Yep, scoop needs git in order to work.

It should be installed by default, but sometimes the installer fails to do so

**Comment by martinet101** [comment]
Gonna check why does it fail

**Comment by martinet101** [comment]
The installer will now install git also
