### ISSUE TITLE
Suggestion: show the number of available updates in the taskbar icon

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#169]
For example:

![Captura de tela 2022-09-30 160843](https://user-images.githubusercontent.com/73800734/193341465-0e4ec906-0b7f-43d0-9131-d0b99d66989c.png)
![Captura de tela 2022-09-30 125500](https://user-images.githubusercontent.com/73800734/193341468-7d567d12-9f38-473c-916a-c9bdf6c43a41.png)

**Comment by ppvnf** [comment]
1. I know To Do List is UWP, but I don't think [Ferdium](https://github.com/ferdium/ferdium-app) (second picture) and [Mailspring ](https://github.com/Foundry376/Mailspring)are (pic below).

![Captura de tela 2022-09-30 172916](https://user-images.githubusercontent.com/73800734/193351513-0fb50622-792e-4d4e-b9a7-6b502b376c84.png)

2. Because the systray is smaller than the taskbar, I think it makes sense not to display the number of updates there. So I don't think you have to change the systray icon behavior (if you do decide to implement this feature) to add the update number to the taskbar though.

3. Yes, I know it's redundant and not really an essential feature. The taskbar is bigger than the systray and you don't have to click/hover the mouse to see the number of updates. However, I understand if you feel it isn't worth it.

**Comment by martinet101** [comment]
> 3. Yes, I know it's redundant and not really an essential feature. The taskbar is bigger than the systray and you don't have to click/hover the mouse to see the number of updates. However, I understand if you feel it isn't worth it.

I think it is not worth it because non-UWP apps require custom taskbar icons for counter badges (if you check, the icon you show dones't follow the system-styled top-right accent-colored badge, but a custom one). Also, you'd have to maintain the WingetUI open in order to have this feature, because otherwise the icon would fallback to the executable one.
