### ISSUE TITLE
v1.4 Packages not correctly identified

### ISSUE THREAD

**Issue by gerardog** [martinet101/WingetUI#172]
See the Package Id column issue:
![image](https://user-images.githubusercontent.com/3901474/193414177-b9f6c345-ffd5-4cb5-81ac-ee7643d66cc5.png)

May be the cause for the package id not recognized on `winget upgrade`
![image](https://user-images.githubusercontent.com/3901474/193414207-cfeab0f6-28eb-4da1-9dda-d40e1190bb45.png)

**Comment by gerardog** [comment]
...after installing 1.4.0
Using Win11 21H2

**Comment by SailorZOfficial** [comment]
I was introduced to this winget ui app today, installed it via winget on powershell and ran into this same issue IMMEDIATELY. This should be marked as a priority item and swarmed asap (in my '_professional_' opinion that is lol)

**Comment by martinet101** [comment]
yeah, this shouldn't be happening. 

Is it happening always or it happens only some times?
does this also happen in the uninstall section?

**Comment by gerardog** [comment]
> Is it happening always or it happens only some times?

The more I retry, the less it happens. 

> does this also happen in the uninstall section?

Yes, and sometimes in that section but not the updates one.

**Comment by martinet101** [comment]
Guys, can you please share your WingetUI logs? you can get them by clicking on the three dots menu (...) in the top.right corner of the window and then -> WingetUI logs

**Comment by gerardog** [comment]
I wasn't able to reproduce it anymore untill I restarted

This log is with both Updates and Installed tabs failing

[WingetUILog.txt](https://github.com/martinet101/WingetUI/files/9690936/WingetUILog.txt)

**Comment by gerardog** [comment]
So the problem is parsing WinGet output.
Unicode, Latin, long names may be a problem.
I have some spañish apps installed.

This line in v1.4 is related to some unicode hanlding, but never getting inside the ELSE part.
https://github.com/martinet101/WingetUI/blob/3070c8f41154312f2001f9f02882deeae1fc8cbd/wingetui/wingetHelpers.py#L20

**Comment by martinet101** [comment]
Hi guys, do you have python knowledge? could you please try the latest head?

If not, please try the .zip file i'll attach here in a few minutes

**Comment by martinet101** [comment]
https://drive.google.com/file/d/101DwZGsnN2DKtyOyuUSD_TT1fqj8_F0K/view?usp=sharing

**Comment by gerardog** [comment]
The attach didnt workd. Building from scratch...

Did not ended well.. a few comments/ideas...

![image](https://user-images.githubusercontent.com/3901474/193427926-6dd6db4a-ce13-4d8d-88f4-f8e0cfc16965.png)

- In requirements.txt PyInstaller is missing.
- In build.bat append `|| exit /b %errorlever%` to abort on failure, like `python -m PyInstaller "Win.spec" || exit /b %errorlever%`
- Also, prefer paths using [`%~dp0`](https://stackoverflow.com/questions/5034076/what-does-dp0-mean-and-how-does-it-work)

**Comment by gerardog** [comment]
Well, the zip file worked at the 2nd attempt... But still failed, this time Installed Applications worked, but Updates did not.

[WingetUILog2.txt](https://github.com/martinet101/WingetUI/files/9691186/WingetUILog2.txt)

**Comment by martinet101** [comment]
I'm dumb. I replaced the misleading character in the count but forgto to .strip() the resulting string before counting the length...

Can you please test again the google drive file (i have updated the contents, but the URL still the same)?

**Comment by gerardog** [comment]
I've tested a few times and so far it's working.

**Comment by gerardog** [comment]
Yes, that fixes it. Release it!

**Comment by martinet101** [comment]
Yes, I'll fix a few annoying bugs and I'll release 1.4.1 disay or tomorrow

**Comment by ppvnf** [comment]
In my system this bug only happens with the install version of WingetUI. Portable/scoop version correctly display the packages

**Comment by martinet101** [comment]
Ok, will release v1.4.1 this afternoon
