### ISSUE TITLE
Bug – v1.3.1: Exiting the app (from the tray) doesn't update to v1.4

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#173]
When I previously only had it running in the foreground, closing it out would result in the app updating itself if there was a new version available.

However, now with v1.4 available, exiting the app in the tray didn't result in the app updating itself (also did multiple attempts to give the app a chance).

One possible improvement would be to add options in the app to proceed with installing the available update, e.g., in the About section, as well as the tray menu.

**Comment by martinet101** [comment]
I have realised, and this is a bug. The app should update itself.

However, while i'll fix that, in the following hours version 1.4 will (hopefully) be approved on Winget, so everyone will be able to easily update

**Comment by martinet101** [comment]
Done!
