### ISSUE TITLE
Version 1.4: Context menu improvements

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#175]
- [x] Right-clicking select all in the info menu is always disabled. "Ctrl + A" works though

![Captura de tela 2022-10-01 123925](https://user-images.githubusercontent.com/73800734/193417068-94cd7a9e-76f1-405b-8171-bd2b71a713ef.png)

- [ ] "Undo" and "Paste" shouldn't be greyed out if you can use them (this happens only if the search bar is empty)

![Captura de tela 2022-10-01 124044](https://user-images.githubusercontent.com/73800734/193417172-cf5d6866-8cf2-46a4-9190-bdde5201b5af.png)

![Captura de tela 2022-10-01 123454](https://user-images.githubusercontent.com/73800734/193417177-3ab6df83-9d47-4b33-966f-7836825fe529.png)

**Comment by martinet101** [comment]
> * "Undo" and "Paste" shouldn't be greyed out if you can use them (this happens only if the search bar is empty)

I'll take a look, though this is more a Tq but rather than a WingetUI issue...

**Comment by ppvnf** [comment]
@martinet101 I remember you fixed a similar issue https://github.com/martinet101/WingetUI/issues/143

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/208180996-76146c9d-021a-4e0a-8678-13aedd181155.png)
The 1st issue was alreadu fixed. 

The second issue is indeed a Qt issue and can't be fixed

**Comment by ppvnf** [comment]
> * [ ]  "Undo" and "Paste" shouldn't be greyed out if you can use them (this happens only if the search bar is empty)

Would it be possible a workaround like forcing "undo" and "paste" to never be greyed out?

**Comment by marticliment** [comment]
They are already set to be white, but they do not follow the stylesheet for whatever the reason.

**Comment by ppvnf** [comment]
And how about making everything white? I believe it would at least better than everything grey

**Comment by marticliment** [comment]
But then disabled options would be also white, and, for the amount of people that use this menu when no text is on the textbox and the amount of people that can differentiate enabled vs disabled entries i don't think it is worth it

**Comment by ppvnf** [comment]
Yes, you are probably right
