### ISSUE TITLE
v1.4 – Redundant text/grammar – Scoop installation script

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#177]
![image](https://user-images.githubusercontent.com/67732686/193422839-7d17727b-2218-4bbe-ab6b-2de7d12c4cd7.png)

Notice the repetition of “required”, as well as “Press any key to continue”.

In this sentence, it should read “its” rather than “it's”.

**Comment by martinet101** [comment]
Whoops...

**Comment by RavenMacDaddy** [comment]
A suggested version of the text, with the addition of describing ESC as the key to cancel (obviously needs the added functionality):

"This script will install Scoop and the dependencies required by WingetUI.

Press ESC to cancel, or any other key to continue."

**Comment by martinet101** [comment]
Yes, might as well

**Comment by martinet101** [comment]
This issue has been fixed, but I forgot to close it
![image](https://user-images.githubusercontent.com/53119851/194911884-5df05106-8536-4546-99b2-3199078f4365.png)

**Comment by ppvnf** [comment]
> A suggested version of the text, with the addition of describing ESC as the key to cancel (obviously needs the added functionality):

I've fixed a typo left. Also, I don't know how to implement the feature above

**Comment by RavenMacDaddy** [comment]
The correct grammar is still “_its_” rather than 'it's', and the sentence is still using two instances of 'required' – please consider using the suggested version repeated below.

`This script will install Scoop and the dependencies required by WingetUI.` 

If the implementation of using ESC to cancel the script is not possible, well then that's that.

**Comment by ppvnf** [comment]
> The correct grammar in the current version of the sentence is still “_its_” rather than 'it's', and there are still two instances of 'required' – please consider using the suggested version repeated below.
> 
> `This script will install Scoop and the dependencies required by WingetUI.`
> 
> If the implementation of using ESC to cancel the script is not possible, well then that's that.

@RavenMacDaddy, I've fixed that in https://github.com/martinet101/WingetUI/pull/226/commits/24206bafa600244db0b4e4e39133d213f6021d19, except implementing ESC to cancel

**Comment by RavenMacDaddy** [comment]
Haha, was about to say.

By now it's grammatically correct – appreciate your work @ppvnf.
