### ISSUE TITLE
v1.4 – Improvement: Description boxes for options/actions upon hovering

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#179]
![image](https://user-images.githubusercontent.com/67732686/193423089-5f67bc8a-8a18-4a87-94d7-80e1daf8970c.png)

Minimalistic design is nice – as long as the options at the user's disposal are clear on what they entail.

Consider adding description boxes for the actions at the top (and eventually elsewhere if applicable) to make things easier to understand, and therefore more usable.

**Comment by martinet101** [comment]
Done!

**Comment by ppvnf** [comment]
it possible to remove the tooltips when there's already text?

![Captura de tela 2022-10-02 221256](https://user-images.githubusercontent.com/73800734/193485684-672f7877-8b4a-48ea-9544-5ff9afb798d8.png)

**Comment by martinet101** [comment]
The tooltips are there because, if the window gets resized and the text doesn't fit, the toolbar is set to hide the text and show only the icons
