### ISSUE TITLE
Inspiration: Improving the symmetry, viewability and aesthetics of the app

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#18]
![Symmetry and aesthetic design overhaul inspiration](https://user-images.githubusercontent.com/67732686/169764008-98d0cd03-eed9-468e-998a-4fdc1ff6a7eb.png)

Essential changes made in the screenshot:

- [x] Increases the space between the top section and the content below, as well as moving the top buttons further down
- [x] The About section specifically seems to look better adjusted to the left, hence the choice
- [x] Adjusts the button sizes depending on the amount of text, as well as the height of the buttons and text
- [x] Reduces the space between titles and sub headers and the normal text while increasing the spacing between the sections
- [ ] Slightly adjusts the licensing text to the right to make them all align vertically
- [x] Increases the spacing between the buttons at the top, makes things easier to distinguish and read
- [x] Improve tab select widget

More or less all the different elements have been adjusted with the goal of more symmetry and being more aesthetic to look at - as well as easier to view and read.

I think the buttons and text for the sections at the top could do with being enlarged as well.

This is meant as ideas and inspiration for improving the project.

**Comment by martinet101** [comment]
Yes, it looks definitely better. At the moment i'm having exams week at school so I need to study, but i'll try to do this asap (just like the two other issues)

**Comment by RavenMacDaddy** [comment]
It's not your job - you do what you feel like doing, when you feel like it. 

With that said, I appreciate your drive.

**Comment by martinet101** [comment]
This might be difficult, but the final result is worth the time.

You know, it is amazing to work with someone that gives ideas, because there are lots of things I wouldn't have thought of. I really appreciate the effort you are putting here, without waiting for any reward or something. Thank you a lot, mate :)

**Comment by RavenMacDaddy** [comment]
My pleasure, and likewise - I think we complement each other very well.

**Comment by RavenMacDaddy** [comment]
For reference on how the buttons could be lit up:

![image](https://user-images.githubusercontent.com/67732686/170772104-d02618cc-f03c-4ec2-81aa-ec6ff4ca69c3.png)

**Comment by martinet101** [comment]
> The tight buttons at the top visible in the build published in issue #21 gave me an idea, check this screenshot:
> 
> ![Alternative Section buttons](https://user-images.githubusercontent.com/67732686/170729415-3c217f14-5bfa-44b4-9003-21e3b1d24a31.png)
> 
> So instead of spread out buttons, the sections are separated by simple lines, and the corresponding selected/active section ought to be lit up both for clarity and in terms of aesthetic design.
> 
> Notice how the lines that separate them have been placed to be somewhat in the middle between each one - although it's all just a fast mockup for inspiration.
> 
> Personally I like this design more and more as I look at it.

What about something like this?
![image](https://user-images.githubusercontent.com/53119851/170836683-71096ef0-32c5-4491-81e4-16055b820d4e.png)

**Comment by martinet101** [comment]
Final Result:

![image](https://user-images.githubusercontent.com/53119851/170837531-64091912-03f8-4ec4-8a2d-b55243a5ee58.png)

**Comment by RavenMacDaddy** [comment]
I personally find that buttons should be proportionate to the amount of text and its size.

I get what you're going for making everything spread across in the middle, it just looks a little weird when the text is so small and short while the buttons are very wide.

The top is a lot better, but to clarify what I envisioned myself was more in line with what was illustrated; 

The sections are simply separated by lines, and the active one is lit up, akin to the other screenshot from the Windows 11 context menu - it's the same rounded shape just inside the outer rounded edges, in a lighter shade; highlighting to indicate what's selected (for example with the mouse hovering).

Finally I notice the 'Unlicense' text being slightly to the right making it not vertically in line with the rest.

With that said, this is a definite improvement, and you've done a great job.
