### ISSUE TITLE
Application theme visual bug 

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#181]
I think there's a small visual bug with this feature. I'm using Windows 10 with system dark mode enabled. The default application theme should be "follow system color scheme". WingetUI already behaves like that, but the app incorrectly shows by default:

![Captura de tela 2022-10-02 091010](https://user-images.githubusercontent.com/73800734/193453254-6186636a-82e9-44dc-9725-41bfaa0a296b.png)

Only if I select/click "Light" WingetUI really changes to light theme, so the behavior is correct but for some reason the default option (follow system color scheme) isn't being shown by default.

Related: https://github.com/martinet101/WingetUI/issues/178

**Comment by martinet101** [comment]
Done!
