### ISSUE TITLE
ModuleNotFoundError when running from source: Problem with casing in file name to import modules

### ISSUE THREAD

**Issue by harleylara** [martinet101/WingetUI#182]
Hello,

First of all, congratulations for the release of version 1.4 🥳 

A bit of context, this discussion starts [here](https://github.com/martinet101/WingetUI/commit/0a436e3c60ac7877b77391761554cf62ab1dd2c6#comments).

Why is this a problem? When trying to run `WingetUI` from source in a case-sensitive environment the following error is produced (from the cool log system in 1.4 😎 ):
```
                        OS: Windows
                   Version: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
               APP Version: Unknown
                   Program: WingetUI
           Program section: Main script

-----------------------------------------------------------------------------------------



WingetUI Log:




Traceback (most recent call last):
  File "D:\git\WingetUI\wingetui\__init__.py", line 9, in <module>
    import wingetHelpers, scoopHelpers
  File "D:\git\WingetUI\wingetui\wingetHelpers.py", line 3, in <module>
    from tools import *

ModuleNotFoundError: No module named 'tools'<class 'ModuleNotFoundError'>: No module named 'tools'
```

As you can see the `tools` module is not found, even when the file exists with the name [`Tools.py`](https://github.com/martinet101/WingetUI/blob/main/wingetui/Tools.py). Why not just change the case in import to `from Tools import *` to match the module case? this solution [raises some problems](https://github.com/martinet101/WingetUI/commit/0a436e3c60ac7877b77391761554cf62ab1dd2c6#commitcomment-85392801) in other environments.

Some of the assumptions that could generate the problem was to clone the repo using WSL, however I tried to clone the repo with "Git for Windows" and the problem persisted. So after a little research I came across this, [PEP 235 - Import on Case-Insensitive Platforms](https://peps.python.org/pep-0235/) (as we know Windows has a case-insensitive file system), the interesting part is in [Proposed Semantics](https://peps.python.org/pep-0235/#proposed-semantics) where: 
> A. If the [`PYTHONCASEOK`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONCASEOK) environment variable exists, same as before: silently accept the first case-insensitive match of any kind; raise ImportError if none found.
 > B. Else search sys.path for the first case-sensitive match; raise ImportError if none found.

---
✅ SOLUTION ✅: Create the environment variable [`PYTHONCASEOK`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONCASEOK), no matter what value you assign to it, if it exists python disables the case sensitive when importing modules.
To set environment variables in `cmd`:
```
set PYTHONCASEOK=true
```

---
⚠️ CAUTIONS⚠️: If you create the environment variable in your global python environment this will affect all your other python projects running with the global environment. 

---
ℹ️ RECOMENDATIONS ℹ️: Create a python `virtual Environment`, or if you have anaconda you can create a `conda environment`, both alternatives prevent affecting the global python environment.

---
❓  QUESTION ❓: @martinet101 Do you think it is better to keep the project as case-insensitive for importing modules? or do you consider the idea of forcing casing for importing modules (python's default behavior)?

Without further ado, best regards ✌️ . 

_Note: This Issue was opened to record this behavior and possible solutions._

**Comment by martinet101** [comment]
Honestly, knowing that windows is not case-sensitive and that this project won't be extended to linux/macOS, i think that the best idea is to set this project as non-case sensitive
