### ISSUE TITLE
v1.4 dotnet sdk 6.0 update loop

### ISSUE THREAD

**Issue by Cromaxxx** [martinet101/WingetUI#185]
Still get update loop for dotnet 6.0 update.

![Screenshot 2022-10-03 021717](https://user-images.githubusercontent.com/10215299/193482847-23b75b36-0e13-4f86-bafd-d518770e4757.png)

**Comment by ppvnf** [comment]
> Still get update loop for dotnet 6.0 update.

Could you please share the result of `winget upgrade` command on PowerShell or cmd?

**Comment by Cromaxxx** [comment]
thats strange

![winget](https://user-images.githubusercontent.com/10215299/193492425-f7e08b1f-4c6b-46c2-8b86-afd27dd9f7a7.png)

**Comment by ppvnf** [comment]
What happens if you try to update it with the command `winget upgrade Microsoft.DotNet.SDK.6`?

**Comment by Cromaxxx** [comment]
![winget](https://user-images.githubusercontent.com/10215299/193497887-86c2e6fc-d39e-4bf6-863d-92a759242590.png)

**Comment by ppvnf** [comment]
`winget upgrade "Microsoft.DotNet.SDK.6"` also doesn't work, right? This seems like a problem with the Winget package itself, but wait @martinet101 for confirmation. If you aren't able to update this package through cmd WingetUI also won't be able to. If this is the case you may try to get help at https://github.com/microsoft/winget-pkgs.

**Comment by Cromaxxx** [comment]
you are right ty
