### ISSUE TITLE
Show package info sometimes doesn't correctly display version of Winget packages

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#187]
This problem happens only in the update and uninstall sections, and only for Winget packages. For example, you can see the installed version of this package and the new version available:

![Captura de tela 2022-10-03 002436](https://user-images.githubusercontent.com/73800734/193496201-4de2a3b1-50cc-4673-bf5c-7b90799968f2.png)

However, if I click show more info, this same information isn't displayed:

![Captura de tela 2022-10-03 002633](https://user-images.githubusercontent.com/73800734/193496362-c977950f-6908-4301-b222-7c65e40cdac1.png)

On the Discovery tab this problem doesn't happen. So, I believe it only does when there's nothing besides "Latest" in the combo box. Also, this only affects Winget apps because scoop ones always have their version under "Latest".

**Comment by martinet101** [comment]
Fixed!
