### ISSUE TITLE
missing App Icons in Windows Search after first WingetUI installation

### ISSUE THREAD

**Issue by BobaFett012345** [martinet101/WingetUI#188]
I found out that the App icons in windows search are replaced with "dummy-icons" (e.g. searching for "Word") after first WingetUI installation.
Tried it on 4 machines, every time the same thing.
App icons in Windows App list are still the same as before installation

**Comment by martinet101** [comment]
This is because the windows shel often does those weird things. If you install software manually this _bug_ also occurs

**Comment by ppvnf** [comment]
restarting Windows fixes this issue for me
