### ISSUE TITLE
Trouble with screen lay out

### ISSUE THREAD

**Issue by aadvanraamt** [martinet101/WingetUI#19]
![WingetUI_2fwYYYtOxx](https://user-images.githubusercontent.com/22995621/169831235-8c6d20ab-58be-45ad-954d-1cb5c15dac24.png)

**Comment by RavenMacDaddy** [comment]
Please provide context so the developer knows why this happens; how to reproduce it.

**Comment by aadvanraamt** [comment]
Direct after staring the program

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by aadvanraamt** [comment]
Hello the problem is gone when i rezize the box then it works fine
________________________________
Van: Martí Climent ***@***.***>
Verzonden: woensdag 25 mei 2022 13:28
Aan: martinet101/WingetUI ***@***.***>
CC: aadvanraamt ***@***.***>; Author ***@***.***>
Onderwerp: Re: [martinet101/WingetUI] Trouble with screen lay out (Issue #19)


Closed #19<https://github.com/martinet101/WingetUI/issues/19> as completed.
