### ISSUE TITLE
Version 1.4.1 - Missing letter

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#192]
![Captura de tela 2022-10-03 195438](https://user-images.githubusercontent.com/73800734/193701579-fc0d00a5-0a4e-4b5e-91f0-c764d0806746.png)

The new version introduced this bug.

**Comment by martinet101** [comment]
I reckon this is because the font used in WingetUI is not being detected in tour system. Could you try installing the fonts `Segoe UI Variable Display` and `Segoe UI Variable Text`?

**Comment by ppvnf** [comment]
Thanks! Installing this font fixed the issue. Shouldn't this be done by default? 

[segoe-ui-variable-cufonfonts.zip](https://github.com/martinet101/WingetUI/files/9708657/segoe-ui-variable-cufonfonts.zip)

**Comment by martinet101** [comment]
I thought w10 had this font instal·les by default... Gonna force the installer do that...

**Comment by ppvnf** [comment]
I believe this has been fixed https://github.com/martinet101/WingetUI/commit/85bc8f965e0edf1c0cabf6b6d241a2119d3c4911

**Comment by martinet101** [comment]
Still need to test but in theory yes

**Comment by ppvnf** [comment]
> Still need to test but in theory yes

I could test it on another Windows 10 PC without the font if you send me a installer with the fix

**Comment by ppvnf** [comment]
> I need to test oter features (like letting the user enable or disable scoop from the installer) so i'll test it all at once.
> 
> Thank you anyway ;)

I'm not sure how scoop installation works, but the font would be installed for Windows 10 users through scoop as well, right?

**Comment by martinet101** [comment]
> but the font would be installed for Windows 10 users through scoop as well, right

no, the font will be installed from a separate .ttf file
