### ISSUE TITLE
The version of non-latin characters apps isn't displayed in the search menu

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#194]
Some Winget packages contain non-latin characters, like Chinese:

![Captura de tela 2022-10-03 210513](https://user-images.githubusercontent.com/73800734/193707054-c662d316-ac1b-4bf8-926a-81dcc7865e9a.png)

The version of those packages is not being shown, unless you click "show info":

![Captura de tela 2022-10-03 211510](https://user-images.githubusercontent.com/73800734/193707942-723a5dda-9aa1-43ad-b5a1-5a517d286834.png)

Related:
https://github.com/martinet101/WingetUI/issues/193
https://github.com/martinet101/WingetUI/issues/190

**Comment by martinet101** [comment]
> Also, would it be possible to have an option in the settings to hide packages that contain non-latin characters?

But non-latin characters would include packages with accent (à, á, è, é, etc.)?

**Comment by ppvnf** [comment]
> But non-latin characters would include packages with accent (à, á, è, é, etc.)?

I've searched packages with accent and only "é" seems affected by this bug.
I am rethinking if that option is a good idea. French words are somewhat common in English, so packages with accent shouldn't be blacklisted. I also remembered that µTorrent uses the greek letter "µ", so this option seems too complex to implement and may cause more harm than good.

![Captura de tela 2022-10-04 075142](https://user-images.githubusercontent.com/73800734/193801229-c99cba15-656d-4706-861d-0f9dfa741370.png)
![Captura de tela 2022-10-04 074319](https://user-images.githubusercontent.com/73800734/193801233-f6ebf7b1-fedb-4ce6-a5f3-7799de97b3be.png)

**Comment by ppvnf** [comment]
> If you try installing one of them, could you please tell if they show correctly in the unstall section? Because the functions that read discover and that read updates/uninstalled are a bit different

Same result:

![Captura de tela 2022-10-04 094745](https://user-images.githubusercontent.com/73800734/193823147-7d5c7527-f230-42f1-ac96-395fe7dadd23.png)

**Comment by ppvnf** [comment]
I've created a todo list for this issue. I'm unsure if you want to implement this option:

- [ ] If possible, have an option to hide packages that contain non-latin characters

If you do not, you may remove it

**Comment by martinet101** [comment]
> * possible, have an option to hide packages that contain non-latin characters

Honestly, it is not that i don't want to implement it (because the implementation would be very simple, but rather i feel this option would be wrong.). I'd prefer to fix this issue, (because at the end of the day, is not the fault of anyone that non-latin characters are represented differently) rather that just _hiding_ it.

**Comment by martinet101** [comment]
Fixed!
