### ISSUE TITLE
Bug: Unable to uninstall Scoop apps (WingetUI uses Winget parameters)

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#195]
WingetUI version at the time of writing: **1.4.1**

![image](https://user-images.githubusercontent.com/67732686/193777011-6190b1b4-4134-4a74-8f85-823d7ccaa83f.png)

[WingetUI log.txt](https://github.com/martinet101/WingetUI/files/9704283/WingetUI.log.txt)

It's attempting to uninstall the Scoop app with Winget parameters;

```
Uninstalling cmake
🟢 Have permission to install, starting installation threads...
🟢 Waiting for install permission... title=cmake, id=cmake, installId=1664873352.4688141
🟢 winget installer assistant thread started for process <Popen: returncode: None args: ['F:\\Users\\amand\\AppData\\Local\\Programs\...>
['F:\\Users\\amand\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'uninstall', '-e', '--name', 'cmake', '--source', 'winget', '--accept-source-agreements', '--silent']
```

**Comment by martinet101** [comment]
Yeah, it looks like it is idenfiffying it as winget...

**Comment by ppvnf** [comment]
I'm also unable to install scoop packages:
![Captura de tela 2022-10-04 102536](https://user-images.githubusercontent.com/73800734/193831400-30eeef62-eda4-4f43-a731-4d839d8ca3bd.png)
Updates are working fine tho.

**Comment by martinet101** [comment]
Yep, i'll fix this as soon as i can

**Comment by martinet101** [comment]
Done!

**Comment by martinet101** [comment]
Fixed!
