### ISSUE TITLE
Bug: Text that's cut short in the main window is also cut short under Show info

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#196]
Partially related to #23.

![image](https://user-images.githubusercontent.com/67732686/193848515-5a298f02-627b-4513-8d88-3263e0629241.png)

![image](https://user-images.githubusercontent.com/67732686/193848568-2f8c8589-7694-421b-a490-2cdc5c4de120.png)

**Comment by ppvnf** [comment]
i didn't notice Package ID was also cut

Related to: 
https://github.com/martinet101/WingetUI/issues/193

**Comment by martinet101** [comment]
This bug is related to winget. if you run `winget show`, you'll see this packages are also cut out, so this is more a winget issue and not WingetUI

**Comment by martinet101** [comment]
Ayway, i'll try resizing th virtual console where winget calls get emulated

**Comment by ppvnf** [comment]
> This bug is related to winget. if you run `winget show`, you'll see this packages are also cut out, so this is more a winget issue and not WingetUI

That's true, but I think WingetUI is cutting out more than Winget-cli already does:
![Captura de tela 2022-10-04 144936](https://user-images.githubusercontent.com/73800734/193890594-c5e635d1-a0a7-4a98-ba3b-5193ff0dee03.png)

**Comment by martinet101** [comment]
> That's true, but I think WingetUI is cutting out more than Winget-cli already does:

because that's how subprocess.Popen handles virtual sizes of virtual consoles

**Comment by ppvnf** [comment]
> > That's true, but I think WingetUI is cutting out more than Winget-cli already does:
> 
> because that's how subprocess.Popen handles virtual sizes of virtual consoles

I get it. How about adding ... after the cut out in the info menu (if the cut out is indeed inevitable)?

**Comment by martinet101** [comment]
Well, running winget search does not always show the full app names.

I tried forcing big screen modes (and while they were successfully applied), winget wouldn't use the whole width of the virtual console.

However, i've added back the three dots:
![image](https://user-images.githubusercontent.com/53119851/194095582-bbb51536-c2f1-401c-a361-288b3c0254a6.png)
