### ISSUE TITLE
Bug: restore from systray not working reliably

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#197]
On Windows 10 minimizing to systray works fine when you click the WingetUI systray icon or have minimize when you close enabled, however clicking the icon doesn't always restore WingetUI window. Clicking "Show WingetUI" on the icon context menu also fails sometimes. I am not sure about the conditions necessary for this to happen, but trying to restore WingetUI shortly after minimizing to the systray seems to increase the chances of it failing

**Comment by martinet101** [comment]
Done!
