### ISSUE TITLE
Bug: Unable to uninstall Chrome (except as admin) (winget version)

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#198]
Uninstalling as admin works. It's also possible to uninstall it using unelevated Powershell (this issue also applies to Chrome dev, beta, etc.):

![Captura de tela 2022-10-04 101953](https://user-images.githubusercontent.com/73800734/193879868-1fed2dec-525c-44d4-a24c-0c996db94cad.png)
![Captura de tela 2022-10-04 135222](https://user-images.githubusercontent.com/73800734/193879872-a2213073-edcf-408f-8372-e2a00a51b585.png)

I believe the scoop version isn't affected by this.

**Comment by ppvnf** [comment]
I did a few tests. Updating is working and interactive uninstall is also working, however WingetUI is detecting the package (at least for Chrome dev as not being installed by Winget, which is false as you can see it the shell):

![Captura de tela 2022-10-04 154406](https://user-images.githubusercontent.com/73800734/193900595-dd8d5a92-6e8f-4310-bf5e-580728bff490.png)

**Comment by martinet101** [comment]
> as not being installed by Winget, which is false as you can see it the shell

However, this won't change the uninstall command (local pc and winget are handled in the same way)

**Comment by ppvnf** [comment]
> > as not being installed by Winget, which is false as you can see it the shell
> 
> However, this won't change the uninstall command (local pc and winget are handled in the same way)

I see... I thought not being able to uninstall was because of the package not being correctly identified by Winget. I just remembered that I had the same problem with Microsoft Visual C++ Redistributable packages a few days ago. I believe the cause was the manifests being changed. I am gonna open a new one not bloat this one, but feel free to unify them if you wish.

**Comment by martinet101** [comment]
What would happen if you ran `winget uninstall --id Google.Chrome -e --silent`?

**Comment by ppvnf** [comment]
> What would happen if you ran `winget uninstall --id Google.Chrome -e --silent`?

I am also getting error 1603 on Winget-cli. So, this isn't a problem with WingetUI after all?

**Comment by martinet101** [comment]
I don't think. 

What i suspect is happening is that the `--silent` flag in winget prevents msi installers (chrome and some older vcredist) from showing the UAC prompt, failing with oc 1603. Running as admin already gratns needed provoleges so it works ok. 

I reckon this is an issue with winget-cli, though

**Comment by martinet101** [comment]
I can try to create some kind of fallback, that when uninstalls fail they'll be ran without the `--silent` flag, what do you think?

**Comment by ppvnf** [comment]
> I can try to create some kind of fallback, that when uninstalls fail they'll be ran without the `--silent` flag, what do you think?

I don't see any downside for doing that

**Comment by ppvnf** [comment]
I've just tested `winget uninstall --id Google.Chrome -e --silent` today and somehow it worked fine on Winget-CLI, but WingetUI still fails with error 1603

**Comment by martinet101** [comment]
can you please test that same command but with the winget versio  bundled in WingetUI? `%localappdata%\programs\WingetUI\winget-cli\winget.exe`

**Comment by ppvnf** [comment]
> can you please test that same command but with the winget versio bundled in WingetUI? `%localappdata%\programs\WingetUI\winget-cli\winget.exe`

Never mind, I think I accidentally opened Powershell as admin before. I've tried again and `winget uninstall --id Google.Chrome -e --silent` fails on both bundled and system PowerShell. I've opened an issue about this there: https://github.com/microsoft/winget-pkgs/issues/82692
I believe [this](https://github.com/martinet101/WingetUI/issues/198#issuecomment-1269833035) is a good idea. It would be even better if Microsoft implemented it on Winget-cli though

**Comment by ppvnf** [comment]
I got an answer [here](https://github.com/microsoft/winget-pkgs/issues/82692#issuecomment-1279388329):

> One of our key design criteria has been supporting "unattended" installations to support things like `winget import packages.json`. We might consider a fallback approach to "non-silent" installs once we have some user driven settings or arguments to allow users to select that behavior.

**Comment by martinet101** [comment]
Well, they are not going to fix it, we'll need to do it ourselves.

**Comment by martinet101** [comment]
Fixed!

**Comment by martinet101** [comment]
Now when the error occurs it immediately re-runs the uninstall command with administrator rights
