### ISSUE TITLE
UI in "frozen" state after `scoop bucket add extras`

### ISSUE THREAD

**Issue by octoshrimpy** [martinet101/WinGetUI#2]
after running `scoop bucket add extras`, whenever wingetUI store is open it remains in a semi-frozen state, like so:

![Screenshot (2)](https://user-images.githubusercontent.com/7097172/135133358-3adc2424-5e81-4183-b335-445a776a7651.png)

I can see apps that only exist in the extras bucket (for example `lightcord`) and even click into for package details, however the main app itself never finishes loading or display the correct total item count.

**Comment by martinet101** [comment]
Hi @octoshrimpy, thanks ffor letting me know that 😀, i'll take a look a this and try to fix it.

**Comment by martinet101** [comment]
I have fixed that, i'll comment when the release comes out

**Comment by martinet101** [comment]
Release 0.4 is now available with the fix
