### ISSUE TITLE
Feature: hide scrollbar when unnecessary

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#200]
MS Store only shows the scrollbar when it's possible to scroll, WingetUI shows it even if there are fews/no search results, which is unnecessary:

![Captura de tela 2022-10-04 095819](https://user-images.githubusercontent.com/73800734/193883864-f7d514dc-2df9-4028-8d21-3c4b817ad7cf.png)
![Captura de tela 2022-10-04 095755](https://user-images.githubusercontent.com/73800734/193883608-f8d52871-4aba-4e25-8f2a-ae2ee5944c38.png)
![Captura de tela 2022-10-04 133429](https://user-images.githubusercontent.com/73800734/193883650-de8d2443-46ba-4fd9-8ee4-efa74ae02e76.png)

**Comment by martinet101** [comment]
Done!
