### ISSUE TITLE
Feature suggestion: add message when search results = 0 (except in update section when available updates is also = 0)

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#205]
I like the message in the update section. How about something similar for when there are no search results available? Maybe something like: no results for "typed word"

![Captura de tela 2022-10-05 184849](https://user-images.githubusercontent.com/73800734/194170535-22518ad8-669d-4077-b4eb-8586e036be41.png)
![Captura de tela 2022-10-05 184910](https://user-images.githubusercontent.com/73800734/194170531-5c65c993-2a3d-4d6e-8db2-fe889af42c64.png)
![Captura de tela 2022-10-05 184859](https://user-images.githubusercontent.com/73800734/194170538-4c2fd223-90d4-40da-9a09-506d97a2e939.png)

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/194352550-e3073374-2d80-4738-83bf-4a08d874a233.png)
