### ISSUE TITLE
Bug – Scoop: Apps containing PowerShell modules get stuck when updating (when supposedly replacing the module)

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#207]
![image](https://user-images.githubusercontent.com/67732686/194316632-8e87c099-2a42-426c-9459-4b93c3dd6e68.png)

For reference, this is not a module that's part of Scoop; any apps containing PS modules, like `scoop-completion`, gets the corresponding data installed into the subdir _modules_ – and apparently, while trying to replace the old version, WingetUI gets stuck in the process.

```
🔵 Current program set to 1665060355.9610548
🔵 Sending cancel signal...
🔵 Sending cancel signal...
🟢 Have permission to install, starting installation threads...
🟢 Waiting for install permission... title=scoop-completion, id=scoop-completion, installId=1665060452.285913
🟢 scoop installer assistant thread started for process <Popen: returncode: None args: 'powershell -Command scoop update scoop-compl...>
🔵 Current program set to 1665060452.285913
🔵 Sending cancel signal...
🔵 Sending cancel signal...
```

Hmm…no clue.

[Log.txt](https://github.com/martinet101/WingetUI/files/9724965/Log.txt)

Even weirder, I don't see the output that WingetUI is getting stuck on when successfully installing the update through the CLI;

![image](https://user-images.githubusercontent.com/67732686/194318160-e3552fca-845c-4d77-843b-f1418901a4ab.png)

**Comment by martinet101** [comment]
what happens if you run `powershell -Command scoop update scoop-completion` on a command prompt window?

**Comment by ppvnf** [comment]
I don't know about Scoop, but Winget isn't native to PowerShell yet. See https://github.com/microsoft/winget-cli/issues/221

**Comment by martinet101** [comment]
> If **CMD** is being used in WingetUI, I suppose it ought to be updated to use **PowerShell** instead – but if I'm missing the point of its use, by all means educate me.

CMD is _not directly_ used, but it is used to call a powershell instance that takes care of the scoop command. (it is python's default subprocess.Popen behaviour)

As far as I understand, the issue here is that scoop is prompting for an answer, but then (since you can't interact with the console, it gets stuck.)

I suppose this is a scoop bug, because it should take care of ran command to be unattended (as you can see, it says that the recurse parameter for whatever the function was not specified)

**Comment by martinet101** [comment]
Opened an issue on scoop, see here: https://github.com/ScoopInstaller/Scoop/issues/5173
