### ISSUE TITLE
[Bug] Dragging the description window for any package slows down the dragging itself (Win10)

### ISSUE THREAD

**Issue by Satanarious** [martinet101/WingetUI#208]
Dragging the description window for any package on windows 10 slows down the dragging, I guess it might be because Windows 10 doesn't completely support Windows 11 transparency effect. I donno, just guessing here. In the gif below I'm holding and dragging, while the window takes its time to complete the dragging.

![My Video](https://user-images.githubusercontent.com/42642682/194434817-31ddc863-76bc-4a8a-b143-3b97cc461ef2.gif)

**Comment by ppvnf** [comment]
I've tested it on Windows 10. This problem indeed happens when transparency is activated on Windows settings

**Comment by martinet101** [comment]
Yes, this is a bug with the library that applies that effect. Gotta check for a fix tor thus

**Comment by martinet101** [comment]
This issue has already been fixed with the general improvements in the information window
