### ISSUE TITLE
Bug: Weird characters for certain apps that prevents interaction (and telling what's what)

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#21]
![image](https://user-images.githubusercontent.com/67732686/170043491-50671f54-45f4-4513-8673-f214d6242451.png)

![image](https://user-images.githubusercontent.com/67732686/170043571-e8a102e7-2405-4ef7-b51c-df278f2fa35a.png)

[32;1mname or something, unknown app in the Installed list, as well as links and everything else in the first screenshot.

**Comment by martinet101** [comment]
Well, that's weird.
Faast Questions:
 - Does it happen with Winget packes, with scoop packages or with both?
 - Does your user directory contain any special characters?

**Comment by RavenMacDaddy** [comment]
1. Only Scoop apps are affected.
2. Nope, just letters, and the dir for Scoop is F:\Backup\Scoop - aka custom dir.

**Comment by martinet101** [comment]
so what if you run in a cmd window `scoop info caprine`, does it show normal or does it fail?

**Comment by RavenMacDaddy** [comment]
![image](https://user-images.githubusercontent.com/67732686/170462039-a60135f7-d924-4455-ae54-e23aa8f569f3.png)

Completely normal.

**Comment by RavenMacDaddy** [comment]
Nono, this is the current default color that the Scoop app uses.

**Comment by martinet101** [comment]
huh, weird... Anyway, l'll try to fix it

**Comment by RavenMacDaddy** [comment]
And I appreciate your commitment and am very impressed.

**Comment by martinet101** [comment]
Hi, can you please sry the latest head?

**Comment by RavenMacDaddy** [comment]
Oh Martí, I'd be glad to, but I've no programming knowledge so I dunno how to compile and test it.

**Comment by martinet101** [comment]
Oh, no worries :)

**Comment by martinet101** [comment]
It should have the character issues fixed

**Comment by RavenMacDaddy** [comment]
For some reason I can't even see any Scoop packages;

![image](https://user-images.githubusercontent.com/67732686/170725276-aeb51934-6f41-476d-ba1d-513327c38b3e.png)

![image](https://user-images.githubusercontent.com/67732686/170725310-da21ce18-c855-4678-b071-22e54a9ffdd9.png)

**Comment by martinet101** [comment]
> Can you try this .exe?
> 
> https://drive.google.com/file/d/1--59dlIGpZoRyW3FXNeLOTFnZXaHtfso/view?usp=sharing

Can you try this again please? (I hae updated the file.)

You will find a nwe tab called "Debugging log"

Please open it, click to see the log and send me all the text shown there.

I'm sorry i've been _asleep_, but i had to finish final exams :')

**Comment by martinet101** [comment]
Hi, can you please run this command: `scoop -v`

Also, can you try running this: `Set-ExecutionPolicy Unrestricted`. Because it seems like PowerShell is blocking scoop

> b'At line:1 char:1' At line:1 char:1
> b'+ scoop search' + scoop search
> b'+ ~~~~~' + ~~~~~
> b'+ CategoryInfo          : SecurityError: (:) [], PSSecurityException' + CategoryInfo          : SecurityError: (:) [], PSSecurityException
> b'+ FullyQualifiedErrorId : UnauthorizedAccess' + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by RavenMacDaddy** [comment]
![image](https://user-images.githubusercontent.com/67732686/175052450-3c6f049a-af89-49ec-9579-2fed0841ad26.png)

Setting Unrestricted for the current user didn't help, and also goes against Scoop's own homepage;

![image](https://user-images.githubusercontent.com/67732686/175053159-ff59ec4c-825d-4a85-970b-e2b9ba9c0635.png)

I ran the command for CU and then started WingetUI, viewed a Scoop app with the same characters coming up.

**Comment by martinet101** [comment]
And now that scoop apps are showing, can you please try thie file?

> > https://drive.google.com/file/d/1--59dlIGpZoRyW3FXNeLOTFnZXaHtfso/view?usp=sharing

**Comment by RavenMacDaddy** [comment]
Actually it seems to be fixed in v1.1, great work.
