### ISSUE TITLE
Improve icons

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#210]
I guess this is very subjective and I'm no expert on icons, so take my opinion with a grain of salt:

- [x] I think the meaning of the ![](https://user-images.githubusercontent.com/73800734/194564195-41802398-2026-4d37-801e-2b3ba78019fd.png) icon isn't very intuitive.  [Preferred suggestion](https://github.com/martinet101/WingetUI/issues/210#issuecomment-1277333290)

- [x] Better Uninstall icons
I've added a task list just for organization, but feel free to modify it

**Comment by martinet101** [comment]
>  And why not have the icons colored like in earlier versions?

I Honestly think it looks worse, or at least with the new w11-like style.



> * I think the meaning of the lock icon isn't very intuitive.

Which one do you mean? the ID one? It was supposed to be a tag, but couldn't find any better one

**Comment by ppvnf** [comment]
> I Honestly think it looks worse, or at least with the new w11-like style.
> 

I suppose it wouldn't be easy/worth it to have a toggle to enable/disable icon color?

> Which one do you mean? the ID one? It was supposed to be a tag, but couldn't find any better one

This one:
![Captura de tela 2022-10-07 102035](https://user-images.githubusercontent.com/73800734/194564195-41802398-2026-4d37-801e-2b3ba78019fd.png)
packages are boxes IMO

**Comment by martinet101** [comment]
couldn't find anything better. 

The source of the icon is icons8.com, and their icon stock is limited

**Comment by ppvnf** [comment]
> couldn't find anything better.
> 
> The source of the icon is icons8.com, and their icon stock is limited
> 
> And the icon is supposed to represent a software package

Suggestions: 

https://img.icons8.com/pastel-glyph/2x/box--v1.png
https://img.icons8.com/pastel-glyph/2x/box--v2.png
https://img.icons8.com/pastel-glyph/2x/box--v3.png
https://img.icons8.com/pastel-glyph/2x/box--v4.png

**Comment by ppvnf** [comment]
I've updated the task list taking in consideration our recent discussion

**Comment by ppvnf** [comment]
> * Also, what about having a different icon/icon color to differentiate package sources from Scoop and Winget? - I've no idea which icons to use though

I couldn't think anything better:
Scoop: https://img.icons8.com/ios/452/ice-cream-bowl.png
Winget: https://img.icons8.com/external-kmg-design-detailed-outline-kmg-design/344/external-open-box-shipping-delivery-kmg-design-detailed-outline-kmg-design.png

Also, I've added more suggestions [here](https://github.com/martinet101/WingetUI/issues/210#issuecomment-1271652459)

**Comment by martinet101** [comment]
> https://img.icons8.com/external-kiranshastry-lineal-kiranshastry/452/external-package-logistic-delivery-kiranshastry-lineal-kiranshastry-20.png What do you thin about this edit, without the tag? It fits the rounded-corner style and the icon is not drawn in perspective, following the other icons in the UI
![image](https://user-images.githubusercontent.com/53119851/195546426-b3f00f6d-5f74-40c5-9a06-08a8ace86dbe.png)

**Comment by ppvnf** [comment]
> > https://img.icons8.com/external-kiranshastry-lineal-kiranshastry/452/external-package-logistic-delivery-kiranshastry-lineal-kiranshastry-20.png What do you thin about this edit, without the tag? It fits the rounded-corner style and the icon is not drawn in perspective, following the other icons in the UI

I like it, but I think the image below is even better (you can also remove the tag from it):

https://img.icons8.com/external-kiranshastry-lineal-kiranshastry/452/external-package-logistic-delivery-kiranshastry-lineal-kiranshastry-4.png

**Comment by martinet101** [comment]
> > > https://img.icons8.com/external-kiranshastry-lineal-kiranshastry/452/external-package-logistic-delivery-kiranshastry-lineal-kiranshastry-20.png What do you thin about this edit, without the tag? It fits the rounded-corner style and the icon is not drawn in perspective, following the other icons in the UI
> 
> I like it, but I think the image below is even better (you can also remove the tag from it):
> 
> https://img.icons8.com/external-kiranshastry-lineal-kiranshastry/452/external-package-logistic-delivery-kiranshastry-lineal-kiranshastry-4.png

This one definitely looks the best. Thanks!

**Comment by martinet101** [comment]
Hi @ppvnf, the icon you sent appears to be too thin. However, I found this one that resembles the one you sent and has the adecuate width.

What do you think?

![icons8_cardboard_box_96px](https://user-images.githubusercontent.com/53119851/195670128-4105e03c-b47e-44da-9014-7b80afba84fa.png)

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/195670697-e665de2d-b47c-47de-a155-ef17b8f04917.png)
It looks infinitely better

**Comment by ppvnf** [comment]
It looks awesome!

**Comment by ppvnf** [comment]
> * Would it be easy/worth it to have a toggle to enable/disable icon color?
> * Also, what about having a different icon/icon color to differentiate package sources from Scoop and Winget? - I've no idea which icons to use though

I think you might close this issue. The suggestions above are kinda useless/difficult to implement. I've tried manually changing the icons to colored versions and while I found them a little bit prettier, it was also more distracting. About the icons for Scoop/Winget source I found [here](https://github.com/martinet101/WingetUI/issues/210#issuecomment-1276837660), they don't remind me much Scoop/Winget

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/195673529-30f239de-d3a7-442d-8e1e-8ee1928f0652.png)

**Comment by martinet101** [comment]
Hi @ppvnf, thinking it better, i have set specific icons for winget and scoop packages. 

And honestly, it wasn't a bad idea at all:
![image](https://user-images.githubusercontent.com/53119851/204344396-7092ebf5-2b66-4e9d-9f48-d46c4a314149.png)

**Comment by martinet101** [comment]
Btw, i'm working on a redesigned app icon, was you who suggested that?
![image](https://user-images.githubusercontent.com/53119851/204344676-cb010a64-4257-46da-97af-846aac4b0b77.png)

**Comment by ppvnf** [comment]
> Hi @ppvnf, thinking it better, i have set specific icons for winget and scoop packages.

Wow, that looks pretty cool!

> Btw, i'm working on a redesigned app icon, was you who suggested that?

I think so. I like your idea of simplifying the design of the current icon
