### ISSUE TITLE
Banner is shown even after wingetui is updated.

### ISSUE THREAD

**Issue by rp1231** [martinet101/WingetUI#211]
![WingetUI_9eZRD8pfLU](https://user-images.githubusercontent.com/47380919/194473099-c76c523e-4882-420a-aa24-5650561785df.png)

The banner to update is shown even when winget is the latest version.

**Comment by martinet101** [comment]
Yes, this is "web-based" content, and I haven't updated it yet.

Note that lots of users haven't updated already to 4.x versions

**Comment by martinet101** [comment]
I have updated it now
