### ISSUE TITLE
Installed version column should expand to show version number when there is space on the sides.

### ISSUE THREAD

**Issue by rp1231** [martinet101/WingetUI#212]
![WingetUI_6qAqsf0DTc](https://user-images.githubusercontent.com/47380919/194473439-b49ede84-63db-42be-97fd-c5dfae65fea2.png)
Right now the Installed version column clips the version number when  it is too big for the column.
Ideally the column should be resizable and should automatically resize if the number extends outside the column.

**Comment by martinet101** [comment]
I agree

**Comment by ppvnf** [comment]
Is the fix to this problem similar to https://github.com/martinet101/WingetUI/commit/a1dd458131af34c6f042a8886bf49e75adb90748?

**Comment by martinet101** [comment]
No, this one was on the updates section, and not to the uninstall one

**Comment by martinet101** [comment]
I have been trying to use autostretch, but honestly it does not work. This issue only happens on long versions, and you can either hover on them to see the tooltip or either open the app to get more info.
