### ISSUE TITLE
Bug – v1.4.1: Doesn't update, and every time the app is closed to tray, it notifies that a new version is being installed

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#214]
![image](https://user-images.githubusercontent.com/67732686/194551564-afdc069c-d75d-476e-b824-75b6bc2b3e0d.png)

This also often prevents the app from being restored from the tray icon.

![image](https://user-images.githubusercontent.com/67732686/194551678-acc9ee53-cfaa-472b-96e2-826804d9c47e.png)

**Comment by RavenMacDaddy** [comment]
Oh, I'm mixing things up – it does _not_ update to the new version (namely 1.4.2 currently) however many times I close or restart the app.

I didn't even receive a notification that an update was available as the app was running in its current session – I only knew about it as I'm following the project here on GitHub.

The first time I attempted to close the app the process got stuck – as well as the tray icon – so I'd to force quit the app through Task Manager.

Only after starting the app a second time it started with the notifications, but still (so far) hasn't updated, whether I close the app to tray – where the screenshot is taken from – or entirely.

**Comment by martinet101** [comment]
Can you please share your log after WingetUI showing the notification?

**Comment by RavenMacDaddy** [comment]
Since the same thing isn't happening with the manually installed 1.4.2 version update, I'm closing this as related to a broken installation for now.

**Comment by martinet101** [comment]
But the updater didn't work as expected, right?

**Comment by RavenMacDaddy** [comment]
Correct, it never updated.

**Comment by martinet101** [comment]
But the issue has been solved by the winget update, right?

**Comment by martinet101** [comment]
Fixed! (in theory)
