### ISSUE TITLE
WingetUI installation: installer + Scoop integrations

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#216]
Currently (v1.4.2 installation):

TODO:
 - [x] Fix scoop not being detected
 - [x] Improve installer order
 - [x] If scoop is detected, do NOT disable it when updating

![image](https://user-images.githubusercontent.com/67732686/194599980-1a753427-3a5a-4342-bb15-b68be3a9826d.png)

Ought to be:

![image](https://user-images.githubusercontent.com/67732686/194600740-82dd0183-dcb6-406c-b2ed-169591b41821.png)

**Comment by RavenMacDaddy** [comment]
Of note is that upon the first startup after installation, WingetUI wasn't detecting Scoop or its apps (similar to #71 but for Scoop) – possible bug related to the new Scoop options _during_ installation?

Upon the second startup it first updated its repositories and the corresponding apps showed up in the list as expected.

**Comment by martinet101** [comment]
Yes, this issue is due WingetUI being launched with the path being loaded before is actually installed, so when restarting, it shows jut fine. I'm working on fixing that

**Comment by ppvnf** [comment]
> [ ] Improve installer order

Fixed (in theory). Also, Scoop is now capitalized 😀 
https://github.com/martinet101/WingetUI/pull/231

**Comment by martinet101** [comment]
> I don't know how to fix that 😢

This would require a env vars reload, dont worry, i'll (hopefully be able to) do that

**Comment by ppvnf** [comment]
@martinet101, I think TODO should be like this:

() Fix scoop not being detected
(X) Improve installer order
() If scoop is detected, do NOT disable it when updating

**Comment by martinet101** [comment]
actually yes

**Comment by martinet101** [comment]
This issue should be now fixed
