### ISSUE TITLE
small text cut off in the about section + align text

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#217]
![Captura de tela 2022-10-07 212533](https://user-images.githubusercontent.com/73800734/194680342-d7ab84c6-a257-497c-980e-1092a1458363.png)
It's very small, but you can't fully see the "g" letter in Winget. Maybe the "p" in Scoop is also affected

- [ ] Fix the cut off shown in the image above
- [ ] Make the text aligned like in the image below

![194680342-d7ab84c6-a257-497c-980e-1092a1458363](https://user-images.githubusercontent.com/73800734/195453778-ea4c97d0-a1e3-4659-8fdb-fc67401d6270.png)

**Comment by martinet101** [comment]
I see

**Comment by ppvnf** [comment]
I've added to the todo:

- Make the text aligned like in the image below

**Comment by martinet101** [comment]
![Uploading image.png…]()
