### ISSUE TITLE
Feature request: Adding install date and Size columns to Installed apps view

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#22]
Is it possible to add the columns Install date and Size to the Installed applications section?

**Comment by martinet101** [comment]
Not really, since winget does not provide this info.

**Comment by RavenMacDaddy** [comment]
Just curious, since to my knowledge this app is meant to be specific to Windows as an OS and the app in this specific view seems to gather as many apps as it can present on the system for the user to uninstall if they so wish, wouldn't it be possible to query for the date and size of these apps in the same manner?

Most of the apps I see in this view I certainly didn't install through Winget - 95% is through Scoop, and the only reason I use other ways to acquire apps is cause Scoop is simply not the optimal solution.

That's to say, Winget doesn't seem to be the primary source of information anyway.

**Comment by martinet101** [comment]
> Just curious, since the app in this specific view seems to gather as many apps as it can that's present on the system for the user to uninstall if they so wish, no matter if Winget is the source or not.

What I meant is that this list of applications is taken from winget. If you write "winget list" in your cmd, you will see all your installed software, but from here and beyond there's no way to get the installation date

**Comment by RavenMacDaddy** [comment]
That makes sense, thanks.

**Comment by adripo** [comment]
I revive this issue given the evolution this project had in the last year.
Could it be possible to implement the installation date and/or size at least for Local PC or Chocolatey packages?

**Comment by marticliment** [comment]
Local pc apps are retrieved from winget, so I don't think this would be able to be done.

Scoop apps neither do, so the column would be half empty.
