### ISSUE TITLE
Bug – Checking for updates: Either manually (by refreshing) or supposedly automatically, doesn't work

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#221]
Version: **1.4.2**

Not sure if this only applies for Scoop, or in regard to Winget as well.

Either manually refreshing, or letting the app automatically (supposedly; see the question in #222) check for updates, based on the set schedule – doesn't at least update the sources of Scoop, which would result in showing released updates.

I noticed it as I was reading my usual software news and therefore knew for a fact that at least one of my apps had an update available.

Restarting the app, it actively updated the sources, resulting in the expected app updates showing up.

**Comment by RavenMacDaddy** [comment]
It's worth noting that I don't recall this issue happening previously when I'd not changed the update check period from the default value of 1 hour – in case it's connected somehow.

Either that or some change that was made between 1.4.1 and 1.4.2 I believe.

**Comment by martinet101** [comment]
I can confirm that the issue was fixed but undocumented a few days ago (i thought i broke it after version 1.4.2), and I can confirm also it is working again
