### ISSUE TITLE
Feature request: Utilizing available window space

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#23]
![image](https://user-images.githubusercontent.com/67732686/170045578-1edb90ca-276f-4c42-a543-f8b6040b91a1.png)

![image](https://user-images.githubusercontent.com/67732686/170046007-b4ce060e-e8ca-4b19-b4da-e7d8c652981f.png)

Whether it be smaller or larger, it would benefit the app to have some sort of responsive design to adjust itself depending on the window size.

As per the screenshot above, having the columns get wider would give them more room (e.g. for longer texts) as well as filling up the void that gets left in the window once maximized.

In the reverse scenario, content like columns or text gets cut off/lost completely, although one solution to this is to have a limit for how small the app window can be.

**Comment by martinet101** [comment]
Done!

**Comment by RavenMacDaddy** [comment]
![image](https://user-images.githubusercontent.com/67732686/193821021-b03794e0-aaef-45a1-88ec-ffa9b838997f.png)

This ought to be reopened.

---

Even if the columns don't expand to utilize the available window space, they're seemingly wide enough in their current state to show more characters.

However, the resulting content is cut off with “…” at the end of the entries.

![image](https://user-images.githubusercontent.com/67732686/193816805-1e8083a3-f69e-4f45-950f-1afb1498b3ef.png)


---

The options and contents overall would benefit from utilizing the space as they're currently relatively cramped together, making things take a second to distinguish and understand.

![image](https://user-images.githubusercontent.com/67732686/193816723-6b42ab57-1400-419f-a121-bacbf363ca32.png)

---

Throwing around some elements for inspiration:

![image](https://user-images.githubusercontent.com/67732686/193823921-8d49bc5c-448c-46c2-a695-9164d026bc2b.png)
