### ISSUE TITLE
Bug – Installation: Successful installations don't disappear from the list at the bottom

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#234]
![image](https://user-images.githubusercontent.com/67732686/195301411-b5cbcfa1-2510-476b-b638-ec8f51e9ccf3.png)

For updates, it works as expected.

As can be seen in the screenshot, both Winget and Scoop apps were tested to make sure it's isolated to the Discover packages section of the app and not a particular package manager.

…and yes, when uninstalling apps from the Installed packages section it works as intended and disappears as well.

**Comment by ppvnf** [comment]
I am unable to reproduce this on Windows 10. Installs disappear as intended

**Comment by RavenMacDaddy** [comment]
Weird… Tested restarting the app just to be sure, but installing .NET Framework which was readily available at the top (source: Winget), it still didn't disappear.

Personally, I'm running it on Windows 11 rather than 10.

**Comment by ppvnf** [comment]
@RavenMacDaddy, which button are you using to install .NET Framework? 
For me installing it using the context menu button and the info menu worked, but I got an error when I tried to use the search menu install button. Do you also get this error? 

https://user-images.githubusercontent.com/73800734/195332060-43d117a8-1853-46c0-a53a-93e8ccb90a05.mp4

**Comment by RavenMacDaddy** [comment]
I get the same error as you when using the installation button at the top left – that needs to be posted as a separate issue, though, would you mind?

Back OT, the successful installation progress is the same for me, with the difference that the list at the bottom doesn't get emptied;

https://user-images.githubusercontent.com/67732686/195334159-73c9e296-bb6e-4638-a02f-5570393f11db.mp4

**Comment by ppvnf** [comment]
I was able to reproduce this error. It happens when you have this option checked:
![Captura de tela 2022-10-12 111845](https://user-images.githubusercontent.com/73800734/195367894-f812449a-7fd6-4409-aec2-1635cf10d3d4.png)

**Comment by RavenMacDaddy** [comment]
Good, then we at least know the cause.

**Comment by ppvnf** [comment]
@martinet101, it's fixed for me. I'm using 46816adc20a885d71ff431fdaddd10ab56ee7488

**Comment by RavenMacDaddy** [comment]
I'm currently not using the app and so forth as things are a bit rough, I don't mind closing this for now.

**Comment by ppvnf** [comment]
In case you are one day interested in testing the beta version, I have added instructions [here](https://github.com/martinet101/WingetUI/wiki#running-and-building-the-source-code). The easiest way to do it IMO is:

1. Download the source code [here](https://github.com/martinet101/WingetUI/archive/refs/heads/main.zip) and extract it
2. Install Python 3.10 through Winget
3. [Install dependencies](https://github.com/martinet101/WingetUI/wiki#installing-dependencies)
4. Run build.bat (inside WingetUI-main)
