### ISSUE TITLE
Bug: Scrolling the mouse wheel beside the list has no reaction

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#24]
![image](https://user-images.githubusercontent.com/67732686/170050898-d48d21b5-d8bd-4524-b2d6-b92f0749f0e2.png)

Let's say I want to position my mouse to either side of the list to not block the content that I want to scroll.

Currently this has no reaction to input - only when the mouse hovers over the list it works.

**Comment by martinet101** [comment]
Mhmm... This would mean reimplementing the scroll event... I guess it is possible, thoug.

**Comment by martinet101** [comment]
Fixed!

**Comment by Superuser18** [comment]
I'm facing the same issue. Scrolling with the mouse wheel never worked for me.
