### ISSUE TITLE
Bug: Scoop bucket successful installation message doesn't disappear automatically from the bottom panel

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#241]
Similar to https://github.com/martinet101/WingetUI/issues/234

![Captura de tela 2022-10-13 113332](https://user-images.githubusercontent.com/73800734/195626551-89f9545e-1d9b-4acd-829e-4ef91f5f05b9.png)

**Comment by martinet101** [comment]
Done!
