### ISSUE TITLE
Remove bucket displays wrong message

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#243]
Today I removed nonportable bucket and this was the (confusing) message/notification displayed:

![Captura de tela 2022-10-13 141653](https://user-images.githubusercontent.com/73800734/195664424-9f1e20bc-a449-4b15-b6fa-0fb80b07d59c.png)

**Comment by martinet101** [comment]
Whoops...

This must be because the bucket has a custom command set...

**Comment by ppvnf** [comment]
It does work though

**Comment by martinet101** [comment]
Yes, but the thing is that it runs a custom command from an installer widget instance, so it says it has been installed while the command removes the bucket

**Comment by martinet101** [comment]
Fixed!
