### ISSUE TITLE
Bug: Descriptions get cut off if they're long

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#25]
![image](https://user-images.githubusercontent.com/67732686/170054867-506c9905-380e-4c7f-a45f-5c485fe2d830.png)

**Comment by martinet101** [comment]
Can you please check if the descripton is complete in the manifest file?

**Comment by RavenMacDaddy** [comment]
![image](https://user-images.githubusercontent.com/67732686/170256866-0ee462fb-a50d-4036-b159-a543df00a005.png)

**Comment by martinet101** [comment]
It should now be fixed
