### ISSUE TITLE
Display the date of when the package was lastly updated

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#253]
For example, 

scoop.sh:
![Captura de tela 2022-10-14 063217](https://user-images.githubusercontent.com/73800734/195814297-c0240aeb-9402-4e8c-81dc-8fdb363717e7.png)

winstall:
![Captura de tela 2022-10-14 063546](https://user-images.githubusercontent.com/73800734/195814765-75587fc9-7383-407d-b3ef-b9540def8c04.png)

**Comment by martinet101** [comment]
Doable both from scoop and winget
![image](https://user-images.githubusercontent.com/53119851/195859901-00dd9020-b064-4877-95db-a42bc3e17638.png)

**Comment by ppvnf** [comment]
Partially related to https://github.com/martinet101/WingetUI/issues/303 and https://github.com/martinet101/WingetUI/issues/396

**Comment by martinet101** [comment]
Winget:
![image](https://user-images.githubusercontent.com/53119851/205987329-a38d40af-67f2-49ef-af6c-edc45965e9a3.png)

Scoop:
![image](https://user-images.githubusercontent.com/53119851/205987415-d78a9621-dd31-4094-9b7b-c8e190ad9407.png)
