### ISSUE TITLE
(Beta version) Cut off in "Instant Search"

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#254]
![Captura de tela 2022-10-14 075917](https://user-images.githubusercontent.com/73800734/195831949-6805fbbe-8a89-4eab-b731-efeb1e928b19.png)

This happens even with the font installed on Windows 10. Only on Discovery tab, every time WingetUI is opened. Changing to another tab fixes the problem.

I'm using 41d9d48a986fb56c2fa475d512c1a0977fc3da35

**Comment by martinet101** [comment]
Yes, this is a thing I have in mind. Also, with other languages some text widths are different, so a UI improvement needs to be done

**Comment by martinet101** [comment]
Now the headers will resize to accomodate all the content. 

You can see the catalan UI example, where the checkbox has a longer text, and it shows fine

![image](https://user-images.githubusercontent.com/53119851/195940786-df143f74-225c-489f-bb4e-3bdd3b7c04b9.png)
