### ISSUE TITLE
What is this checkbox used for

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#257]
I don't understand its function:

![Captura de tela 2022-10-14 115514](https://user-images.githubusercontent.com/73800734/195878575-2e1e843d-8bb4-4367-8242-52934822e8c4.png)

**Comment by martinet101** [comment]
Winget often can't detect the version of some apps (for example windirstat), and they are always shown as updates. But they are hidden by default, but they can be shown with this toggle.
