### ISSUE TITLE
! and : missing in Catalan translation

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#259]
![Captura de tela 2022-10-14 141159](https://user-images.githubusercontent.com/73800734/195915530-c17ebb6b-f3d4-4779-9000-ce5854e23cbd.png)
![Captura de tela 2022-10-14 140630](https://user-images.githubusercontent.com/73800734/195915539-8b45bc74-65ea-4438-ac12-2c4fb64b3506.png)
![Captura de tela 2022-10-14 141123](https://user-images.githubusercontent.com/73800734/195915541-96b83dd3-49d6-4e17-b06d-2b0722a413be.png)

**Comment by martinet101** [comment]
Thanks!

**Comment by martinet101** [comment]
Btw, i have added screenshots on the double-parameter strings, you can check them out by clicking the little cameras down there.
![image](https://user-images.githubusercontent.com/53119851/195916824-b12f2455-fffb-4ab0-96b2-ffa86ebc03b6.png)
