### ISSUE TITLE
Feature request: Persist list position after search

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#26]
![image](https://user-images.githubusercontent.com/67732686/170055437-2df4ac69-771f-44ba-8bff-bea2b25b9d81.png)

The app clearly knows where I was before I searched for something, and it does already persist my position if I switch sections in the app.

Is it possible to persist the position after a search to avoid the need to scroll all the way down again?

**Comment by martinet101** [comment]
I guess something can be done

**Comment by martinet101** [comment]
Done!
