### ISSUE TITLE
Reduce empty space + move version number below

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#261]
I did actually try to fix it myself, but I don't have enough skill...

- [x] Reduce space between component information and About WingetUI

![Captura de tela 2022-10-14 184003](https://user-images.githubusercontent.com/73800734/195952613-18230641-8fe4-4f75-8a0d-63a8ffd4ffbf.png)

- [x] Reduce space between language ComboBox and General preferences

![Captura de tela 2022-10-14 183924](https://user-images.githubusercontent.com/73800734/195952616-bd4f0d5d-5d35-4499-8227-bf91e861132a.png)

- [ ] Move version to above the description

![Captura de tela 2022-10-14 184003](https://user-images.githubusercontent.com/73800734/195953030-3a7fb12d-a3f5-4d69-ac3b-485c44c81623.png)

**Comment by martinet101** [comment]
> * Move version to above the description

I honesly like it how it is right now
