### ISSUE TITLE
Question about translation

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#264]
![Captura de tela 2022-10-14 223644](https://user-images.githubusercontent.com/73800734/195963350-0fe0f85c-8f4a-4b25-8075-649d1b3a0371.png)

what's correct {0} or {}?

**Comment by ppvnf** [comment]
I believe Catalan is the correct one and French/English should be fixed

**Comment by martinet101** [comment]
This shoukd work
```
>>> "a{}c".format("b")
'abc'
```

However, the {0} is better, because when there's more than one parameter it lets properly place them in their correct positions
