### ISSUE TITLE
Disable workflow for other people

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#266]
I got this email:

![Captura de tela 2022-10-15 054121](https://user-images.githubusercontent.com/73800734/195977644-a79b5bad-66bf-48a3-a685-96a1d8687bdb.png)

I know I can disable this myself, but maybe [this ](https://github.com/orgs/community/discussions/26704#discussioncomment-3252979) is better:

>     1. Keep all the workflow YAML files in your forked repository, include yours and other people’s.
> 
>     2. In your workflows, add the following [**if conditional**](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif) for each job.
>        if: github.repository == ‘jimbob88/Osiris’
> 
>     3. In other workflows, add the following if conditional for each job.
>        if: github.repository != ‘jimbob88/Osiris’

**Comment by martinet101** [comment]
I have changed the action permissions so the workflows only run on the root repo. 

Could you please confirm that this run does not occur again?

**Comment by ppvnf** [comment]
Thanks! I've enabled workflow notification again, so I will reopen this if I receive a new one.

**Comment by ppvnf** [comment]
![Captura de tela 2022-10-16 032021](https://user-images.githubusercontent.com/73800734/196021353-9f32b69b-e8f5-4792-b103-a538806d443e.png)

**Comment by martinet101** [comment]
I see

**Comment by martinet101** [comment]
Has this issue happened again?

**Comment by ppvnf** [comment]
> Has this issue happened again?

It happened 3 days in a row so I disabled workflow notification
