### ISSUE TITLE
Missing punctuation in Catalan/French

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#271]
![Captura de tela 2022-10-15 095405](https://user-images.githubusercontent.com/73800734/195993124-3b6c7f01-28ac-4ce8-bc0b-c83422d01173.png)
![Captura de tela 2022-10-15 100134](https://user-images.githubusercontent.com/73800734/195993125-9a1f26e2-a747-4280-b7f5-c01dd9b4c638.png)
![Captura de tela 2022-10-15 100116](https://user-images.githubusercontent.com/73800734/195993126-2c7b5d3c-0f83-4ad0-8d28-405a4894fe83.png)
![Captura de tela 2022-10-15 071843](https://user-images.githubusercontent.com/73800734/195993127-b9884615-71a0-40b6-abf0-3752cf6430de.png)

I think in French there's a space before the punctuation mark

**Comment by martinet101** [comment]
Yes, the french grammar states that there must be spaces between punctuation signs and words.
