### ISSUE TITLE
Catalan translation missing punctuation

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#276]
![Captura de tela 2022-10-15 182001](https://user-images.githubusercontent.com/73800734/196008132-c8514c7b-9d08-4a3a-8b27-bbec18dc3edf.png)
![Captura de tela 2022-10-15 181646](https://user-images.githubusercontent.com/73800734/196008134-1d12c7d5-4118-49c3-99c4-270d26587c5b.png)

**Comment by martinet101** [comment]
I have fully checked again catalan. No more punctuation should be missing
