### ISSUE TITLE
Chinese translation missing punctuation

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#277]
I was conducting a review on the Portuguese translation and besides finding (and fixing) errors on my own translation I've found possible mistakes on the Chinese one. I don't know Chinese, so some of those may in fact be correct:

![Captura de tela 2022-10-15 181323](https://user-images.githubusercontent.com/73800734/196008228-237b39f7-e44f-4880-9655-2bd18b294a50.png)
![Captura de tela 2022-10-15 181357](https://user-images.githubusercontent.com/73800734/196008229-10dc6498-cb8c-4cdd-a7f7-3b94b9bec3d0.png)
![Captura de tela 2022-10-15 181252](https://user-images.githubusercontent.com/73800734/196008230-a9f01ba1-2d4f-4bc5-a00d-44c39dad5952.png)
![Captura de tela 2022-10-15 181304](https://user-images.githubusercontent.com/73800734/196008232-4557ef1f-defb-4c60-b097-5b2507906183.png)
![Captura de tela 2022-10-15 181005](https://user-images.githubusercontent.com/73800734/196008234-8bd8813c-b2f6-425b-b281-82fc90927709.png)
![Captura de tela 2022-10-15 180943](https://user-images.githubusercontent.com/73800734/196008235-c498d8a1-e1fe-44c0-ade8-11c6b18d15fa.png)
![Captura de tela 2022-10-15 180607](https://user-images.githubusercontent.com/73800734/196008236-a9aa8756-5a6e-47a1-b83e-06b578a1a367.png)
![Captura de tela 2022-10-15 180904](https://user-images.githubusercontent.com/73800734/196008238-c0274b33-c256-4d41-b1bb-505015d064ac.png)
![Captura de tela 2022-10-15 180913](https://user-images.githubusercontent.com/73800734/196008239-d5936ab5-1e5b-48eb-8d9f-14698ff671b1.png)
![Captura de tela 2022-10-15 181125](https://user-images.githubusercontent.com/73800734/196008240-973d15f4-63e4-4b9f-ba15-0051d3c79be9.png)
![Captura de tela 2022-10-15 181137](https://user-images.githubusercontent.com/73800734/196008242-d55507b0-6f63-4a95-b0a8-176c9dcca732.png)

**Comment by ppvnf** [comment]
@BUGProtectionAssociation Sorry for tagging you, would you mind confirming this and fixing it if the punctuation is indeed missing?

**Comment by BUGProtectionAssociation** [comment]
> 

It may be fixed successed.

**Comment by BUGProtectionAssociation** [comment]
> @BUGProtectionAssociation Sorry for tagging you, would you mind confirming this and fixing it if the punctuation is indeed missing?

It works as normal now if not have other trouble

**Comment by ppvnf** [comment]
Thanks for the fast answer!
