### ISSUE TITLE
Bug: Winget manifests come up as 'Unknown'

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#28]
![image](https://user-images.githubusercontent.com/67732686/170058790-14398ff7-5c18-4764-9522-5caed8402cf2.png)

In the example given, the appropriate manifest would probably be: https://github.com/microsoft/winget-pkgs/blob/master/manifests/u/Unchecky/Unchecky/1.2/Unchecky.Unchecky.yaml

**Comment by martinet101** [comment]
This is a think i must work out, since the manifest path is not provided by winget

**Comment by martinet101** [comment]
As I have seen, `winget show packageManifest` does not give any information related to a manifest path. 

The text will change from unknown to "Not applicable", since this fature is thought for scoop
