### ISSUE TITLE
Translate message needs fixing (also affects 1.4.2)

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#281]
- [x] Translation message is broken in the about section

![Captura de tela 2022-10-16 050137](https://user-images.githubusercontent.com/73800734/196025168-354c80e8-d4f9-441f-b879-6b73f71bbd64.png)

- [x] Replace ElevenClock with WingetUI in the translation message

![Captura de tela 2022-10-16 050011](https://user-images.githubusercontent.com/73800734/196025169-a224329d-2bf3-4715-95bc-ee3913df7d22.png)

- [ ] I would use the donation message in the about section and the translation message in the settings page

**Comment by martinet101** [comment]
Done! I don't know why it said ElevenClock, i guess i mixed files and linked ElevenClock announcement to WingetUI and ElevenClock.

Now it looks better

![image](https://user-images.githubusercontent.com/53119851/196030154-5370968a-3f8d-4d04-bb46-1ef728c63c0b.png)

**Comment by martinet101** [comment]
> * would use the donation message in the about section and the translation message in the settings page

About this, i might do a section in the about page about dev, contributors and ways to support the app, rather than using one of the announcements...
