### ISSUE TITLE
Unable to install » Folder names cannot include...

### ISSUE THREAD

**Issue by PwrSrg** [martinet101/WingetUI#289]
I am unable to install the latest build (v1.4.2) due to the following **Windows 11 ERROR**:

```
Folder names cannot include any of the following characters:
/ : * ? ` < > |
```

Video: https://youtu.be/4abWJ24WM-k

https://user-images.githubusercontent.com/711603/196261104-a98eeab5-3eec-4cc8-81d6-1475bd8c298b.mp4

**Comment by martinet101** [comment]
Hi,

can you please share your user directory path?

(if you prefer send it to marticlilop@gmail.com since this is private information)

**Comment by PwrSrg** [comment]
`C:\Users\PwrSrg`

![image](https://user-images.githubusercontent.com/711603/196271846-e6689162-c3c9-4531-b3f4-93990666f0b6.png)

**Comment by martinet101** [comment]
Hi, Have you tried reinstalling the app through winget?

Also, what is the value of the env var `%localappdata%`?

**Comment by PwrSrg** [comment]
> Hi, Have you tried reinstalling the app through winget?
Yes, that is how I first received the error.

> Also, what is the value of the env var %localappdata%?
`%localappdata%`  »  `C:\Users\PwrSrg\AppData\Local`

I am going to try to remove all traces of WinGetUI and see if that helps.

**Comment by martinet101** [comment]
Could you please try running a health check on your pc? Cause this issue is probably caused due to system corruption

**Comment by martinet101** [comment]
https://www.windowscentral.com/how-use-dism-command-line-utility-repair-windows-10-image

**Comment by PwrSrg** [comment]
> Could you please try running a health check on your pc? Cause this issue is probably caused due to system corruption

It's a brand new install, so I doubt it.  But I will try.

**Comment by martinet101** [comment]
Do you have any third-party anti-virus running?

**Comment by PwrSrg** [comment]
> Do you have any third-party anti-virus running?

Nope.  I just booted into SAFE MODE and cleared out ALL of my TEMP directories.  So I will see if that makes a difference.

What is super strange is that it originally installed FINE a few weeks ago.  It is only THIS UPDATE that refuses to install correctly.

**Comment by martinet101** [comment]
The last version still installs fine?

**Comment by ppvnf** [comment]
@PwrSrg how about disabling AV and/or running the installer as admin?

**Comment by martinet101** [comment]
I did not release the executable itself, but it looks as if someone did, compressed it and released it as a portable version. (the file looks correct)

However, portable versions don't tend to work at 100%, and i don't recommend using them

**Comment by PwrSrg** [comment]
> I did not release the executable itself, but it looks as if someone did, compressed it and released it as a portable version. (the file looks correct)
> 
> However, portable versions don't tend to work at 100%, and i don't recommend using them

OK, thanks for confirming.  I will have to track this down because this is **EXACTLY** what we are looking for!  Especially since I still can't get the **official** installer to run correctly. 😔

**Comment by martinet101** [comment]
I'll make n'est installers ask where WingetUI should be installed, so you can choose a different path and extract wingetui to a valid folder

**Comment by ppvnf** [comment]
@PwrSrg maybe it's fixed in version 1.5

**Comment by martinet101** [comment]
Yes, you can now change I stallation location

**Comment by PwrSrg** [comment]
Hello all.  The ability to change the installation path resolved the installation issue.  But the GOAL is still to have a **portable version** like the one I had been using, so I will keep looking for that.

Also for reference, the path that the old installer was trying to use and kept erroring on was:
`C:\Users\[my username]\.wingetui\_MEI71842\sudo\C:\Portable\Portable Apps\WingetUI`

The `C:\Portable\Portable Apps\WingetUI` path was obviously the path to my portable standalone executable.
