### ISSUE TITLE
WingetUI fails to detect the source of a few Winget packages

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#291]
If I use the command `winget list " "` I am able to properly see which packages are from Winget. However, in WingetUI the source of a few of those packages aren't properly recognized (they show as local pc). This seems related to the fact that they were recently added to Winget, but I don't know why this would matter.  

Example: MediaArea.MediaInfo.Gui

![Captura de tela 2022-10-17 220656](https://user-images.githubusercontent.com/73800734/196311572-45e9bebd-edc1-4877-b9ad-df188cfece12.png)
![Captura de tela 2022-10-17 220518](https://user-images.githubusercontent.com/73800734/196311576-edf26859-46b8-482e-b793-2650b9635d73.png)

**Comment by martinet101** [comment]
This happens with packages that have more than one point on their id. I'm aware of this, but i want to differentiate them from android apps installed on W11, that also share the same id scheme

**Comment by martinet101** [comment]
It should be fixed now
