### ISSUE TITLE
[FEATURE REQUEST] Add WingetUI to majorgeeks

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#297]
https://www.majorgeeks.com/files/details/elevenclock.html is already added. How about adding WingetUI as well?

**Comment by martinet101** [comment]
I don't really know how to add it. They were who actually added ElevenClock

**Comment by ppvnf** [comment]
I think there's no reason to keep this issue open. It would be great if they add it, but if they don't there isn't nothing that can be done by you
