### ISSUE TITLE
[FEATURE REQUEST] add info icon to uninstall section

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#299]
![Captura de tela 2022-10-18 211354](https://user-images.githubusercontent.com/73800734/196569314-3cfd535a-9977-402b-a05b-3487de340e10.png)

**Comment by ppvnf** [comment]
What would happen if source is local pc?

**Comment by martinet101** [comment]
In fact, when you right-click an app this option won't always show, and it will depend on the package provider

**Comment by ppvnf** [comment]
> "This app is not avalable through any package manager"

I agree. There's just a small typo in "available"
