### ISSUE TITLE
Upgrade list

### ISSUE THREAD

**Issue by DAmNRelentless** [martinet101/WingetUI#3]
Looks promising and better than all GUIs I have seen for WinGet so far. Is this still being worked on?

I would love to see another tab to update your installed apps in the future or that the discover tab shows which software is installed already and if it needs updates. Design-wise, I would prefer another tab though. :)

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/168047816-a919c04b-e441-4a18-af9e-8cdccc9eb047.png)
It is coming...

**Comment by martinet101** [comment]
Upgrade to version 1.0 to get this new feature
