### ISSUE TITLE
[FEATURE REQUEST] Also have portable version for future releases

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#302]
**Is your feature request related to a problem? Please describe.**
I didn't think this would be useful, but maybe it would be helpful for a few people like in https://github.com/martinet101/WingetUI/issues/289

**Describe the solution you'd like**
I think running build.bat without Inno already makes a semi-portable installation. I am unsure about WingetUI updates and the .wingetui preference folder tho

Edit: This issue is more like a general suggestion, so feel free to close it

**Comment by martinet101** [comment]
> I think running build.bat without Inno already makes a semi-portable installation. I am unsure about WingetUI updates and the .wingetui preference folder tho

that would be messed up.

Also, the portable installation would mean self-extractable files, which dump loads of temp files in the %temp% folder and are way slower. Trust me, i have used them and they are not a good option.

Also, the issues like #289 _shouldn't_ happen, rather that should be fixed with portable installations

**Comment by ppvnf** [comment]
Tbh since Winget was released I am no longer using portable apps that much, although I still use some portable Scoop apps. So, this feature isn't really something I think as that important. However, would you really have to use the temp folder? Wouldn't it be possible to simply create more folders inside the main WingetUI folder? Again, this isn't something I plan to do with WingetUI, but I like the simplicity of portable apps. You can move the app folder to another PC or USB drive and it works exactly the same (I personally dislike having to move config files from AppData or another random folder, but I understand the downside of the user losing the config data after deleting the app).

**Comment by martinet101** [comment]
Yeah, that's how PyInstaller works. It's temp folder or nothing

**Comment by ppvnf** [comment]
> Yeah, that's how PyInstaller works. It's temp folder or nothing

I see

**Comment by PwrSrg** [comment]
I believe the type of "portable version" the OP is referring to is a **standalone executable**, not a different type of installer.

**EXAMPLES:**
https://github.com/Romanitho/Winget-Install-GUI  (WiGui_1.8.0.exe)
https://www.jonasjohn.de/red.htm  (empty-folder-nuker-1.3.0.exe)
https://github.com/amd989/Symlinker  (Symlink.Creator.zip)
https://www.advanced-ip-scanner.com  (Advanced_IP_Scanner_2.5.4594.1.exe)
https://github.com/Gisto/Gisto  (Gisto-1.13.4-Portable.exe)
https://papas-best.com/stlviewer_en  (Best STL Viewer.exe)
https://github.com/ebkr/r2modmanPlus/releases/download/v3.1.32  (r2modman-3.1.32.exe)
https://github.com/jgraph/drawio-desktop  (draw.io-20.3.0-windows-no-installer.exe)
https://github.com/hxseven/Remove-Empty-Directories  (red-v2.2-portable.zip)

**Comment by ppvnf** [comment]
> I believe the type of "portable version" the OP is referring to is a **standalone executable**, not a different type of installer.
> 
I actually didn't specifically think about this kind of portable app, but I have not against it. You mean something like an AppImage for Linux, right? Personally I don't care if the portable app is simply a ZIP with multiple files inside or a standalone EXE. IMO a portable app of any type would be a good feature to have, but I am not a developer so I can't say if there's a way to make WingetUI portable. Initially I thought this wouldn't be a hard thing to do since you can easily build the app like [this](https://github.com/martinet101/WingetUI/issues/234#issuecomment-1284053313), but after reading [martinet101's answer](https://github.com/martinet101/WingetUI/issues/302#issuecomment-1284413025) I can't imagine a way to make it work.

**Comment by martinet101** [comment]
> for Linux, right? Personally I don't care

Yes

> I believe the type of "portable version" the OP is referring to is a **standalone executable**, not a different type of installer.
> 
> **EXAMPLES:** https://github.com/Romanitho/Winget-Install-GUI (WiGui_1.8.0.exe) https://www.jonasjohn.de/red.htm (empty-folder-nuker-1.3.0.exe) https://github.com/amd989/Symlinker (Symlink.Creator.zip) https://www.advanced-ip-scanner.com (Advanced_IP_Scanner_2.5.4594.1.exe) https://github.com/Gisto/Gisto (Gisto-1.13.4-Portable.exe) https://papas-best.com/stlviewer_en (Best STL Viewer.exe) https://github.com/ebkr/r2modmanPlus/releases/download/v3.1.32 (r2modman-3.1.32.exe) https://github.com/jgraph/drawio-desktop (draw.io-20.3.0-windows-no-installer.exe) https://github.com/hxseven/Remove-Empty-Directories (red-v2.2-portable.zip)

Yes, a standalone executable would require temp extraction on every single run

**Comment by ppvnf** [comment]
@martinet101 did you also consider simply a ZIP file with the contents of wingetuiBin folder and changing the .wingetui preference folder to inside wingetuiBin folder? One problem that I can think about this approach is how to update the portable version.

**Comment by martinet101** [comment]
I guess the best solution would be to allow the installer to change installation dir, and allow like extracting to a USB or something

**Comment by ppvnf** [comment]
> I guess the best solution would be to allow the installer to change installation dir, and allow like extracting to a USB or something

That's a little bit different, but I guess it would also work. A portable "install" wouldn't create a desktop/start menu icon nor register in the Control Panel and also would not have files in place besides the install folder, right?

**Comment by martinet101** [comment]
You can disable the icon, but while it being portable, sometimes is useful to have an icon that points to the portable destination

**Comment by ppvnf** [comment]
> You can disable the icon, but while it being portable, sometimes is useful to have an icon that points to the portable destination

I agree. By the way, shouldn't the regular install also have the option to create (or not) a start menu shortcut and maybe even a taskbar shortcut?

**Comment by martinet101** [comment]
The start menu icon is added automatically, the desktop icon is optative and I dont think it would be a good practice to bloat users Taskbar with new icons. I guess this should be each user's choice.

**Comment by ppvnf** [comment]
I don't think it would make much sense to add a start menu icon in portable mode

**Comment by martinet101** [comment]
I might as well make a switch for this

**Comment by martinet101** [comment]
Next versions will allow to choose where to install and will allow to disable shortcuts on the desktop and on the start menu

**Comment by PwrSrg** [comment]
Since this is now **[CLOSED]** does that mean there is now a **PORTABLE version**?!?  🤩🤩🤩

**Comment by martinet101** [comment]
I mean, you can install it on a USB and then run the executable from there

**Comment by martinet101** [comment]
(and not rn, just starting from the next version)

**Comment by PwrSrg** [comment]
Hey @martinet101,

Just checking back on this.  I know it is not a priority of yours, but was just curious if by "next version" you were referring to either of the last two releases since your comment - 1.5.0 or 1.5.1?

Thanks!

**Comment by martinet101** [comment]
the installerr of 1.5.1 should now allow you to install on an USB, don't they?

**Comment by PwrSrg** [comment]
> the installerr of 1.5.1 should now allow you to install on an USB, don't they?

**OH, GREAT!**  There was no mention of it in the release notes so I hadn't attempted it yet, but will do so NOW.

**Thanks!**

**Comment by ppvnf** [comment]
I think this approach to a portable install should be considered in order not to have an uninstall entry created by the installer: https://github.com/sandboxie-plus/Sandboxie/blob/master/Installer/Sandboxie-Plus.iss

```
[Setup]
Uninstallable=not IsPortable
```

It also allows using `/portable` parameter, although I do not think it would be very useful

**Comment by ppvnf** [comment]
a portable install, I suppose, would also keep the appdata in the install folder

**Comment by marticliment** [comment]
Yes, however, I'm not quite sure on how to distinc between portable and nonportable installations

**Comment by marticliment** [comment]
Next version of the installer will have an option to not create any kind of shortcut

**Comment by ppvnf** [comment]
> a portable install, I suppose, would also keep the appdata in the install folder

Nice. did you also manage to do that?

**Comment by marticliment** [comment]
> > a portable install, I suppose, would also keep the appdata in the install folder
> 
> Nice. did you also manage to do that?

No, configuration will be machine-dependant. 
Since settings depend on wether files exist or not, there is no way to properly detect where settings are stored
