### ISSUE TITLE
[BUG/ISSUE] (Beta Version - screenshot update) The version of some Winget apps fails to load and is shown as "Unknown"

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#304]
TODO:

- [x]  After you open the info menu it becomes impossible to scroll the package list:

https://user-images.githubusercontent.com/73800734/196812914-9af70bc8-a094-4bb1-b27e-692002335559.mp4

- [x]  If you move to another section the previous one continues selected:

[![Captura de tela 2022-10-19 125030](https://user-images.githubusercontent.com/73800734/196796310-58cf151a-e6a5-434f-a17a-078ff3312dff.png)](https://user-images.githubusercontent.com/73800734/196812903-9fd38017-a304-46f3-8d0a-49c5a0f57bb6.mp4)

- [ ] The version of some Winget apps fails to load and is shown as "Unknown":

![Captura de tela 2022-10-19 174020](https://user-images.githubusercontent.com/73800734/196799689-934f7cf4-8e02-4842-88f1-9747f62d6052.png)

![Captura de tela 2022-10-19 174236](https://user-images.githubusercontent.com/73800734/196799863-5a3d087f-1211-4b87-9687-7a1ab7ffa073.png)

**Comment by martinet101** [comment]
> After you open the info menu it becomes impossible to scroll the list and if you move to another section this happens (the previous one continues selected):

I don't think I understand what you mean... That should have happened in older versions also

**Comment by ppvnf** [comment]
> > After you open the info menu it becomes impossible to scroll the list and if you move to another section this happens (the previous one continues selected):
> 
> I don't think I understand what you mean... That should have happened in older versions also


https://user-images.githubusercontent.com/73800734/196812903-9fd38017-a304-46f3-8d0a-49c5a0f57bb6.mp4


https://user-images.githubusercontent.com/73800734/196812914-9af70bc8-a094-4bb1-b27e-692002335559.mp4

**Comment by martinet101** [comment]
Oh I see. I did not realise that. Gonna fix it

**Comment by martinet101** [comment]
> * [ ]  The version of some Winget apps fails to load and is shown as "Unknown":

Winget is failing to load info for packages sometimes, it is not only the version. I'll open another issue for that. The UI glitch has been fixed

**Comment by ppvnf** [comment]
I've updated the 

> > * [ ]   The version of some Winget apps fails to load and is shown as "Unknown":
> 
> Winget is failing to load info for packages sometimes, it is not only the version. I'll open another issue for that. The UI glitch has been fixed

Ok, I've changed the title to make this clear 😉
