### ISSUE TITLE
[FEATURE REQUEST] Scoop bucket information should always be displayed

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#311]
**EDIT: The only thing left is to add it to the info menu of the update section as well**: https://github.com/martinet101/WingetUI/issues/311#issuecomment-1287859317

When the package source is Scoop, It's possible to see the bucket information in the Discovery section (in the search menu and in the info menu).

However, in the Update and Install sections, this information isn't available neither in the info menu nor in the search menu, despite being available in CLI:

![Captura de tela 2022-10-20 123547](https://user-images.githubusercontent.com/73800734/196993986-3610fff6-c0f2-4db9-b1da-b365d2d3c968.png)

![Captura de tela 2022-10-20 123620](https://user-images.githubusercontent.com/73800734/196993979-71ca13fb-98af-4486-adc8-2572679a32e0.png)

![Captura de tela 2022-10-20 124005](https://user-images.githubusercontent.com/73800734/196994837-4b6a1494-daf4-41e9-b220-501d0fe1c0a9.png)

**Comment by martinet101** [comment]
> However, in the Update and Install sections, this information isn't available neither in the info menu nor in the search menu, despite being available in CLI:

When listing updates it is not possible to see the bucket.

**Comment by martinet101** [comment]
Done!

**Comment by ppvnf** [comment]
Would it be possible to add it to the info menu of the update section as well?
 
![Captura de tela 2022-10-22 141618](https://user-images.githubusercontent.com/73800734/197353623-b4d1d340-baab-4ff6-807e-f516dc3ae9ee.png)
![Captura de tela 2022-10-22 141332](https://user-images.githubusercontent.com/73800734/197353624-17d860db-887b-46f4-8efe-6279ec030611.png)

**Comment by martinet101** [comment]
I guess so

**Comment by ppvnf** [comment]
Shouldn't this be reopened,?

**Comment by ppvnf** [comment]
Could the solution applied in https://github.com/martinet101/WingetUI/issues/406 also be used to display the info menu in the update section? 

<details>

1- Update section
![Captura de tela 2022-12-19 091334](https://user-images.githubusercontent.com/73800734/208428522-9d5a3968-b8ff-473e-a6c1-71e3f665e06e.png)

2 - Uninstall section (real info)
![Captura de tela 2022-12-19 092731](https://user-images.githubusercontent.com/73800734/208428525-7097a1ff-5ecd-4ac7-a872-e7e5916edcf9.png)

</details>

**Comment by martinet101** [comment]
Yeeees i think so

**Comment by ppvnf** [comment]
Hm... I have doubts this issue can be fixed because the problem is that `scoop status` doesn't show the bucket and `scoop info`  without bucket/package doesn't identify from which bucket the package is installed

**Comment by martinet101** [comment]
but the json does. the json can be retrieved with scoop info - -verbose

and some scoop info is taken from the json, so the bucket shouldn't be an issue

**Comment by ppvnf** [comment]
> and some scoop info is taken from the json, so the bucket shouldn't be an issue
Do you think it's possible to get the bucket info for packages in the update section using the uninstall list?

![Captura de tela 2022-12-20 064251](https://user-images.githubusercontent.com/73800734/208635435-7b62cf39-82ee-4589-bb80-7a94a4a8e19c.png)
![Captura de tela 2022-12-20 064323](https://user-images.githubusercontent.com/73800734/208635445-8f29fecc-7141-44c1-bc97-43d011e3c2df.png)

I have 2 json files for okular. I don't know how you could find which one is installed, except using `scoop list`
C:\Users\PICHAU\scoop\buckets\extras\bucket\okular.json
C:\Users\PICHAU\scoop\buckets\jr-bucket\bucket\okular.json

**Comment by martinet101** [comment]
WingetUI will check the program id and the installed version with the one found on the updates section, to check if the listed package is the same, and if so, it will get its bucket information.
On the first launch, if the installed list is not already loaded, it has a timeout of 3 seconds before it defaults to the provided version by scoop status
![image](https://user-images.githubusercontent.com/53119851/208690824-7d8c0148-4fa8-453d-8a36-7321dadd92b1.png)
