### ISSUE TITLE
[FEATURE REQUEST] Use more space of the screen to avoid truncate package name and package version

### ISSUE THREAD

**Issue by fernandog** [martinet101/WingetUI#312]
I have a lot of screen space, but WingetUI still truncated package names and package versions. Is there a way to improve this with auto-size @martinet101 

HINT is also truncated (third screenshot)

![image](https://user-images.githubusercontent.com/2620870/197019567-b6169ca6-1a3e-4b42-a13e-5efbae7ddf39.png)

![image](https://user-images.githubusercontent.com/2620870/197019582-42790edc-aadd-457e-a62c-e1b7eb5c462a.png)

![image](https://user-images.githubusercontent.com/2620870/197019605-e5d9c895-b49d-4981-85d6-318e74a51ee6.png)

**Comment by martinet101** [comment]
The names being cut can't be fixed at the moment, because that' a winget issue. 

The version/new version can be fixed though

**Comment by martinet101** [comment]
Fixed!

**Comment by fernandog** [comment]
@martinet101 that was fast. I updated later that HINT is also truncated. 

I don't see a PR for this and the uninstall issue that we talked about the winget search " ". Do you have other repo?

![image](https://user-images.githubusercontent.com/2620870/197022804-169d6890-e7d0-4a15-95a4-d78a1ed62be2.png)

**Comment by fernandog** [comment]
ah, you do only commits, right?

**Comment by martinet101** [comment]
> ah, you do only commits, right?

yes

**Comment by martinet101** [comment]
That hint being truncated is again the issue with winget cutting text out, and not wingetui's fault
