### ISSUE TITLE
[FEATURE REQUEST] Shouldn't these itens be translatable?

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#314]
"Local PC", "Unknown", "Not Found" and "Not Applicable"

1. ![Captura de tela 2022-10-20 153908](https://user-images.githubusercontent.com/73800734/197054926-82597b48-2b72-438f-8342-e4f2321c3199.png)

3. ![Captura de tela 2022-10-20 154856](https://user-images.githubusercontent.com/73800734/197054934-99109137-4f7d-4068-ae44-b93c0fe3f55f.png)

4. ![Captura de tela 2022-10-20 180559](https://user-images.githubusercontent.com/73800734/197058079-3df7339a-eadc-4339-8816-536fbb5550f4.png)

5. ![Captura de tela 2022-10-20 180544](https://user-images.githubusercontent.com/73800734/197058081-b2d528ea-9a19-4467-8aee-4a44a8e2a18f.png)

6. ![Captura de tela 2022-10-31 112749](https://user-images.githubusercontent.com/73800734/199041600-1a07c99f-eefe-4789-9014-c26acd37270c.png)

7. ![Captura de tela 2022-10-31 143941](https://user-images.githubusercontent.com/73800734/199073370-a9748cf8-67b0-45f3-b684-13fa78138dba.png)

**Comment by martinet101** [comment]
Some of them yes, some of them need further study. For example, local pc is used on some checks and i mist be careful when adding this feature

**Comment by ppvnf** [comment]
Edit: I've added a fifth item
