### ISSUE TITLE
[FEATURE REQUEST] Info menu loading is slow for Scoop packages

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#318]
**Is your feature request related to a problem? Please describe.**

The beta version seems to load info much faster for Scoop  packages! 

However a few fields are still a bit slow to load:

![Captura de tela 2022-10-21 195149](https://user-images.githubusercontent.com/73800734/197303465-8216088e-67f5-45a3-9d83-df34fb9e4240.png)

**Describe the solution you'd like**

Would it be possible to also improve the loading speed of these fields?

**Comment by martinet101** [comment]
Nope. That's because scoop show without the --verbose flag is much fasted and provides the basic information faster. However, some info needs the --verbose flag to be shown.

This is the actual reason of it being like this.
