### ISSUE TITLE
[FEATURE REQUEST] A way to view the live output of the console during install/uninstall.

### ISSUE THREAD

**Issue by Spacellary** [martinet101/WingetUI#329]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**

## Is your feature request related to a problem? Please describe.

Not enough clarity about what's happening during the installations, as a progress bar and only the last line alone isn't enough for me to know for example, where files are going.
For scoop packages this is less of a problem, but for Winget they could be anywhere.

## Describe the solution you'd like

`"One the reasons I still install some stuff using the Terminal is because I can read the log output and figure out where the things are going, is there a way to see the WingetUI log live as it installs/uninstalls, like a terminal window/box/panel/side-panel (like in ChocoGUI for example)?"`

I propose some kind of optional/toggle-able window/box/panel/side-panel/pop-up with a live terminal output. If possible with _color syntax_ for easier reading.

## Alternative solution

Alternately this could be downgraded to just a log file of that particular operation, for example once the operation is done we see a brief `OK` button, there should be an option to make they not go away automatically and then add a new button besides that one, a `LOG` button. That would open the log file for that respective operation alone, which the user can then open in their software of choice for easier readability (vscode/notepad++, etc. I don't mind vscode being the default here, personally – eg.: `code drive-letter/[log-folder-path]/log-file_XYZ.log`).

## Additionally

Regardless of the route taken, I believe it would be good to have a "History" of all or "X number" of recent operations as a list, something like this:

```
"Installed: Package.Package [version][timestamp][log file location]"
"Uninstalled: Package.Package [version][timestamp][log file location]"
[...]
```

**Comment by Spacellary** [comment]
Hopefully this was descriptive enough, but should any further clarification, information or feedback be needed I'm here to provide as much as I can in my current capacity!

**Comment by ppvnf** [comment]
I agree that some sort of option to enable verbose mode or install log could be useful sometimes. Regarding not being able to find apps, PowerToys Run is somehow much better than standard Windows Search, which is pretty strange since both are from MS. Another good option for finding folders/files is Everything

**Comment by Spacellary** [comment]
A positive of scoop, but there's the downside of only uninstalling with scoop as well. But I think simply manually deleting the portable folder and shortcuts also works there.

**Comment by Spacellary** [comment]
That's one option, usually what we see in some Linux and windows standalone Installers! I'm starting to the think the log file is a better idea and generally more useful and simple xD

**Comment by martinet101** [comment]
I guess some kind of live output/log can be done

**Comment by martinet101** [comment]
Done!

**Comment by Spacellary** [comment]
Thanks all!
