### ISSUE TITLE
[FEATURE REQUEST] Discover Apps instead of Discover Packages and Discover Software

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#330]
## Before submitting the issue

- [X] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**

## Is your feature request related to a problem? Please describe.

What to do you think?

Discover Apps instead of Discover Packages and Discover Software

![Captura de tela 2022-10-23 200751](https://user-images.githubusercontent.com/73800734/197422604-bb84d970-96a1-444b-b053-f76a8da02e09.png)

## Describe the solution you'd like

I think it's easy to change these on Tolgee (I've opened this issue for confirmation)

**Comment by martinet101** [comment]
I would leave it in software, since some of the _binary executables_ that can be downloaded are utilities, command-line tools and programs that _are not_ applications in the way we understand them. What do you think?

**Comment by ppvnf** [comment]
> I would leave it in **Discover Software**, since some of the _binary executables_ that can be downloaded are utilities, command-line tools and programs that _are not_ applications in the way we understand them. What do you think?

I agree!
