### ISSUE TITLE
why when installing or updating WingetUI from winget by default enable and install scoop?

### ISSUE THREAD

**Issue by candrapersada** [martinet101/WingetUI#333]
![image](https://user-images.githubusercontent.com/36833664/198002076-c04d0e2b-5234-40bb-b5e1-363285384eb1.png)

**Comment by ppvnf** [comment]
I believe this is already fixed (for the next version): https://github.com/martinet101/WingetUI/pull/231/commits/61ccc42bb4b74cfa5f1fbd315168c56f843a7d0f

**Comment by martinet101** [comment]
Yes, this was fixed already, but thanks for pointing opu!
