### ISSUE TITLE
[FEATURE REQUEST] Improve search performance by adding a small delay when typing 

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#335]
## Before submitting the issue

- [X] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**

## Is your feature request related to a problem? Please describe.

If instant search is enabled, typing something in the search bar will make the interface briefly unresponsive (you won't be able to see what has been typed in the search bar before the results are shown. This usually takes a few seconds and is only a visual problem since the search function isn't impaired by not being able to temporarily see what was typed). I think this happens because the search is executed in the instant that the user types something.

## Describe the solution you'd like

Add a small delay when searching for a package. For example, Tolgee will perform the search about a second after the user has stopped typing. I believe this is a good idea because it allows the user to fully see what is being typed, and only after the typing is finished that the search results are shown

**Comment by martinet101** [comment]
Really, this can be done, but the UI will still be unresponsive. If you search on the updates section or on the uninstall section, you'll see that this does nott happen. This is due to the large amout if items WingetUI has to process, so the solution would be threading this function so it doesn't do lag

**Comment by ppvnf** [comment]
> the solution would be threading this function so it doesn't do lag

That would be great and it's probably better than the solution I proposed! 
I am gonna explain a little bit more about it just in case...

> Really, this can be done, but the UI will still be unresponsive.

Only if the search query generate a lot of results. For example, typing only "a" will cause lag, but "aegis" won't.
So, while not a perfect solution, I believe this would be able to eliminate the perceived lag in most cases.

> If you search on the updates section or on the uninstall section, you'll see that this does nott happen.

That's true, this problem happens only in Discovery section

**Comment by martinet101** [comment]
I have added a small delay that _improves_ the behaviour, but this main issue is being caused by Qt having to hide 4800+ items at once, which makes it hang for a sec.

**Comment by ppvnf** [comment]
> I have added a small delay that _improves_ the behaviour, but this main issue is being caused by Qt having to hide 4800+ items at once, which makes it hang for a sec.

It seems a little bit faster now. But don't you think it's possible to improve this even further in the future?

**Comment by martinet101** [comment]
The issue here is the amout of packages that need to be changed from visible to hidden. A solution to this could be disabling `Instant search`, that would disable live results

**Comment by ppvnf** [comment]
I like instant search. I just wished situations like these wouldn't happen:

- For example, typing only "a" will cause lag, but "aegis" won't.

If it's not possible to improve it, then so be it.

**Comment by ppvnf** [comment]
I've done a few tests here the delay you implemented seems like a hit or miss (sometimes it works, sometimes it doesn't). (time.sleep(0.25) did help improve it a little bit further, but even so there are some character combinations that for some reason still lag during typing (even when the complete word generates few results). Is this Python's fault?

**Comment by martinet101** [comment]
No, the issue here is that the searches are being queued up. 

Could you please try latest head again?

**Comment by ppvnf** [comment]
> No, the issue here is that the searches are being queued up.
> 
> Could you please try latest head again?

Thanks! It's definitely much better. I tried many key combinations and most of them are working as expected now. I can't explain why but a few words still lag about 1/3 of the time, for example "test"
