### ISSUE TITLE
Displays the internet speed when downloading the package

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [martinet101/WingetUI#337]
It's strange that Winget has this functionality but WingetUI not.
So we could know What caused the slow installation.
![image](https://user-images.githubusercontent.com/65578116/198178231-e24067a0-d56f-4a84-b3ce-4fc29b556f72.png)

**Comment by martinet101** [comment]
I guess this could get in the "live log" feature.

**Comment by martinet101** [comment]
The live log feature has been added. However, there's no way to get current download speed.

I'm sorry :(
