### ISSUE TITLE
slow download speeds

### ISSUE THREAD

**Issue by venkat2305** [martinet101/WingetUI#338]
## Before submitting the issue

- [ ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that I am running the latest version of WingetUI**
- [ ] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [ ] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**

</b>

## Describe the bug
I tried to download the intellij IDE from wingetUI and the website. the download speed when downloaded from website was around 500mbps but when I tried to install from wingetUI, its only about 80 to 120mbps. Is there any fix for this?

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to the three dots menu on the top-right corner of WingetUI -> Winget Log. 

If the issue can be reproduced, please send the log AFTER reproducing the issue (1. Launch WingetUI, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by martinet101** [comment]
No really, this is an issue with Winget-cli.

Maybe open an issue there?
