### ISSUE TITLE
why no uninstall scoop and Remove the execution policy?

### ISSUE THREAD

**Issue by candrapersada** [martinet101/WingetUI#341]
![image](https://user-images.githubusercontent.com/36833664/198375787-96ac9cf7-e84b-42d0-9fda-c92a315c2b62.png)

**Comment by ppvnf** [comment]
related to https://github.com/martinet101/WingetUI/issues/286
I agree with the option to uninstall scoop, but I think it should display a warning as it also uninstall all scoop packages. I am not sure about resetting the execution policy. How about asking if the user wants to do that?

**Comment by martinet101** [comment]
Is there an official way to remove scoop?

**Comment by ppvnf** [comment]
> Is there an official way to remove scoop?

I've never tried, but I think you can use `scoop uninstall scoop`

**Comment by candrapersada** [comment]
> but I think you can use `scoop uninstall scoop`

how to Remove the execution policy and windows environment variables path after uninstall scoop?

**Comment by ppvnf** [comment]
> how to Remove the execution policy and windows environment variables path after uninstall scoop?
Maybe ask if the user wants to restore it to default value. I believe the execution policy is restricted by default

**Comment by martinet101** [comment]
Done!
