### ISSUE TITLE
[BUG/ISSUE] (Beta) Update not disappearing from the list at the bottom + getting unstable after opening logs

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#343]
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**

</b>

## Describe the bug
After https://github.com/martinet101/WingetUI/commit/7955889e216fb3cdf73b82754391c30f353a00c4 [this issue](https://github.com/martinet101/WingetUI/issues/234) is happening again. I've tested it in the update section, so I am not sure if it happens in other sections:

1. if you don't click to show the log, the successful update message won't disappear.

2. If you click show the log, things get really confusing... (successful install seem to appear as failures and also don't disappear. It's kinda hard to explain, but it is really chaotic)

img 1 (before opening log)
![Captura de tela 2022-10-27 214321](https://user-images.githubusercontent.com/73800734/198424291-987aca09-4b95-4001-abd9-6550467c7b13.png)

img 2 (opening log)
![Captura de tela 2022-10-27 214419](https://user-images.githubusercontent.com/73800734/198424295-bb4d3846-592b-4c9e-a1f5-ef317233c012.png)

img 3 (after opening log)
![Captura de tela 2022-10-27 214028](https://user-images.githubusercontent.com/73800734/198424293-67c865c0-fedf-450f-86c5-d4c97a292c6f.png)

img 4 (after opening log)
![Captura de tela 2022-10-27 214538](https://user-images.githubusercontent.com/73800734/198424288-e373ff7c-1d8a-44e2-a44e-b46c7b9ff99f.png)

Edit: this problem also appears in install/uninstall sections

**Comment by martinet101** [comment]
In theory this issue shouldn't happen anymore. Could you please test the latest head?

**Comment by ppvnf** [comment]
It seems fixed! Good job!
