### ISSUE TITLE
[Question] Why I can't enable notifications at Windows 11 settings > System > Notifications

### ISSUE THREAD

**Issue by fernandog** [martinet101/WingetUI#344]
@martinet101 quick question: I see winget notifications, but I'm wondering why this happens at windows settings

https://user-images.githubusercontent.com/2620870/198586794-2d7f8554-9424-4cb8-af79-1f9eb29b63fc.mp4

**Comment by martinet101** [comment]
Honestly, I don't know. This pane shouldn't appear there.

The notifications shown by WingetUI are handled as regular ballon popups (like on w7 or earlier), so they shouldn't be able to be enabled or disabled by ms settings. 

Do notifications still work, right?

**Comment by fernandog** [comment]
yes, It was a couple of days ago I got a notification, but I remember getting it.

**Comment by martinet101** [comment]
Then i suppose that this is windows bugging out when trying to read win32 apps as uwp packages

**Comment by fernandog** [comment]
@martinet101 I reported an issue at Feedback hub if you want to vote up: https://aka.ms/AAikn5u

**Comment by martinet101** [comment]
It won't allow me to vote cause of the regional prefs, but thanks !
