### ISSUE TITLE
[FEATURE REQUEST] Fix Publisher/Author for Scoop packages

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#347]
## Before submitting the issue

- [X] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**

## Is your feature request related to a problem? Please describe.

The Publisher/Author displayed for Scoop packages is wrong. I know `scoop info` doesn't show it, but I don't think it makes any sense to display the last Github user who edited the JSON file as Publisher/Author.

## Describe the solution you'd like

Publisher/Author could be shown as unavailable/unknown, or you could use some script to parse the URL:

![Captura de tela 2022-10-28 200332](https://user-images.githubusercontent.com/73800734/198750684-53c1a784-5b42-4618-bfb8-2b2bc8beb8b5.png)
![Captura de tela 2022-10-28 194626](https://user-images.githubusercontent.com/73800734/198750686-8485f86a-fd5b-44bf-9930-6b2e6ccbd277.png)
![Captura de tela 2022-10-28 195521](https://user-images.githubusercontent.com/73800734/198750687-5ed4ed66-b0f3-43c1-83d5-1568231975d1.png)

**Comment by martinet101** [comment]
Honestly, I would live it like this, because that's what the package manager says. And while we can add icpns and screenhots, i feel like we should stick on the information that scoop and wingetui provide. Also, this should be fixed by scoop, shouldn't it?.

**Comment by ppvnf** [comment]
> Honestly, I would live it like this, because that's what the package manager says. And while we can add icpns and screenhots, i feel like we should stick on the information that scoop and wingetui provide. Also, this should be fixed by scoop, shouldn't it?.
> 
> What do you think?

I agree about sticking on the information that Scoop and Winget provide, but I think it's confusing to have the last Github user who edited the JSON file appear as Publisher/Author. For example, if I were to edit WingetUI manifest, I would become its Publisher/Author

**Comment by martinet101** [comment]
Maybe the author no, but the publisher yes. You are the one who last edited the file

**Comment by ppvnf** [comment]
> Maybe the author no, but the publisher yes. You are the one who last edited the file

I agree

**Comment by martinet101** [comment]
I thought, if the webpage is a github repo, to take the username as the author
![image](https://user-images.githubusercontent.com/53119851/198835310-a8407723-53b3-415c-b4e0-cb3ac0d7f9d8.png)

**Comment by ppvnf** [comment]
> I thought, if the webpage is a github repo, to take the username as the author 

If it's not a Github repo I think you can take what is between  https:// or http:// and .com/.org (except www.)

![Captura de tela 2022-10-29 105733](https://user-images.githubusercontent.com/73800734/198835687-e81b9c10-0d20-4e9a-8b79-12905a5d490f.png)
![Captura de tela 2022-10-28 195521](https://user-images.githubusercontent.com/73800734/198750687-5ed4ed66-b0f3-43c1-83d5-1568231975d1.png)

**Comment by ppvnf** [comment]
> If it's not a Github repo I think you can take what is between https:// or http:// and .com/.org (except [www](http://www).)

Do you think this is possible?

**Comment by martinet101** [comment]
Yeah, it works.
![image](https://user-images.githubusercontent.com/53119851/198838944-c8cb2c57-9ce5-4156-a70e-4dc04a6dfb0f.png)

**Comment by ppvnf** [comment]
That's great! I wish Scoop itself would add this feature so we could also use it to search pkgs by author like Winget

**Comment by ppvnf** [comment]
would it be possible to improve the parsing script in this case?

![Captura de tela 2022-11-07 213549](https://user-images.githubusercontent.com/73800734/200445964-d58fa406-1a09-4009-b79d-fb39304a4710.png)
![Captura de tela 2022-11-07 213004](https://user-images.githubusercontent.com/73800734/200445966-db5cfa0b-d589-4dba-97bd-c053aab07af3.png)

**Comment by martinet101** [comment]
Done!
