### ISSUE TITLE
[Translation feedback] Why developer is in italic?

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#352]
![Captura de tela 2022-10-29 083750](https://user-images.githubusercontent.com/73800734/198845214-f08bc2c2-dd29-42d8-ab62-9e8d736ac99c.png)

**Comment by martinet101** [comment]
Because I am not a dev. I have no studies in programming or software developing, so in theory i am not a developer, though i have developed a piece of software🤷

**Comment by ppvnf** [comment]
> Because I am not a dev. I have no studies in programming or software developing, so in theory i am not a developer, though i have developed a piece of software🤷

That's hard for me to believe! I thought only billionaires like Bill Gates could learn programming without formal education.

WingetUI seems so advanced that it's almost like magic to me. I really would believe you if you told me you had 17 years of development experience, not of age. I am aware that I don't have any talent, but I still wish to learn how to develop softwares/websites in the future.

It's actually my dream to learn programming, but symbols like > , { \ ' " and specially indentations are very scary to me. I also do not know much about programming software. I've heard about PyCharm and VisualStudio, but I don't know where to start from.

I am actually very curious to know how you've learned so much about software developing (Python and other languages)!

**Comment by martinet101** [comment]
Honestly, my learnings started with windows notepad, trial and error and the most sketchy python calculator you'll ever find.
I'm also afraid of weird symbols like }, * and [, and my knowledge doesn't go further than Python and a little bit html.

That's why  I consider myself a _developer_ and not a **developer**
