### ISSUE TITLE
[BUG/ISSUE] Description of settings subsections isn't translated

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#353]
![Captura de tela 2022-10-29 172835](https://user-images.githubusercontent.com/73800734/198851477-367286a1-17f8-4f09-8566-9f284c0cab52.png)

**Comment by martinet101** [comment]
New translation will be loaded automatically every nignt to every user, without needing an update. After the trabslatikns have been updated on Github, (usually 9am utc), the user will need to restart WingetUI twice to see the changes.

This system was _stolen_ from ElevenClock, where it does work very well.

**Comment by martinet101** [comment]
So any missing changes/corrections can be applied  without needing to release a new update every time

**Comment by ppvnf** [comment]
> So any missing changes/corrections can be applied without needing to release a new update every time

It's not possible to translate this phrase tho:

![Captura de tela 2022-10-29 184344](https://user-images.githubusercontent.com/73800734/198853457-607cb54a-1aae-4f6e-86ca-e757003666f8.png)

**Comment by martinet101** [comment]
Fixed!
