### ISSUE TITLE
[FEATURE REQUEST] Is there a provisional way to upload screenshots?

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#356]
Or is it better to wait you finish the uploader?

**Comment by ppvnf** [comment]
This one is also missing a tag. I've made a pull request that will hopefully fix this for future issues

**Comment by martinet101** [comment]
You can pull request to the file in /Web-based-Data, put I'd rather you wait before I have the contribution algorithm ready.

**Comment by ppvnf** [comment]
ok, you can close the issue or let it open to track this feature?

**Comment by Spacellary** [comment]
@martinet101
Do the images have to be linked from the official websites? Sometimes they don't have them or they aren't in an ideal formator aspect ratio, in that case can we use image hosting websites like imgur.com or postimages.org for example, and upload more appropriate versions of those screenshots for submission?

**Comment by martinet101** [comment]
They don't need to be from anywhere in special. If they work, they work. Obviously, if official screenshots are found it would be better than nothing, but there's no need to stick to official images/icons if better ones are found on other sites

**Comment by ppvnf** [comment]
> imgur.com or postimages.org

Websites like those may delete the image after a certain time. I think it's better to use Github to host the images

**Comment by Spacellary** [comment]
> > imgur.com or postimages.org
> 
> Websites like those may delete the image after a certain time. I think it's better to use Github to host the images

True. That's probably going to be better long term.
They - postimg.cc - do claim that:

> **How long will images remain on the server?**
> You can upload unlimited images per post and you will never have to worry about your images being removed due to inactivity.

And while after years I never had anything from their servers gone missing, it's better to be as safe as possible to avoid breakings that could happen for any reason.

**Comment by martinet101** [comment]
https://github.com/martinet101/WingetUI/wiki#the-icon-and-screenshots-database

I have added a basix explanation (i'll improve it when i can)

**Comment by ppvnf** [comment]
> https://github.com/martinet101/WingetUI/wiki#the-icon-and-screenshots-database
> 
> I have added a basic explanation (i'll improve it when i can)

@martinet101 Is it okay to use https://postimages.org/?

Also, why packages from the extra bucket aren't on the list?

**Comment by martinet101** [comment]
That claim to not expire.

About the extras bucket, I'll add it soon, but I want to finish polishing some stuff before
