### ISSUE TITLE
[BUG/ISSUE] Website instead of homepage

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#358]
![Captura de tela 2022-10-29 084953](https://user-images.githubusercontent.com/73800734/198855918-91f91860-fb1e-4248-a313-9de046715f72.png)
![Captura de tela 2022-10-29 083827](https://user-images.githubusercontent.com/73800734/198855919-add23448-ae1c-4c75-942c-04ea9d979ca9.png)
![Captura de tela 2022-10-29 202558](https://user-images.githubusercontent.com/73800734/198856099-14aae7f6-3a60-434a-92b2-d6223e84b58e.png)

In Portuguese website makes more sense than homepage. I've also changed it in English. What's your opinion?

Or personal website/personal web page?

**Comment by martinet101** [comment]
Yes, I totally agree.

**Comment by martinet101** [comment]
Then I can close this as fixed, right?

**Comment by ppvnf** [comment]
sure!
