### ISSUE TITLE
[BUG/ISSUE] Menu shouldn't continue selected if closed

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#359]
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**

</b>

## Describe the bug
The ... menu shouldn't be selected if you click away from it. I believe the current section title should automatically be selected when the ... menu is closed (except if you click in another section title)

## To Reproduce
1. Go to any section
2. Click on the .... menu
3. Close the menu (by clicking elsewhere)
4. Menu will continue selected

## Screenshots

![Captura de tela 2022-10-29 204141](https://user-images.githubusercontent.com/73800734/198856470-a84794e5-782b-4a22-b1f2-43219a3479fa.png)
![Captura de tela 2022-10-29 204157](https://user-images.githubusercontent.com/73800734/198856473-b0fb8ddf-f8a6-412d-8aad-e08f76498841.png)
![Captura de tela 2022-10-29 204207](https://user-images.githubusercontent.com/73800734/198856474-dba19f2f-1376-4265-83f0-ba5d77196c91.png)

Obs: I believe the menu should continue selected only when options/logs/about section is open:

![3dotmenushouldbeshown](https://user-images.githubusercontent.com/73800734/199085946-3ee94377-24ee-475d-9a27-180d30c0dc87.png)

**Comment by ppvnf** [comment]
Edit: I've added an observation

**Comment by ppvnf** [comment]
@martinet101 This issue is somewhat useless. I think there's no need to fix it if you believe it's time-consuming/not worth it. Maybe it would be simpler to just unselect the menu if its context menu is closed

**Comment by martinet101** [comment]
I don't know, I'll see if it can be fixed easily

**Comment by martinet101** [comment]
Fixed!
