### ISSUE TITLE
Bug: Application error shows up in the Event Viewer (Python DLL crash)

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#36]
![image](https://user-images.githubusercontent.com/67732686/170881175-3b2e0d72-e73f-4b04-95dc-ba5117231d73.png)

![image](https://user-images.githubusercontent.com/67732686/170881335-80b92902-497a-417a-bc01-9a55dcf690f9.png)

![image](https://user-images.githubusercontent.com/67732686/170881348-59dff7b4-8246-4e44-832e-61aca9096f7b.png)

Something related to the Python DLL crashing.

I'm not noticing it, even if the application performance will surely get improved with time - but there's no visible crashing with the app.

**Comment by martinet101** [comment]
I guess this is more a python bug than any other thing. If the app is not crashing (take note that maybe this was registered as an error but the error got handled and didn't make the program crash), much can't be done about it.

I'm sorry :(
