### ISSUE TITLE
[BUG/ISSUE] The CJK font style is not uniform

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [martinet101/WingetUI#361]
CJK fonts such as Chinese should be sans-serif, not serif
Perhaps you should use Microsoft Yahei(msyh) or Noto sans CJK for Chinese and Japanese
![image](https://user-images.githubusercontent.com/65578116/198864952-e2efb71a-b6f6-444f-a738-524e15c329e4.png)
The normal fallback font of CJK is wrong now:
![image](https://user-images.githubusercontent.com/65578116/198865136-7649ebb2-5e32-4981-a708-49d2f34413d5.png)
msyh.ttc will like as this:
![image](https://user-images.githubusercontent.com/65578116/198865177-53db42af-4dc3-4be0-b165-39e4c2821362.png)
If you don't want to use msyh, you can also use [Noto Sans Hans](https://github.com/googlefonts/noto-cjk) for Chinese even all languages font

**Comment by martinet101** [comment]
Fixed!
