### ISSUE TITLE
[FEATURE REQUEST] Option to disable and set the duration of the "auto-hide bottom" installation progress report.

### ISSUE THREAD

**Issue by Spacellary** [martinet101/WingetUI#364]
### Related to #329:
Now that we have the button to show live output it's more necessary than ever to be able to control the duration of the progress report, since upon completion, it very quickly vanishes and after that you can't access the log of the operation it just performed or open the terminal window again (I know it used to take longer before and was changed, but I'm not asking for a reversion of that change here, I'm asking for a new option as per the title).

## Proposed solutions:
1) **Add options to disable or change the timeout/delay of that behavior**.
    _or_
2) ~~Add a persistent "Terminal/Log" button to the top/toolbar of the window or somewhere else, so you can always open the log window again~~.
   **(mockup image bellow)**
    _or_
3) ~~All of the above if possible~~.
<br>

#### Quick mockup:
![mockup2-wingetui-log](https://user-images.githubusercontent.com/39604793/198875721-a1ed5f1e-31c4-452f-bf63-cb411385f87b.png)

**Comment by martinet101** [comment]
The log is independent for each install, so option 1 will be implemented

**Comment by Spacellary** [comment]
> The log is independent for each install, so option 1 will be implemented

In case of **option 1** would be possible to also set a max number of entries in the progress report queue as to cull older entries and make room for the newer ones if the user is performing many operations?

If there's already a feature in place to mitigate that as of right now than just implementing **option 1** as proposed should be enough.

Thanks in advance and sorry for requesting so many features in against any more pressing concerns!

**Comment by martinet101** [comment]
Done!

**Comment by Spacellary** [comment]
❤️
