### ISSUE TITLE
[FEATURE REQUEST] I've modified the Wiki

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#366]
I've added this phrase in order to prevent another situation like https://github.com/martinet101/WingetUI/pull/365:

⚠️ Please, do not create a pull request — follow the instructions below, it's quite easy to translate using Tolgee!

I've thought about adding it to the readme instead of the Wiki, but I will let you choose

Just for awareness, you may close this issue

**Comment by martinet101** [comment]
Thanks!
