### ISSUE TITLE
[BUG/ISSUE] bundled vcredist is out of date

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#371]
Bundled Vcredist 2015+ isn't the latest version. Latest one according to Winget installer is:
https://download.visualstudio.microsoft.com/download/pr/a16e1596-7fef-4570-8d63-fb9d4e72c820/D0CAFF8097BB9C43A3685686826867506BF6EDD667F7B90092CB0EB1B964A85E/VC_redist.x64.exe
and
https://download.visualstudio.microsoft.com/download/pr/a16e1596-7fef-4570-8d63-fb9d4e72c820/BB66E74A41ECF5DC09487608E477ACC4F78A38A0EC4FFE3100069C8A067DA29A/VC_redist.x86.exe
Context: after a fresh install, WingetUI detects an update for Vcredist 2015+
![Captura de tela 2022-10-31 130821](https://user-images.githubusercontent.com/73800734/199054940-8dbb6ae3-c1a6-4bbf-b564-de2bc9abc6e8.png)

**Comment by martinet101** [comment]
Thanks!

The file will ship with the next updates!
