### ISSUE TITLE
[BUG/ISSUE] This option is unavailable after 1.5 update

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#372]
It's not possible to enable/disable this option (scoop cleaning up on startup), even if Scoop is enabled:

![shouldn't be disabled](https://user-images.githubusercontent.com/73800734/199081809-a4de5224-2af7-4427-b8c9-ad8a23004c9e.png)

**Comment by martinet101** [comment]
You need to have enabled index updating on launch in order to be able to enable that function

**Comment by ppvnf** [comment]
> You need to have enabled index updating on launch in order to be able to enable that function

I don't understand why index updating has to disable it to use the scoop cleaning option

**Comment by martinet101** [comment]
Yes, now I realise that it doesn't make sense, but on older versions it would be enabled but do nothing inf the option `update indexes on launch` was disabled
