### ISSUE TITLE
[BUG/ISSUE] deleting .wingetui folder will generate random entries if Scoop wasn't installed

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#373]
I was testing what would happen if you clean install Windows 10 and install WingetUI without Scoop. Then, for some reason, like troubleshooting, you decide to delete the .wingetui folder. The result is the following false entries:

![winget](https://user-images.githubusercontent.com/73800734/199112672-001bfa1b-03a4-48d2-b8d0-bfbe821ad220.png)

and (not really important):

![Captura de tela 2022-10-31 112749](https://user-images.githubusercontent.com/73800734/199041600-1a07c99f-eefe-4789-9014-c26acd37270c.png)

This problem might seem irrelevant, but maybe it isn't because it impacts https://github.com/martinet101/WingetUI/issues/190.

Interestingly the entries are almost the same as of https://github.com/martinet101/WingetUI/issues/370, but I did not change the ExecutionPolicy in this case.

**Comment by martinet101** [comment]
Thus bug is caused because, when deleting that folder, you are deleting the setting that disables scoop

**Comment by martinet101** [comment]
This will be fixed with the reset WingetUI setting

**Comment by ppvnf** [comment]
> This will be fixed with the reset WingetUI setting
