### ISSUE TITLE
[FEATURE REQUEST] Remove update all/export all from toolbar

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#375]
Now that there's an option to select all/none I don't understand why the update all/export all options are still present:

![Captura de tela 2022-10-31 194512](https://user-images.githubusercontent.com/73800734/199124546-7f25ce3a-db78-400c-82f3-50379ba90652.png)
![Captura de tela 2022-10-31 194744](https://user-images.githubusercontent.com/73800734/199124549-233e182a-01c3-4f7d-a200-4abe313545d2.png)
![Captura de tela 2022-10-31 194458](https://user-images.githubusercontent.com/73800734/199124551-0c6eb3ca-1da7-4386-ba15-8783c6afd986.png)

**Comment by martinet101** [comment]
Export all maybe not, but I find the update all button a useful shortcut

**Comment by ppvnf** [comment]
> Export all maybe not, but I find the update all button a useful shortcut

Packages are selected by default, so Update Selected by default will update every package. In fact, the reason I am asking this is because I accidentally clicked Update All instead of Update Selected once... Anyway, how about moving Update All to the end of the toolbar or changing its place with Update Selected instead?
