### ISSUE TITLE
[BUG/ISSUE] (Virus Detected with latest release from GitHub)

### ISSUE THREAD

**Issue by dtiziani** [martinet101/WingetUI#379]
## Describe the bug
I've tried the "Upgrade all" option and it tried to upgrade the wingetui itself together with other packages.
The upgrade of TeamViewer failed due to a hash difference, which I've tried to ignore/skip, all good.
During the upgrade of WinGetUI, there was some dll missing (an error dialog) that seemed to relate to C++ redistributable package.
I've tried to skip, then it failed altogether, so I've proceeded to download the latest release from GitHub (1.5.0)

While downloading, I've got an alert from Chrome (Failure - Virus detected), per the screenshot below (in portuguese, PT-BR):

![image](https://user-images.githubusercontent.com/11280919/199285293-7e661c9d-cc32-40c6-bc0c-2edcfc93af84.png)

This file was retrieved from GitHub Releases page.

I'm running Windows 11 wirth latst packages updated, and the latest Chrome version.

**Comment by dtiziani** [comment]
I've tried everything to download it but Windows keeps removing the file due to a virus.
Tried to check with VirusTotal and no occurrences: https://www.virustotal.com/gui/url/2fb2c96021b524af5d6cf6f3de9c8788b811e925f31b901196bc4b80d3f5d119?nocache=1

But Windows SmartScreen keeps telling me otherwise. Is there any changes that might have caused it?

**Comment by ppvnf** [comment]
Google Chrome/Windows SmartScreen often automatically block new software from relatively unknown publishers. You could try installing WingetUI using Winget or Scoop (see readme). Yesterday I did a test install using MS Edge and I was actually able to bypass SmartScreen with a few clicks. @martinet101 probably can answer if some code change could trigger this behavior, but I am not aware of any

**Comment by t0m5k1** [comment]
How can people trust something that is being consistently reported as malware by the applications supposed to be protecting them.
Can't the creator/contributors contact the the big AV companies, give them the signature and ask them to validate and accept this application as trusted/not malware?

**Comment by martinet101** [comment]
The downloadable installer should not have any virus. 

To make sure that you are not being hacked, please compare the hash of the downloaded file with the one published on the release and with the one in virustotal.

As said by @ppvnf, windows defender often messes things up and unsigned apps like WingetUI get flagged as virus.

**Comment by martinet101** [comment]
This is an issue with the antivirus raising a false-positive

**Comment by ppvnf** [comment]
I've found out [here](https://www.techsupportalert.com/how-to-report-malware-or-false-positives-to-multiple-antivirus-vendors/) that you can submit files to MS [using this website](https://www.microsoft.com/en-us/wdsi/filesubmission). I've no idea how to submit it to Google though.

**Comment by martinet101** [comment]
Yeah, i have done this multiple times, and they just ignore you
