### ISSUE TITLE
[FEATURE REQUEST] Would it possible to show the install progress in the taskbar icon?

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#382]
Example:

Progress bar in WingetUI interface:

![Captura de tela 2022-10-31 200456](https://user-images.githubusercontent.com/73800734/199348294-cf3230de-e69d-4723-96c1-7f864aec132a.png)

Progress bar in the taskbar icon (it can be red or green instead of yellow)

![Captura de tela 2022-10-31 200546](https://user-images.githubusercontent.com/73800734/199348460-8397e180-c2d1-4ae3-bc64-377918dbfeb4.png)

**Comment by martinet101** [comment]
Hi,

Qt6 does not give the ability to do that.

I'll stay tuned for Qt to restore back this feature (it existed in Qt5)

**Comment by EDM115** [comment]
+1, maybe you can check https://github.com/BLumia/qtwinextras ?

**Comment by EDM115** [comment]
@marticliment any update on this ?

**Comment by marticliment** [comment]
sill not compatible with WinUI3
