### ISSUE TITLE
[FEATURE REQUEST] Improve light theme in Windows 10

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#383]
![2](https://user-images.githubusercontent.com/73800734/199353011-12dd6179-09ef-4df3-8c71-a1fa247d35eb.png)
![Captura de tela 2022-10-31 195912](https://user-images.githubusercontent.com/73800734/199353015-1104eee5-f7cd-4b93-a7bc-197219cf5804.png)

1. In the first image, when hovering packages, the one being hovered is indistinguishable from the others 

2. In the second image I selected the first package, but, when holding the mouse over it, the selected package becomes indistinguishable from the others.

Dark theme works as expected on Windows 10 tho.

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/205959768-f72dede1-86b6-4100-b0b2-822ba1890601.png)
Fixed!
