### ISSUE TITLE
[BUG/ISSUE] WingetUI isn't detected by Winget 

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#385]
I used Winget to install WingetUI on Windows 11. I believe this problem happened because WingetUI got installed in Portuguese

![Captura de tela 2022-11-01 210957](https://user-images.githubusercontent.com/73800734/199366541-dfbaa437-dfc2-4444-81c3-235567f4ab8e.png)
![Captura de tela 2022-11-01 211047](https://user-images.githubusercontent.com/73800734/199366553-b65adbed-c1d2-4fb7-8f35-4f8d156217d8.png)

**Comment by martinet101** [comment]
If you install it in English, does it get detected?

**Comment by ppvnf** [comment]
> If you install it in English, does it get detected?

actually no

![Captura de tela 2022-11-02 072958](https://user-images.githubusercontent.com/73800734/199467136-80f09046-6c53-4bd2-a153-9465891314b5.png)

**Comment by martinet101** [comment]
Upgrading from 1.4. does work?

**Comment by ppvnf** [comment]
I believe needs-author-answer tag is no longer needed

**Comment by ppvnf** [comment]
This seems fixed!

**Comment by martinet101** [comment]
no, it is not.

I must change the installer program. bame

**Comment by ppvnf** [comment]
I thought this was fixed by https://github.com/martinet101/WingetUI/commit/0e07410a6d75aebc062e3027b70ddce250dc53ce

**Comment by martinet101** [comment]
No, https://github.com/martinet101/WingetUI/commit/0e07410a6d75aebc062e3027b70ddce250dc53ce fixed issue with WingetUI failing to be updated from itself (cause winget was also running)
