### ISSUE TITLE
[BUG/ISSUE] Clicking show more info toolbar icon doesn't display error message

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#389]
![Captura de tela 2022-11-02 180913](https://user-images.githubusercontent.com/73800734/199603651-d4e7bb8f-e159-4deb-b1be-900b1286d1d6.png)

https://github.com/martinet101/WingetUI/commit/014c9a3e347dba14c41fa5e96f6a4e46f36508de error message is not shown for Local PC packages (nothing happens)

**Comment by martinet101** [comment]
Is there any error shown on the log?

**Comment by ppvnf** [comment]
> Is there any error shown on the log?
> 
> For me the dialog still works

Really? I've tried on both Windows 10 and Windows 11 and I don't get this error message when I click Local PC packages:
![Captura de tela 2022-11-03 135642](https://user-images.githubusercontent.com/73800734/199785723-74b37f45-10f9-43c5-989f-fd32063ef901.png)
It used to work in https://github.com/ppvnf/WingetUI/tree/patch-27

**Comment by ppvnf** [comment]
This seems to be fixed in 1.5.1 beta

**Comment by martinet101** [comment]
I think it might be related with the issues on the admin dialog (that were reported by the error report)
