### ISSUE TITLE
Feature request: Installation error window - General improvements

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#39]
![image](https://user-images.githubusercontent.com/67732686/171703734-a4b86ba5-5e0b-4acc-a3aa-e64e6db38a60.png)

1. At the moment it's very small which makes everything hard to view and read through.

Both a larger window by default and one that can be resized would greatly improve the experience.

2. About viewing it again... one way to do it is, instead of having the resulting button down to the right read 'OK', it could say "Show options", where clicking it brings up a menu where one option is "Close" and the other is "View details".

3. Just noticed that the OK and Details buttons look very different from each other, so that's something.

I guess the buttons themselves in terms of alignment could with either being in the middle, somewhat on opposite ends horizontally, or something like that.

**Comment by martinet101** [comment]
This Message Window is the default one, and as some others, it really needs to be redone.

**Comment by martinet101** [comment]
+ Add the ability to drag main window

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/188263632-1f0e8595-16a8-454c-acdd-8935c901dbbb.png)
Coming...

**Comment by martinet101** [comment]
Done!
