### ISSUE TITLE
[BUG/ISSUE] Number of found packages stays the same after uninstalling

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#392]
Before:

![Captura de tela 2022-11-03 142506](https://user-images.githubusercontent.com/73800734/199792629-e3089093-4d1d-4860-93c1-6e3e0bd56ec4.png)

After:

![Captura de tela 2022-11-03 142538](https://user-images.githubusercontent.com/73800734/199792625-c7334756-1057-450d-ad53-f32169f93b0e.png)

Edit:

The same happens in the update section if you use the uninstall button from the context menu:

![Captura de tela 2022-11-11 203558](https://user-images.githubusercontent.com/73800734/201444482-d263c5d4-fe73-41fa-800a-fee2241d61a7.png)

**Comment by ppvnf** [comment]
the same happens in the update section if you use the uninstall button from the context menu

**Comment by ppvnf** [comment]
I believe it's similar to
https://github.com/martinet101/WingetUI/commit/42c1cbe0ed30f03a2e902fd84f39f5568c911197

**Comment by martinet101** [comment]
Done!
