### ISSUE TITLE
[BUG/ISSUE] Scoop shouldn't stay disabled if installing from Scoop or selecting install Scoop option

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#393]
If you first install WingetUI using the option to disable Scoop; then, for some reason, you decide to reinstall it using the option to enable Scoop, it won't actually be enabled because this option (activated by the first install) will continue checked:

![Captura de tela 2022-11-03 153124](https://user-images.githubusercontent.com/73800734/199806181-39420f5c-9b97-4398-897d-31b9c9930b12.png)

The same would apply if you install WingetUI checking the option to disable Scoop and then you use Scoop to install WingetUI. How about making installing WingetUI through Scoop or checking the option to enable Scoop automatically uncheck the setting that disables Scoop?

**Comment by martinet101** [comment]
This issue has already been fixed, anbd the fix will come with the next release
