### ISSUE TITLE
[BUG/ISSUE] (Enter your description here)

### ISSUE THREAD

**Issue by bropines** [martinet101/WingetUI#395]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**

</b>

## Describe the bug
The application is not built from the code

## To Reproduce
Steps to reproduce the behaviour:
1. Go to 'source code'
2. Open 'build.bat'
3. See error

## Log for cmd
 [LINK TO GISTS](https://gist.githubusercontent.com/bropines/0accbe24876b5b14b826fda32b7c608a/raw/5c340cbb3cbdd9fbeca8486c060c6a9e12401966/error)

## Screenshots
![image](https://user-images.githubusercontent.com/57861007/199933132-c664b750-325a-4361-8e01-0a3eda6292e7.png)

**Comment by martinet101** [comment]
the match structure  is supported only in 3.10 and 3.11
