### ISSUE TITLE
[FEATURE REQUEST] Show Release Notes and Release Notes URL (for Winget packages)

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#396]
## Before submitting the issue

- [X] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**

## Is your feature request related to a problem? Please describe.

`winget show` displays "Release Notes" and "Release Notes URL". I believe this is especially useful when checking for updates. 

## Screenshots:

![Captura de tela 2022-11-04 053935](https://user-images.githubusercontent.com/73800734/199931994-3956178f-05f1-4dfb-ab43-e9a3f6f486b7.png)

![Captura de tela 2022-11-04 060052](https://user-images.githubusercontent.com/73800734/199933758-905d1cef-eefe-4949-ae10-a83f6e9098e6.png)

## Describe the solution you'd like

1. Show Release Notes URL in the update section (maybe also in the discover/uninstall sections)
2. Show Release Notes in the update section (maybe also in the discover/uninstall sections)

**Comment by ppvnf** [comment]
related to https://github.com/martinet101/WingetUI/issues/253

**Comment by ppvnf** [comment]
I believe implementing this is simple and similar to https://github.com/martinet101/WingetUI/commit/48396e02d246d574f538ddd1fc5b6f15d54959d0

**Comment by martinet101** [comment]
Fixed!
