### ISSUE TITLE
[BUG/ISSUE] Untranslated items

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#398]
![Captura de tela 2022-11-04 213903](https://user-images.githubusercontent.com/73800734/200093686-01e1f46c-aecd-402d-a67e-9be9f3c8fa11.png)

**Comment by martinet101** [comment]
Yes, I haven't updated tolgee, I wanted to bulk update it when I have more strings, so translators don't have to translate one or two sentences every day
