### ISSUE TITLE
[Feature request] Specify bucket when installing packages scoop

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#406]
I'm not sure it's possible to do that in the CLI. But maybe there's an install parameter that I'm not aware. For example, I wanted to install Okular from an unofficial bucket (because the official one is out of date). However, `scoop install okular` will install it from the extras bucket, even though the unofficial package is the latest one. Likewise, WingetUI will install the outdated version even if selecting the unofficial package. The only way I know of installing it is using `scoop install ...okular.json` 

![Captura de tela 2022-11-09 091305](https://user-images.githubusercontent.com/73800734/200828314-58af6ed7-25d0-4068-aac0-fa8fc902efc7.png)
![Captura de tela 2022-11-09 091342](https://user-images.githubusercontent.com/73800734/200828316-8225f65c-4afa-4fc1-ba7f-e273dfd88bb9.png)

**Comment by martinet101** [comment]
you'd need to remvove the extras bucket, but ii don't think this can be done programatically

**Comment by ppvnf** [comment]
I guess this is a Scoop problem. It seems there's no equivalent to `--source` from Winget

**Comment by ppvnf** [comment]
I just found out an easier way to do that!
`scoop install bucket_name/package_name`

**Comment by ppvnf** [comment]
> The issue should be fixed, but could you please check on the latest head if this is really the case?

Nope

![Captura de tela 2022-12-06 125736](https://user-images.githubusercontent.com/73800734/205960592-a22330d0-0a7d-45e2-9d90-f5934b17137d.png)

![Captura de tela 2022-12-06 125724](https://user-images.githubusercontent.com/73800734/205960607-ddde2d99-eb95-4ea1-8f69-ee92763bc884.png)

**Comment by ppvnf** [comment]
It works partially.

If you install it double-clicking (with this option enabled) it doesn't work (install from wrong bucket).

However, if you install it through the info menu it actually install from the selected bucket. 

Another thing that isn't working properly is the bucket displayed in the info menu:

![Captura de tela 2022-12-06 125736](https://user-images.githubusercontent.com/73800734/205961911-7bb6a20d-1ce2-4867-9a78-6318500a01e6.png)

![Captura de tela 2022-12-06 125724](https://user-images.githubusercontent.com/73800734/205961880-0492b6b1-dde5-4f81-8fb2-07b8b8d5b2b9.png)

**Comment by martinet101** [comment]
And now?

**Comment by ppvnf** [comment]
The info menu now properly displays the correct bucket, but double-clicking still installs the version from the extras bucket (maybe this is related to https://github.com/martinet101/WingetUI/issues/121#issuecomment-1278176296.

Also, I am no longer able to install through the info menu (I was able before b7a2a6a0e041c2e0e4792397ad8258625634a635). I am getting this error now:

I am getting this error: "Couldn't find manifest for 'joaoricarte_jr-bucket/joaoricarte_jr-bucket/okular'. "

**Comment by martinet101** [comment]
Could you please send me the custom bucket you are using please?

**Comment by ppvnf** [comment]
scoop bucket add jr-bucket https://github.com/joaoricarte/jr-bucket

**Comment by martinet101** [comment]
It works now for me, can you please check?

**Comment by ppvnf** [comment]
There's only one problem remaining:

- [ ] double-clicking still installs the version from the extras bucket (maybe this is related to https://github.com/martinet101/WingetUI/issues/121#issuecomment-1278176296).

- [X] The info menu now properly displays the correct bucket information

- [X] I am not able to install through the info menu

**Comment by martinet101** [comment]
The missing one should now be working

**Comment by ppvnf** [comment]
> The missing one should now be working

Nope:
![Captura de tela 2022-12-06 151000](https://user-images.githubusercontent.com/73800734/205989103-0888284f-4aa7-4cc0-be36-171ceb287919.png)

**Comment by martinet101** [comment]
Sorry, i didn't publish the commit😅
