### ISSUE TITLE
[BUG/ISSUE] Screenshot scrolling isn't working properly if image height is big

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#407]
it isn't be possible to fully see the screenshot if the image height is big

![Captura de tela 2022-11-09 093503](https://user-images.githubusercontent.com/73800734/200832008-2209a30e-8cb8-49fd-8739-a693f9e936b6.png)
![Captura de tela 2022-11-09 093445](https://user-images.githubusercontent.com/73800734/200832011-74916d95-5db0-4034-a582-7483e941f5d8.png)

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/209402722-71dcbd51-858b-409d-aa08-e54b29d0ebbe.png)
The screenshot viewer is now better in every way.
