### ISSUE TITLE
[FEATURE REQUEST] Background Download

### ISSUE THREAD

**Issue by t0m5k1** [martinet101/WingetUI#411]
## Background Download

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**

I Noticed that when installing updates to applications the others are sat there waiting, is it not possible to have wingetui download the other updates in the background as this would speed up the time it takes to complete upgrades.

**Comment by martinet101** [comment]
You can, but it might cause issues:
![image](https://user-images.githubusercontent.com/53119851/201496731-54f36d20-758a-47fb-ae86-3467e79dc8d2.png)
