### ISSUE TITLE
Failed in attempting to update the source: winget

### ISSUE THREAD

**Issue by Dhowti** [martinet101/WingetUI#413]
Hi. The source is not updated within a week from the moment the application is installed. 
Winget source update in command line works ok. What's wrong? Log attached.
[WingetUI_log.txt](https://github.com/martinet101/WingetUI/files/9996313/WingetUI_log.txt)

**Comment by Dhowti** [comment]
Oops, running with administrative privileges solves the problem. But that's not right, is it?

**Comment by martinet101** [comment]
No, this shouldn't happen. 

Running winget update does work on non-administrative installs?

**Comment by Dhowti** [comment]
I'm sorry, I didn't understand you. "Winget source update" in the terminal with the rights of the simple user? It works.

**Comment by martinet101** [comment]
And do the sources get updated? I mean, winget works as expected?

**Comment by Dhowti** [comment]
Well, it seems so. Application updates appear every 1-3 days and are updated by Winget-AutoUpdate. But I was thinking of switching to your app.

**Comment by martinet101** [comment]
Can you please share your WingetUI log? You can find it on the Three dots menu -> WingetUI log

**Comment by Dhowti** [comment]
Now there is no source error in it. I consider it after running once as admin. The log with error is in the first message. Attaching new one.
[WingetUI_log.txt](https://github.com/martinet101/WingetUI/files/9997060/WingetUI_log.txt)

**Comment by martinet101** [comment]
With normal rights, what happens if you run:
 `C:\Users\ЕЕ\AppData\Local\Programs\WingetUI\winget-cli\winget.exe update`
 `C:\Users\ЕЕ\AppData\Local\Programs\WingetUI\winget-cli\winget.exe search ""`

**Comment by Dhowti** [comment]
> C:\Users\ЕЕ\AppData\Local\Programs\WingetUI\winget-cli\winget.exe update

Help screen. Maybe, you mean winget source update? Then

PS C:\Users\ЕЕ\AppData\Local\Programs\WingetUI\winget-cli> C:\Users\ЕЕ\AppData\Local\Programs\WingetUI\winget-cli\winget.exe source update
Updating all sources...
Updating source: msstore...
Done
Updating source: winget...
Cancelled

> C:\Users\ЕЕ\AppData\Local\Programs\WingetUI\winget-cli\winget.exe search ""

Large list of applications

**Comment by martinet101** [comment]
The next update will include a button to reset scoop sources. 

Please wait until then (it's coming very soon) and give it a try

**Comment by Dhowti** [comment]
Hi,

Yes, it works. But resetting sources installs Scoop, which was not installed :)

**Comment by martinet101** [comment]
Huh, my wrong. 

Gotta fix that

**Comment by martinet101** [comment]
You can just disable it again.

It got just enabled, it is not actually installed

**Comment by martinet101** [comment]
Fixed!

**Comment by Dhowti** [comment]
After all, the problem with subj periodically repeats when running without administrator privileges. Perhaps this is a problem of my particular environment.
