### ISSUE TITLE
[BUG/ISSUE] Scoop packages that need admin privileges should display error message

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#414]
I've tried installing this manifest (https://github.com/Zliced13/MyScoop/blob/master/bucket/everything-toolbar.json):

```
scoop bucket add MyScoop 'https://github.com/Zliced13/MyScoop'
scoop install everything-toolbar
```

If trying to install it without admin privileges, the error message "app requires admin rights" is displayed in PShell, however WingetUI doesn't display any message and shows the install as successful, even though the package wasn't installed

**Comment by martinet101** [comment]
Some approach like the one done with the msi failing installs could be done here

**Comment by martinet101** [comment]
Done!
