### ISSUE TITLE
[BUG/ISSUE] All tabs show zero packages

### ISSUE THREAD

**Issue by jordanlord** [martinet101/WingetUI#421]
## Describe the bug
Installed version 1.5.0 and all tabs are showing zero packages.

## To Reproduce
Steps to reproduce the behaviour:
1. Run WingetUI exe
2. Click on any tab
3. Results are '0'

## Expected behaviour
Winget packages should load in Discover and Installed tabs

## Screenshots
Discover Tab
![image](https://user-images.githubusercontent.com/41759670/202287644-68c6c1ed-c2c7-498d-bbd3-f5725b479a4f.png)

Installed Tab
![image](https://user-images.githubusercontent.com/41759670/202287757-3bfed19f-e364-4ed1-977a-6686613bb1c2.png)

## The Log

![image](https://user-images.githubusercontent.com/41759670/202287899-2b4bb45f-c9fb-4ebd-a27e-c41151e5ba00.png)

## Additional context
I tried installing on the default directory in users and the Program Files directory. Same result.
[no_packages_WingetUI_log.txt](https://github.com/martinet101/WingetUI/files/10025484/no_packages_WingetUI_log.txt)

**Comment by martinet101** [comment]
Hi,

Does your user directory contain non-ascii characters?

Also, could you please try running the following command in an administrator cmd window?

```
"C:\Program Files\WingetUI\winget-cli\winget.exe" source reset --force
```

**Comment by th3guard1an** [comment]
I'm having the same issue, but since I'm using both scoop and winget, only winget packages are unavailable. Using winget on powershell works as per usual. And using wingetUI with scoop is working properly.

**Comment by martinet101** [comment]
@th3guard1an, what is your user directory path?

**Comment by th3guard1an** [comment]
> @th3guard1an, what is your user directory path?

"C:\Users\jpedr\AppData\Local\Programs\WingetUI\sudo"

**Comment by jordanlord** [comment]
> 

"C:\Users\tojor\AppData\Local\Programs\WingetUI"

**Comment by th3guard1an** [comment]
> > @th3guard1an, what is your user directory path?
> 
> "C:\Users\jpedr\AppData\Local\Programs\WingetUI\sudo"
Resintalling didn't work, but running "C:\Users\jpedr\AppData\Local\Programs\WingetUI\winget-cli\winget.exe source reset --force" solved the issue.

**Comment by martinet101** [comment]
Nice, then we can close this issue, since it has been fixed and is a winget issue, not a WingetUI one.
