### ISSUE TITLE
Better solution about screenshots and icons

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [martinet101/WingetUI#426]
We can display the corresponding screenshot and icon content by referencing the wikipedia's image resources
Thanks to Wikimedia's help and support, these things won't be too difficult.What's missing on the wiki can be added with the old way it's going on now.
Of course, it is also possible (non-commercial) to set up your own wiki site to store this content, such as wingetpackinfo.org

**Comment by martinet101** [comment]
While I could create a new wiki site to upload images, i could never provide reliable and fast server (meaning constant crashes or load errors), so i don't think that would be the best solution. However, services like imgur.com are designed for this specific task, so i guess uploading the images there if thy can't be found in a wiki is the best we can do.
