### ISSUE TITLE
[BUG/ISSUE] Not able to run WingetUI with --daemon parameter

### ISSUE THREAD

**Issue by reaseno** [martinet101/WingetUI#431]
I tried to create my own autostart for WingetUI to start with admin rights. For this I added the --daemon parameter to the normal path as WingetUI would create it itself in the registry:
"C:\Users\USER\AppData\Local\Programs\WingetUI\WingetUI.exe" --daemon

But unfortunately WingetUI does not start with this. What am I doing wrong?

**Comment by martinet101** [comment]
It should work...

Note that registry often needs weird keys for the parameters to work. Have you tried creating a shortcut in the starup apps folder?

**Comment by reaseno** [comment]
The shortcut and the command alone does not even work. What is the command to launch WingetUI in the tray if not as I specified?

**Comment by martinet101** [comment]
They did work for me...

Doesn't appear a icon tray seconds after being launched?

Where have wingetui installed?

**Comment by reaseno** [comment]
Yes, no tray icon. The path is:
C:\User\USER\AppData\Local\Programs\WingetUI\WingetUI.exe.

When I start it this way via cmd, it starts normally. But nothing happens when I append the --daemon parameter.

**Comment by reaseno** [comment]
I have disabled WingetUI startup, because I have no admin rights in WingetUI as described in the opening post, which leads to the bug #206. That's why I wanted to create a custom startup shortcut where you can set startup with admin rights.

**Comment by martinet101** [comment]
Then please disable auto startup from the task manager, enable launch on system startup and, through Task Scheduler, create a task that runs installpath/wingetui.exe --daemon with adminstrator rights on log on of your user

**Comment by reaseno** [comment]
Also in the task scheduling nothing happens after manual execution if the --daemon parameter is used. As soon as you omit it WingetUI starts. I'm also not sure how this would work if the command with parameter in the command line already has no reaction.

Can you run it in the command target with installpath/wingetui.exe --daemon then?

**Comment by martinet101** [comment]
Yeah, but you need to enable the start on launch from the WingetUI Settings. If not, WingetUI will immmediately quit

**Comment by reaseno** [comment]
Oh, it must be enabled in WingetUI Settings for the parameter to work. That was the information I was missing. Could this be allowed in general in the future without the setting?

**Comment by reaseno** [comment]
I have no problem with the WingetUI setting. Only that the parameter does not always work. I also can't understand why you should make the paramenter dependent on the WingetUI setting. I don't know this from any other program that supports start parameters to start this e.g. in the tray.
