### ISSUE TITLE
Scoop installed but not working.

### ISSUE THREAD

**Issue by brimwats** [martinet101/WingetUI#433]
I followed the instructions here https://github.com/martinet101/WingetUI/issues/104 and noted the bits that talked about how it was resolved in 1.4. So I installed 1.5 and it was still not detecting scoop and including these weird packages
![image](https://user-images.githubusercontent.com/73113656/203207705-9f38cb47-7d91-4a39-8b5e-d14dc9b3d58e.png)

i tried to reinstall scoop via winget 1.5 installation but it did not work. I went into settings and I tried it there and get
```
This script will install Scoop and the dependencies required by WingetUI.
Press any key to continue . . .
Installing scoop...                                                                                                     Initializing...                                                                                                         Downloading...                                                                                                          Extracting...                                                                                                           Creating shim...
Scoop was installed successfully!
Type 'scoop help' for instructions.
Installing git...
scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ scoop install git
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Done!
Press any key to continue . . .


```

**Comment by brimwats** [comment]
I then did this         I got rid of the scoop error by running
[irm get.scoop.sh | iex](url)

but I still can't click any options in About WingetUI

_Originally posted by @JonathanPitre in https://github.com/martinet101/WingetUI/issues/138#issuecomment-1263715526_
      

but now 
```
PS C:\Windows\System32> scoop help
scoop: The term 'scoop' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Windows\System32> irm get.scoop.sh | iex
Initializing...
Downloading...
Extracting...
Creating shim...
Scoop was installed successfully!
Type 'scoop help' for instructions.
PS C:\Windows\System32> scoop .\hal.dll
scoop: The term 'scoop' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Windows\System32> scoop help
scoop: The term 'scoop' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Windows\System32>
```

**Comment by brimwats** [comment]
Scoop is in both my system and user environ variables

**Comment by martinet101** [comment]
Then, please try:
1. restart your system
2. Run the "install scoop" opton afain after restarting. This willl have forced an environment variable reload

**Comment by brimwats** [comment]
> Then, please try:
> 
> 1. restart your system
> 2. Run the "install scoop" opton afain after restarting. This willl have forced an environment variable reload

https://github.com/martinet101/WingetUI/issues/433#issuecomment-1323393915

**Comment by martinet101** [comment]
You seem to have a broken scoop installation. Could you please reset scoop (deleting the scoop folder placed in your user directory)

**Comment by brimwats** [comment]
this finally worked. thanks for all the help!

**Comment by elliotl1l** [comment]
I also encountered this problem (version 3.0.1), what worked for me is to run wingetui as administrator.
