### ISSUE TITLE
wiki vandalism

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#438]
I've already reverted it. Maybe there's a bot changing the links of Wiki pages on Github...

https://github.com/martinet101/WingetUI/wiki/Home/_compare/ece6760cb1343674f3ec3f6ce65e10fcb6022240...32a32b26584df55d043aa6b0ba8c1c4daca88fea

**Comment by martinet101** [comment]
Probably yes. 

I'm gonna lock the wiki for the time being.
