### ISSUE TITLE
Change update check frequency ----- (done Tray application and autoupdater)

### ISSUE THREAD

**Issue by sitiom** [martinet101/WingetUI#44]
It seems like you already have a tray icon, albeit non-functioning. It would be good to make use of it. Additionally, having WingetUI run in the background and automatically notify and install updates unattended is something I think is essential to most package manager UIs.

See https://github.com/microsoft/winget-cli/issues/212#issuecomment-1052889052
> Here are some references:
> 
> [zkokaja/Brewlet](https://github.com/zkokaja/Brewlet)
>
> > For example, you need to manually check if some of your packages can be updated. With Brewlet it's easy: if everything is working swimmingly, then you'll see the normal shadow  <img src="https://raw.githubusercontent.com/zkokaja/Brewlet/master/images/brewlet-black.svg" width="16px" /> icon. If updates are available to be installed, the icon will become colored, <img src="https://raw.githubusercontent.com/zkokaja/Brewlet/master/images/brewlet-color.svg" width="16px" /> , to get your attention – along with a notification if you wish. Once clicked, you'll be able to upgrade your packages, among other options. In addition, Brewlet will periodically check the status of packages in the background, so you don't have to.
> 
> ![Brewlet](https://raw.githubusercontent.com/zkokaja/Brewlet/master/images/statusmenu-update.png)
> 
> [cokelid/ChocoButler](https://github.com/cokelid/ChocoButler)
> ![ChocoButler](https://raw.githubusercontent.com/cokelid/ChocoButler/main/img/screenshot-02-tooltip.png) ![ChocoButler](https://raw.githubusercontent.com/cokelid/ChocoButler/main/img/screenshot-03-menu.png)

**Comment by martinet101** [comment]
Huh, that's hard work, but why not

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/179008624-421b9e56-cd5f-456f-86d0-9a2db63c83e1.png)
Done!

**Comment by sitiom** [comment]
Thanks! When will I be able to try this out?

**Comment by martinet101** [comment]
> Also, this supports Scoop too, right?

Of course (or at least it should)



> Thanks! When will I be able to try this out

With the next release, coming in the next week

**Comment by sitiom** [comment]
Is the auto-updating also implemented? How does it work?

**Comment by martinet101** [comment]
Auto update won't be possible rn since most installers from winget still invade user's window by showing pop-ups and unattended windows. This is a thing i'm still trying to figure out, though

**Comment by sitiom** [comment]
> Auto update won't be possible rn since most installers from winget still invade user's window by showing pop-ups and unattended windows. This is a thing i'm still trying to figure out, though

Really? What matters is that it runs unattended, right?

**Comment by martinet101** [comment]
> What matters is that it runs unattended, right? It's

*silent* installs run without the user noticing, but *unattended* installs, while they not require any kind of user input, they still can prompt for UAC and show annoying progressbars in the foreground, interrupting user activity. That's why, for the moment, this is not going to be a thing (atleast until those get fixed)

**Comment by ppvnf** [comment]
There's this for Winget (https://github.com/Romanitho/Winget-AutoUpdate) and for Scoop you can use the task scheduler

**Comment by sitiom** [comment]
> There's this for Winget ([Romanitho/Winget-AutoUpdate](https://github.com/Romanitho/Winget-AutoUpdate)) and for Scoop you can use the task scheduler

That's **exactly** what I am looking for, except WingetUI is not aware of changes when updated externally (https://github.com/martinet101/WingetUI/issues/82#issuecomment-1185400642)

**Comment by martinet101** [comment]
I have done it in a way that lets you know that there are updates for an app by thropwing a notification. The apps can be simply updated from the context menu or from the app itself
![image](https://user-images.githubusercontent.com/53119851/188401278-d05cd263-c54f-42a9-9f6e-fd634116438b.png)

**Comment by sitiom** [comment]
Good enough for me, what is the interval for update checking?

**Comment by martinet101** [comment]
For the moment is 1h.

You'll be inly notified if any updates were found

**Comment by sitiom** [comment]
> For the moment is 1h.

It would also be good to be able to configure the interval.

**Comment by martinet101** [comment]
Yes, this is a pending thing, though it might not come with 1.3, since 1.3 should come today or tomorrow and i want to finish other things that require to be polished

**Comment by martinet101** [comment]
Done!
