### ISSUE TITLE
[BUG/ISSUE] Installing nerd fonts throws an error

### ISSUE THREAD

**Issue by maicol07** [martinet101/WingetUI#443]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**

</b>

## Describe the bug
When installing a nerd font package from scoop it doesn't install and instead throws an error:
```Currently, on Windows 11 Version 22H2 (OS Build 22621) or later,  Font installation only works when installing font for all users. 
Please use following commands to install 'CodeNewRoman-NF' Font for all users. scoop install sudo 
sudo scoop install -g CodeNewRoman-NF
 See https://github.com/matthewjberger/scoop-nerd-fonts/issues/198 for more details.
```

This is thrown in normal and administrator install mode.

## To Reproduce
1.  Add the nerdfonts bucket to scoop from WinGetUI options
2. Search a nerd font (i.e. CodeNewRoman) in the discover software section
3. Try to install it, either in normal and admin mode
5. See error

## Expected behaviour
Package installs

## The Log

[log.txt](https://github.com/martinet101/WingetUI/files/10113657/log.txt)

**Comment by martinet101** [comment]
I suppose this needs the global scoop feature. 

I'll work on that
