### ISSUE TITLE
[BUG/ISSUE] Systray icon context menu "updates found" shouldn't always be in plural

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#446]
I believe it should show "1 update found", instead of "1 updates found":

![Captura de tela 2022-11-30 081250](https://user-images.githubusercontent.com/73800734/204784311-1c7e388c-a229-4488-b64a-806f642f694a.png)

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/205941513-72028829-f111-4ab5-85cb-ee9a63a2f49a.png)
