### ISSUE TITLE
[FEATURE REQUEST] Improve systray icon context menu

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#447]
How about making it possible to click "Available updates", "Installed packages" and "Version number"? Maybe also add links to Discovery and Settings sections.

![Captura de tela 2022-11-30 081250](https://user-images.githubusercontent.com/73800734/204784842-9962813d-00a5-4acf-98db-f295ca728268.png)

**Comment by martinet101** [comment]
Sounds good

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/205940938-8eade535-9a56-45f7-add3-18e465351ea6.png)

**Comment by ppvnf** [comment]
The positioning is no longer correct on Windows 10:

![Captura de tela 2022-12-06 131740](https://user-images.githubusercontent.com/73800734/205965549-fc514cfa-6b79-477f-840a-03b6f7db27b4.png)

![Captura de tela 2022-12-06 131847](https://user-images.githubusercontent.com/73800734/205965542-3c38a814-be40-4727-8a32-872de633cf60.png)

**Comment by martinet101** [comment]
This has been done in purpose for the menu to int interfiere with the taskbar on W11 (it sometimes shows under the taskbar).

Gonna disablke that behaviour on W10

**Comment by martinet101** [comment]
Could you test now?
