### ISSUE TITLE
[BUG/ISSUE] Unable to install Winget package (No package found matching input criteria)

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#453]
WingetUI fails to install **hluk.CopyQ** and shows _No package found matching input criteria_. 

However, WingetUI successfuly install it as admin.

The terminal command `winget install --id hluk.CopyQ --silent` also works.

Maybe related to https://github.com/martinet101/WingetUI/issues/288

**Comment by ppvnf** [comment]
I've restarted my PC and I can no longer reproduce this somehow...

**Comment by ppvnf** [comment]
I've restarted it again and the error is happening again lol

**Comment by ppvnf** [comment]
This problem also happens with other packages. It seems disabling Scoop makes it work, but enabling it causes the problem again 😕

**Comment by martinet101** [comment]
If it happens again, makje sure to reopen the issue so we can investigate it!

**Comment by ppvnf** [comment]
By the way, I solved this simply by deleting .wingetui folder and reinstalling WingetUI
