### ISSUE TITLE
bug with visual screen

### ISSUE THREAD

**Issue by pkroeze** [martinet101/WingetUI#46]
This is on a 4K OLED screen on a 15.6 inch laptop. Reducing the resolution to Full HD didn't help. 
This is on Windows 11, that is up-to-date. 
Please let me know if any more information is needed.

![afbeelding](https://user-images.githubusercontent.com/5010813/174437187-504f8e55-c003-4433-9ff5-f50845df8749.png)

**Comment by martinet101** [comment]
Yes, this is a thing being worked on

**Comment by martinet101** [comment]
It should be fixed with the next update
