### ISSUE TITLE
Missing translation indexes

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [martinet101/WingetUI#462]
There is no translation here, but the translation website shows that it has been 100% translated. Please supplement translation items that do not have an index.
（It's not just Chinese other languages that have this problem)
![image](https://user-images.githubusercontent.com/65578116/205470253-d4fb707f-9d30-4e91-a25a-c5370bdefdec.png)
![image](https://user-images.githubusercontent.com/65578116/205470324-9c14e8da-1a3f-4cb3-b0c6-62527518c9d6.png)
Really 100% translated？ No
![image](https://user-images.githubusercontent.com/65578116/205470338-e9f76b4e-cb52-4851-b007-198522db6580.png)

**Comment by martinet101** [comment]
Hi @BUGProtectionAssociation,

Note the following things:

 - Tolgee translation percentage is broken, please check the one in the WingetUI Github page.
- the context menus are the fdefault ones, and they can't be translated (at least for now)
- when updating a translation, it takes some time for it (more or less two days at least) it be updated in the app, meaning that changes on Tolgee are not immediate


I'll check if I can reproduce this issue on my computer, and I'll let you know

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/205515095-c07afcda-fbc0-4639-b77a-94ead1597cea.png)

It shows translated for me, please check on tolgee if the translation is present
