### ISSUE TITLE
[BUG/ISSUE] The version of some Scoop apps fails to load and is shown as "Unknown" on the infobox section

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#466]
Similar to https://github.com/martinet101/WingetUI/issues/307, but for Scoop. Before 1.5.1 this problem affected only Winget packages,  but now a few Scoop packages have a similar problem. Examples:
![Captura de tela 2022-12-06 140711](https://user-images.githubusercontent.com/73800734/205976876-f1cd185b-60c9-4187-b840-a4a9bff349ba.png)
![Captura de tela 2022-12-06 140755](https://user-images.githubusercontent.com/73800734/205976882-5a3335fb-8caa-4eee-8084-f12aab09eb56.png)
![Captura de tela 2022-12-06 140811](https://user-images.githubusercontent.com/73800734/205976885-ff58c516-994e-4d93-bc55-1e7cb076b139.png)
![Captura de tela 2022-12-06 140824](https://user-images.githubusercontent.com/73800734/205976888-3f43cde8-7652-4ac5-a413-c8facab448f0.png)

**Comment by martinet101** [comment]
This sould now be fixed. Could you please test it again on the latest head?

**Comment by ppvnf** [comment]
Yes, thanks!
