### ISSUE TITLE
[QUESTION] Should "and or "or" be used?

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#472]
Which one makes more sense in this phrase?

> Search for packages on Winget and Scoop

I am wondering if "or" is better than and in this case. Alternatively (not sure it is worth tho) WingetUI could detect if Winget and Scoop are enabled and display the message accordingly

**Comment by martinet101** [comment]
Thinking about it, i think ti would look better simpley `search for packages`

**Comment by ppvnf** [comment]
I agree. How do you plan to implement it?

**Comment by martinet101** [comment]
just change the tooltip string for `Search for packages`.

I don't think we understood pourselves properly. You mean the text on this LineEdit, right?
![image](https://user-images.githubusercontent.com/53119851/206293116-37e6d4d6-225f-4475-a1fb-1004e8407676.png)

**Comment by ppvnf** [comment]
yes

**Comment by martinet101** [comment]
Fixed!
