### ISSUE TITLE
Pop up Error message after installing wingetui

### ISSUE THREAD

**Issue by candrapersada** [martinet101/WingetUI#48]
I get error message that api-ms-win-core-path-l1-1-0.dll is missing.

I am still using Scoop in Win7.
Grateful for any assistance, I would love to upgrade and have the latest bug fixes
![174584138-f162dd44-6eb7-48b3-aff0-ed620d6de0a8](https://user-images.githubusercontent.com/36833664/174606864-8eecf657-adfa-4675-a1fd-6cc621475813.png)

**Comment by martinet101** [comment]
Hi, i guess it is normal for WingetUI to crash, it uses Python 3.10 and PySide6, which are not compatiblew anymore with Windows 7 (also, isn't winget incompatible also?)

I'm sorry, but this won't probably work. You can test older versions based on python 3.8, try out version 0.1 or 0.2, but i don't think that will work either. I'm sorry :'(

Best I can say is upgrading to windows 10/11.
