### ISSUE TITLE
The buttons are not clickable on this dialog box

### ISSUE THREAD

**Issue by rp1231** [martinet101/WingetUI#483]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [ ] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**

</b>

## Describe the bug
The buttons don't work on this dialog box and the only way to close it is via alt f4.
It only shows the resize cursor instead of the normal cursor.

<img width="338" alt="wingetui_sD94pHywR8" src="https://user-images.githubusercontent.com/47380919/206903153-454ad689-0ba7-4759-b56c-8bd22621bf75.png">

## To Reproduce
When an installation fails

## Expected behaviour
Buttons should work

**Comment by martinet101** [comment]
Could you please set WingetUI to dark mode and see if that helps?

**Comment by martinet101** [comment]
> in fact the standard minimize, maximize and close buttons don't show up in the dark mode dialog box

this is actually expected


could you please try (if you have python knowledge) the latest head? Thanks!

**Comment by martinet101** [comment]
oh, no worries then. I'll further investigate and provide you with some test builds

**Comment by meizenga** [comment]
Same here. Cannot click on neither boxes and the mouse changes to resize.
Alt-F4 only way to close the window.

- I have checked that the bug is not a duplicate or, if it is, it needs to be reopened
- I have checked that I am running the latest version of WingetUI
- I have tried resetting and reinstalling WingetUI and the issue persisted or happened again
- I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions

**Comment by martinet101** [comment]
Which version of W10/W11 are you running?

**Comment by DarkEcho3s** [comment]
I am experiencing the same issue. Running Windows 11 22H2 build 22621.963

**Comment by martinet101** [comment]
Can you guys please test this build: 
https://drive.google.com/file/d/16ubEUe0ZqCEYx3R4Xr0XKU4pec-FCCS4/view?usp=sharing

**Comment by martinet101** [comment]
Perfetc then, please stick with this dev build until the next release comes out!

**Comment by DarkEcho3s** [comment]
That fixed the issue for me as well.
