### ISSUE TITLE
WingetUI-Updater.exe throws AV false positive

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#49]
In my case Kaspersky.

![image](https://user-images.githubusercontent.com/67732686/175054298-6a12a715-7885-427c-8ffe-d6df7f0b8ccd.png)

**Comment by martinet101** [comment]
Mhmm, that has to be PyInstaller's fault. Let me check that

**Comment by martinet101** [comment]
Virustotal result for the installer: 
https://www.virustotal.com/gui/file/4537d92ebf0968823984b8acad9dcd62f8b692fc2f1b08c02807ce840db02ad1?nocache=1

Virustotal result for the executable: https://www.virustotal.com/gui/file/f11026d3ff3a718e7d0a14553ae4377a3759b1102069bdd37b56af6c40f52eba?nocache=1

Best I can say is to whitelist wingetUI.

**Comment by SkebbZ** [comment]
This happened to me today with ESET.

**Comment by marticliment** [comment]
@SkebbZ,

which AV are you using?

**Comment by SkebbZ** [comment]
> @SkebbZ,
> 
> which AV are you using?

ESET

**Comment by marticliment** [comment]
please analyze the file with virus total

**Comment by SkebbZ** [comment]
I've tried, but the AV deletes it instantly before I can even touch it. I've reported it to them as a possible false positive though.

**Comment by marticliment** [comment]
Try disabling the AV before doaanloading wingetui, then pass it though virustotal

**Comment by SkebbZ** [comment]
[](https://www.virustotal.com/gui/file/4e0e08409c46335896ca9b9532589eba7177504fb741185bf39a256199eae9a8/detection)
