### ISSUE TITLE
[BUG] Cannot install scoop git

### ISSUE THREAD

**Issue by panther7** [martinet101/WingetUI#495]
Probably need reload powershell/cmd enviroment (or restart app)

![2022-12-14 14 15 48](https://user-images.githubusercontent.com/3808250/207612906-bbd24293-0db2-41f1-965e-63e19a7019a4.png)

**Comment by martinet101** [comment]
This issue should be now fixed!

**Comment by panther7** [comment]
Maybe need restart app, or restart "detect" Scoop, if you install/uninstall Scoop.

Because in "About screen" is not refreshed information and "package list" is not refreshed.

**Comment by martinet101** [comment]
Yes, WingetUI won't detect scoop until the next restart.
But the script shouldn't fail anymore when installing git.

I'm going to force-restart wingetui after the execution of the script

**Comment by martinet101** [comment]
Done!

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/208185552-279b7588-291b-4402-af2d-ad6328c84d86.png)
