### ISSUE TITLE
doesn't install

### ISSUE THREAD

**Issue by aqtsalt** [martinet101/WinGetUI#5]
I get a message and notification saying it was installed correctly but nothing actually installed
it installs on regular winget cli

example programs I tried: 
CDS.AladinDesktop
AdrienAllard.FileConverter
Armin2208.WindowsAutoNightMode

**Comment by martinet101** [comment]
Yes, the CLI is quitr broken, but since winget integrations are 💩, it is difficult to fix that. However, i'll try to fix that

**Comment by martinet101** [comment]
Upgrade to version 1.0 to get this new feature
