### ISSUE TITLE
[BUG/ISSUE] WingetUI doesn't recognize dotnet desktop runtime 3.1 source as being from Winget

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#501]
This is what I get if I run the list command:

![Captura de tela 2022-12-16 094922](https://user-images.githubusercontent.com/73800734/208101881-baa12c3d-cb1a-4c50-ad9d-8a24227ee890.png)

WingetUI for some reason doesn't recognize dotnet desktop runtime 3.1 (x86 and x64) sources as being from Winget (maybe it's because of the underline): 

![Captura de tela 2022-12-16 095540](https://user-images.githubusercontent.com/73800734/208103247-9695d09c-b5b0-4a3c-8e36-9a9e4d2912d1.png)

**Comment by martinet101** [comment]
fixed!
