### ISSUE TITLE
[FEATURE REQUEST] Identify MSStore packages on the install section

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#502]
I know Winget-CLI ability to identify source as MSStore is broken, however I believe there's a relatively simple way this can be achieved by WingetUI. This is because MSStore packages end with an underscore and exactly 13 characters after it. For example:

JAMSoftware.TreeSizeFreePrivate_37s2tpab2h9zg
8bitSolutionsLLC.bitwardendesktop_h4e712dmw3xyy

**Comment by martinet101** [comment]
Oh, you mean like treating them as winget packages (showing info, etc.)?

**Comment by ppvnf** [comment]
> Oh, you mean like treating them as winget packages (showing info, etc.)?

That would be nice, but I was only thinking about them having a different icon from Local PC and regular Winget so I could easily differentiate the source

**Comment by ppvnf** [comment]
I think https://github.com/martinet101/WingetUI/commit/2d61f53f17fa4f9cf12be7490ead92a06d0b692f made MSStore packages appear as Winget ones, but I don't think Winget is able to display info about them (because it's not available). 

Icon suggestion to differentiate MSStore from Winget source:

<details>

<img src="https://user-images.githubusercontent.com/73800734/208439863-0fcc2def-1c37-43d2-978f-d705af63bdbc.png">
</details>

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/208488118-b3855d64-25ae-43d1-b6fd-3cb11d093ed2.png)

**Comment by ppvnf** [comment]
I appreciate your attempt, but it's not working properly.

1. This package for some reason is misidentified as being from MSStore (it's from Winget actually). I believe the reason is the hyphen:
![Captura de tela 2022-12-19 161229](https://user-images.githubusercontent.com/73800734/208501868-65992a56-962e-4814-82e2-77b415e8340c.png)

2. These ones are working fine:
![Captura de tela 2022-12-19 162727](https://user-images.githubusercontent.com/73800734/208504447-a8f10567-0c95-44a4-87d3-d156de606b1e.png)

3. Several packages that are actually from MSStore appear as Winget packages (I believe the reason is the ellipsis):

![Captura de tela 2022-12-19 162853](https://user-images.githubusercontent.com/73800734/208504756-3344f232-a292-4871-887c-9b995440f3b1.png)

**Comment by martinet101** [comment]
Regarding the ellipsis, this is the same issue as always. Microsoft messing up, and much can't be done about it.

**Comment by ppvnf** [comment]
The problem isn't the ellipsis itself, but because of it 16 out of 19 MSStore packages are wrongly identified as Winget pkgs. Only 3 are correctly identified as being from MSStore. Is there a way to ignore the ellipsis only during the source check?

**Comment by martinet101** [comment]
I mean, i could omit it, but the 13-character id wouldn't be 13 characters long.

**Comment by martinet101** [comment]
However, i could actually fix that

**Comment by ppvnf** [comment]
Thanks for fixing Micrisoft's problems ahead of time! I don't know if you have a better idea, but I've noticed that packages with _ that have ... are from MSStore. The only exceptions are packages that have { (but they aren't detected as Winget, so it's probably not a problem)

![Captura de tela 2022-12-19 182530](https://user-images.githubusercontent.com/73800734/208527166-f8a311ed-2f78-4c8b-8d91-c673d2ecf419.png)

**Comment by martinet101** [comment]
It should be now working

**Comment by ppvnf** [comment]
Thanks!
