### ISSUE TITLE
[BUG] Deselect all changing sort in "Update tab"

### ISSUE THREAD

**Issue by panther7** [martinet101/WingetUI#506]
![c](https://user-images.githubusercontent.com/3808250/208240117-b7aef053-56b4-46f5-ac36-1028b300a3f4.gif)

**Comment by martinet101** [comment]
this happens only when sorting by the checkbox status.

gonna fix that

**Comment by martinet101** [comment]
Done!

**Comment by ppvnf** [comment]
I think the package list by default should be arranged by name instead of by selection. It's weird seeing the packages being rearranged when you select/unselect them:

https://user-images.githubusercontent.com/73800734/209407613-ccaf1be8-773a-4bf8-af62-3a339841b48c.mp4

**Comment by martinet101** [comment]
Yes, I agree
