### ISSUE TITLE
[Bug] v1.5.2-beta introduce the broken package name cuts again

### ISSUE THREAD

**Issue by Dragon1573** [martinet101/WingetUI#515]
## Summary

![output](https://user-images.githubusercontent.com/49941141/208820916-6abd1e51-4395-4f28-b890-34b63d4ca06f.gif)

The beta build `v1.5.2-beta` break the package name detection again. 

_Originally posted by @Dragon1573 in https://github.com/martinet101/WingetUI/issues/456#issuecomment-1360843602_

**Comment by martinet101** [comment]
Could you please test the latest head?

**Comment by Dragon1573** [comment]
> Could you please test the latest head?

Excuse me. Cloud you please explain "test the latest head" means? Should I clone the whole project and run `build.bat` to build a target on my own and test it?

**Comment by martinet101** [comment]
oh, sorry

latest heads mean the latest commit. to do this, you need to clone the repository again or pull the latest changes with the git pull command, and then navigate to wingetui/ and double click the file called __init__.py . (please quit any running instances of WingetUI before from the system tray) Then WingetUI should start, and you'll have the latest commits

**Comment by Dragon1573** [comment]
## Test procedure

1. Enable **Windows Sandbox** feature on Windows (this may need Professional Edition).
2. Download everything in `Tools/` folder in [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs).
3. Open Powershell and launch `Tools/SandboxTest.ps1`, a fresh Windows Sandbox instance will startup and automatically install `winget.exe` for you.
4. Use `winget.exe` to install `Git.Git` and `Python.Python.3.10`.
5. Switch `pip` from official PyPI index to a mirror hosted by [Beijing Foreign Studies University](https://mirror.bfsu.edu.cn/pypi/web/simple) for requirements installation speed up.
6. Follow the instruction of [Wiki](https://github.com/martinet101/WingetUI/wiki#running-and-building-the-source-code) to run the source code directly.

## Test result

1. Icons are missing.
2. Package name extraction are still broken.

![image](https://user-images.githubusercontent.com/49941141/209433801-4fb0ef2d-829c-4197-b8c7-e984a2de90e1.png)

3. Interactive with buttons are OK.

![image](https://user-images.githubusercontent.com/49941141/209434153-7b2f7ac1-afeb-443b-ab93-be7e2066c55c.png)

<details>
<summary>Logs from Powershell</summary>

```text
🟢 Total packages: 3
🟡 Package + found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\Users\WDAGUtilityAccount\Desktop\WingetUI\wingetui\scoopHelpers.py", line 88, in searchForUpdates
    signal.emit(element.split(" ")[0].strip() if lc else element.split(" ")[0].strip().capitalize(), f"{element.split(' ')[0].strip()}", list(filter(None, element.split(" ")))[1].strip(), list(filter(None, element.split(" ")))[2].strip(), f"Scoop")

🔴   File "C:\Users\WDAGUtilityAccount\Desktop\WingetUI\wingetui\scoopHelpers.py", line 88, in searchForUpdates
    signal.emit(element.split(" ")[0].strip() if lc else element.split(" ")[0].strip().capitalize(), f"{element.split(' ')[0].strip()}", list(filter(None, element.split(" ")))[1].strip(), list(filter(None, element.split(" ")))[2].strip(), f"Scoop")

🔴 IndexError: list index out of range

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🟢 Scoop search finished
🟡 Package + found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟡 Package + found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 3
IndexError: list index out of range
🟢 Scoop search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 4
🔵 Version URL: http://www.somepythonthings.tk/versions/wingetui.ver
🟢 Updates not found
🟢 Searching for string ""
🟢 Searching for string ""
```

</details>


4. Unable to restart WingetUI after changing some configurations in "Settings" page.

<details>
<summary>Error logs from Powershell (maybe tructated)</summary>

```text
rces/install_scoop.cmd"))))
FileNotFoundError: [WinError 2] The system cannot find the file specified: '.\\resources/install_scoop.cmd'
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\WingetUI\wingetui\uiSections.py", line 2299, in <lambda>
    button.clicked.connect(lambda: (setSettings("DisableScoop", False), disableScoop.setChecked(False), os.startfile(os.path.join(realpath, "resources/install_scoop.cmd"))))
FileNotFoundError: [WinError 2] The system cannot find the file specified: '.\\resources/install_scoop.cmd'
ua
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\WingetUI\wingetui\uiSections.py", line 2129, in changeLang
    setSettingsValue("PreferredLanguage", selectedLang, r=False)
TypeError: setSettingsValue() got an unexpected keyword argument 'r'
tr
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\WingetUI\wingetui\uiSections.py", line 2129, in changeLang
    setSettingsValue("PreferredLanguage", selectedLang, r=False)
TypeError: setSettingsValue() got an unexpected keyword argument 'r'
sr
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\WingetUI\wingetui\uiSections.py", line 2129, in changeLang
    setSettingsValue("PreferredLanguage", selectedLang, r=False)
TypeError: setSettingsValue() got an unexpected keyword argument 'r'
ru
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\WingetUI\wingetui\uiSections.py", line 2129, in changeLang
    setSettingsValue("PreferredLanguage", selectedLang, r=False)
TypeError: setSettingsValue() got an unexpected keyword argument 'r'
pt_PT
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\WingetUI\wingetui\uiSections.py", line 2129, in changeLang
    setSettingsValue("PreferredLanguage", selectedLang, r=False)
TypeError: setSettingsValue() got an unexpected keyword argument 'r'
pt_BR
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\WingetUI\wingetui\uiSections.py", line 2129, in changeLang
    setSettingsValue("PreferredLanguage", selectedLang, r=False)
TypeError: setSettingsValue() got an unexpected keyword argument 'r'
pl
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\WingetUI\wingetui\uiSections.py", line 2129, in changeLang
    setSettingsValue("PreferredLanguage", selectedLang, r=False)
TypeError: setSettingsValue() got an unexpected keyword argument 'r'
ja
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\WingetUI\wingetui\uiSections.py", line 2129, in changeLang
    setSettingsValue("PreferredLanguage", selectedLang, r=False)
TypeError: setSettingsValue() got an unexpected keyword argument 'r'
it
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\WingetUI\wingetui\uiSections.py", line 2129, in changeLang
    setSettingsValue("PreferredLanguage", selectedLang, r=False)
TypeError: setSettingsValue() got an unexpected keyword argument 'r'
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

</details>

5. I switched several settings and manually restart, it seems that issue (2) is fixed. (Maybe there's something wrong with the `WingetUI` builtin `winget.exe`?)
   - General preferences > Application theme: Dark
   - Experimental settings and developer options > Use system Winget (Needs a restart): ✅

![image](https://user-images.githubusercontent.com/49941141/209434826-696d9360-e31c-430d-bd53-f52e31699497.png)

![image](https://user-images.githubusercontent.com/49941141/209434833-53cd3304-db0e-475e-a760-77d9360047f9.png)

**Comment by Dragon1573** [comment]
On my currently-installed-version of `v1.5.2-beta`, I'm currently using the system builtin `winget.exe`. After switching to the bundled version of `winget.exe`, package name parsing works perfect.

Wierd 😕

![image](https://user-images.githubusercontent.com/49941141/209436281-66234f58-c186-4083-a712-1e0f948640be.png)

![image](https://user-images.githubusercontent.com/49941141/209436288-847b8667-f0f1-4d2e-8e62-5bf48da309ea.png)

**Comment by martinet101** [comment]
For the issues you are listing:
1. Missing icons is expected if running from the command line. Running the script by double-clicking `__init__.py` should fix this
2. This issue is caused because the installer has not set up scoop properly. This won't happen in installer-based versions.
4. Restarting WingetUI does not work when running a Python script


System winget is not recommended, and should never be enabled in a non-testing instances, since it breaks stuff. Using the bundled winget is the only supported option.

I suppose this issue can be marked as fixed then
