### ISSUE TITLE
package list by default should be arranged by name instead of by selection (update section)

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#522]
I think the package list by default should be arranged by name instead of by selection. It's weird seeing the packages being rearranged when you select/unselect them:

https://user-images.githubusercontent.com/73800734/209407613-ccaf1be8-773a-4bf8-af62-3a339841b48c.mp4

_Originally posted by @ppvnf in https://github.com/martinet101/WingetUI/issues/506#issuecomment-1364350118_

**Comment by martinet101** [comment]
Fixed!
