### ISSUE TITLE
Bug: Updating all apps either doesn't install updates, or doesn't touch those that require admin

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#53]
Not even running WingetUI as admin and then running Upgrade all packages works - or there's been a misunderstanding about the feature.

Regarding update all, I saw it as fetching the latest data - and updating all the apps after that, kinda like `scoop update *` (when enough time has passed by obviously).

EDIT: More specifically, the app Icaros, which requires admin, being a non-portable app on Scoop, was in the list, but no matter if I ran WingetUI with admin or not and picked Upgrade all packages, it was always left untouched.

EDIT2: I also noticed it's missing auto-refresh upon updating the packages - after manually refreshing the corresponding apps show up.

Maybe it should simply be a separate button called "Upgrade all packages and install updates".

**Comment by martinet101** [comment]
If you run on a cmd window
`winget upgrade --all`
`scoop update`

do the apps get updated?

**Comment by RavenMacDaddy** [comment]
I'm not familiar with winget, but to update scoop apps you need an asterisk, like the aforementioned example, otherwise you're just fetching new manifests. 

The trick is, `scoop update *` will only fetch new manifests if enough time has passed - the exact amount I can't recall at the moment, but nevertheless, if what's programmed is:

`scoop update`
`scoop update *`

That will ensure things get taken care of on the scoop end no matter the elapsed time between executions. 

Please refer to the documentation regarding winget.

**Comment by martinet101** [comment]
fixed
