### ISSUE TITLE
Add options on uninstaller

### ISSUE THREAD

**Issue by candrapersada** [martinet101/WingetUI#55]
why no app cache cleaner like `scoop cleanup *` and `scoop cache rm *`

**Comment by martinet101** [comment]
Yes, this could be a thing

**Comment by candrapersada** [comment]
and add `scoop uninstall -p NameApp` to purge all persist data when you uninstall an app

**Comment by martinet101** [comment]
Done!

**Comment by candrapersada** [comment]
when uninstalling package add two options. the first one without delete persist. the two delete persist.

**Comment by martinet101** [comment]
Yes, this makes more sense

**Comment by candrapersada** [comment]
is it possible to add automatic clearing of cache after install and updating is complete or at startup of WingetUI?

**Comment by martinet101** [comment]
> is it possible to add automatic clearing of cache after install and updating is complete or at startup of WingetUI?

it is already done

**Comment by martinet101** [comment]
This will be discussed in #70
