### ISSUE TITLE
Bug: Upgrade all packages doesn't update winget apps

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#57]
I can see that it attempts to install WebView2 runtime (requires admin, so currently have to run WingetUI as admin), and it even says that it was successful, but I've to click on its own entry manually for the update to successfully complete - upon which it disappears from the list as expected.

**Comment by RavenMacDaddy** [comment]
Nevermind, WebView seems to be bugging out as usual - closing for now.

**Comment by RavenMacDaddy** [comment]
This time it was Webview again which gets updated often.

I'd to run it with sudo since it's installed globally, but it does work through a CLI, Powershell Core in this case; 7.2.5

**Comment by martinet101** [comment]
Fixed (in theory, note that winget still fails to install some stuff)
