### ISSUE TITLE
Add columns?

### ISSUE THREAD

**Issue by neoOpus** [martinet101/WingetUI#6]
Please add more columns and make them toggable like description, homepage link, GitHub, etc

Thanks

**Comment by martinet101** [comment]
I don't think thia will be an option, since this would mean runiing the command "winget show {element}" fo every single package, and this wiuld take like an hour or two to finish

**Comment by megamorphg** [comment]
> I don't think thia will be an option, since this would mean runiing the command "winget show {element}" fo every single package, and this wiuld take like an hour or two to finish


@marticliment is this true for all package managers?

And is it true for the Software Updates tab? It shouldn't take hours for just a dozen packages.

Also, when I go to package details, winget packages take time for it to load the Last updated but other package managers it seem to appear instantly. Is it already loaded to cache for those?

It would be great to see additional info like Last updated or Installer Size if any of those are fetched on the initial update summary pull. If any package manager doesn't have that on a summary than it can stay null until manually pulled.

**Comment by marticliment** [comment]
More or less yes, it is a mess, since each package manager does different things. I have not encountered yet a column that can be put and that will not be mostly empty.
