### ISSUE TITLE
Feature Request: Tickboxes/Select All for Software Updates to allow selective updates of all installed software

### ISSUE THREAD

**Issue by ROBYER1** [martinet101/WingetUI#60]
It would be useful to have tickboxes for the list of installed software under Software Updates + a Select All/Unselect All button to allow quick multi- selection of software to automatically update.

For example I keep multiple versions of Blender installed for different plugins that only work on those versions, when using Upgrade All Packages (which is essential as I have a lot of other packages), Blender versions always get updated.

**Comment by sitiom** [comment]
Related: #84

**Comment by sitiom** [comment]
There should also be a way to ignore apps so that they don't appear in the "available updates" in the tray
![image](https://user-images.githubusercontent.com/56180050/179209381-877609b9-0d86-4ad9-86c6-f75caa0ae3b7.png)

**Comment by martinet101** [comment]
Yes, the blacklist feature and the checkboxes will be independent

**Comment by ROBYER1** [comment]
When is this landing?

**Comment by martinet101** [comment]
Hi @ROBYER1, 

I don't know.

I'm trying to develop thgis in my free time, but, as you will understand, it isn't unlimited.

I'll try to do this as soon as I can

**Comment by ROBYER1** [comment]
> Hi @ROBYER1,
> 
> I don't know.
> 
> I'm trying to develop thgis in my free time, but, as you will understand, it isn't unlimited.
> 
> I'll try to do this as soon as I can

Apologies for sounding impatient, I'm keen to help test it and support this development in the future as I use it a lot on my work/personal computer. Thanks for your hard work on this and I hope to help contribute in the future 👍

**Comment by martinet101** [comment]
Done!

**Comment by martinet101** [comment]
![Uploading image.png…]()

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/188329312-50bee506-8f65-4487-b81a-b3d498318105.png)

**Comment by ROBYER1** [comment]
> ![image](https://user-images.githubusercontent.com/53119851/188329312-50bee506-8f65-4487-b81a-b3d498318105.png)

You legend! I will test this out soon! Does it remember the ticked boxes on relaunch?

**Comment by martinet101** [comment]
No, but there will be an option to blacklist apps (i'm actually working on it rn)

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/188329861-b5c1cee9-ef64-45db-8dbf-5a1f7195e312.png)

**Comment by ROBYER1** [comment]
> ![image](https://user-images.githubusercontent.com/53119851/188329861-b5c1cee9-ef64-45db-8dbf-5a1f7195e312.png)

That looks perfect! Is that out now? Thanks so much!

**Comment by martinet101** [comment]
Still not, i still have to polish some stuff, but it'll be soon!
