### ISSUE TITLE
Feature request: Ability to install apps in parallell 

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#61]
Obviously with some annotation or marked text like "For experts ONLY! Use at your own risk!"

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/178150131-89ae2094-723b-463b-97c9-b849cca56d7e.png)
Done!

**Comment by martinet101** [comment]
Some fail because msiexec does not allow parallel installs
