### ISSUE TITLE
Feature request: Add Update manifests alongside Upgrade all packages

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#63]
This is closely related to #62.

Sometimes you simply want to get the latest manifests, but not necessarily get the resulting updates to your apps - a great example is apps that get updated daily, or even several times a day.

That's gonna clutter up the system with redundant versions real fast.

Whatever the case, it's always good to give users the choice what to do with updates, whether that be for the apps, or just the manifests themselves.

Side note, maybe 'Upgrade all packages' should say "Update all of my software" instead - especially fitting with this feature in place; "Update manifests".

**Comment by martinet101** [comment]
The manifests are going yo be updated on launch, this is a thing t'ha will come with the next version
