### ISSUE TITLE
Improvement: Enlarge the arrow-button for installation status

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#65]
![image](https://user-images.githubusercontent.com/67732686/178092352-91f23439-2536-402b-b261-a70000e46498.png)

At the moment it would benefit from being enlarged to improve the usability; UX.

It would probably also improve the UI in the process since there's an opportunity to ensure the margins on each side are in perfect symmetry in relation to the arrow.

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/179030124-554c37a2-ce40-4748-8c14-98b8867729ba.png)

**Comment by martinet101** [comment]
Done!
