### ISSUE TITLE
Bug: Update to Scoop breaks detection by WingetUI

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#66]
Noticed that since Scoop got updated to 0.2.3, WingetUI isn't detecting the apps.

It still updates Scoop and its buckets if I run Upgrade all packages, but the apps won't show up.

![image](https://user-images.githubusercontent.com/67732686/178094222-2f9a0c0a-9dfc-4afa-9c7b-7468454a09d3.png)

![image](https://user-images.githubusercontent.com/67732686/178094226-79cd8b26-1db4-4039-852d-be6833719103.png)

![image](https://user-images.githubusercontent.com/67732686/178094235-5c83e1d8-f1b2-4227-a2e5-1a7d68ffaf9e.png)

**Comment by martinet101** [comment]
True, it is hgappenning to me also

**Comment by martinet101** [comment]
Fixed!
