### ISSUE TITLE
Add local languages

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [martinet101/WingetUI#67]
Adding a local language can help users better use the software.
Just do it!
Like French Japanese Chinese etc

**Comment by arinoki** [comment]
Well, this needed to be done by contributors. Like if u can to translate to some of languages above - make pull request.

**Comment by martinet101** [comment]
Yes. I would like to wait for the project to have more popularity

**Comment by martinet101** [comment]
Hi @arinoki @BUGProtectionAssociation, the translation program is now open!

Please see how to contribute here: https://github.com/martinet101/WingetUI/wiki#contributing
