### ISSUE TITLE
v1.2 - About > Component info: Cut off path for Sudo 

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#68]
![image](https://user-images.githubusercontent.com/67732686/179057524-9c508ae4-b0f8-4007-b341-557ee77bcb52.png)

First I wanna say, you're doing a great job, very impressed.

The pic speaks for itself.

**Comment by martinet101** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/53119851/188122075-0ea1f411-c0e5-447a-8bfd-a61b3df828b1.png)
