### ISSUE TITLE
v1.2 - Bug: Successful updates don't disappear from the list in real-time (seemingly admin installs)

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#69]
Ran update for WebView2 as admin successfully - good job solving that - what's remaining is successful updates disappearing from the list.

EDIT: Running an update for .NET did however disappear as expected - but I didn't need to run that as admin, so maybe that's it?

**Comment by martinet101** [comment]
I found the issue, the updates that were not hiding where the ones that were launched from the info panel, not double-clicking.

The issue has now been fixed
