### ISSUE TITLE
Feature request: Add Run as admin to the context menu

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#70]
For example when right-clicking apps under Discover Software or Software Updates.

**Comment by martinet101** [comment]
Context menu TODO:
 - [ ] Add Admin on discover
 - [ ] Add Force on discover
 - [ ] Add interactive on discover
 - [ ] Add Admin on update
 - [ ] Add Force on update
 - [ ] Add interactive on update
 - [ ] Add Admin on uninstall
 - [ ] Add interactive on uninstall
 - [ ] Add remove-persists on uninstall (scoop only)

**Comment by candrapersada** [comment]
- [ ] Add Admin on install update uninstall (Scoop Nonportable Bucket only)

**Comment by candrapersada** [comment]
> Not all nonportable Scoop applications need admin.

is there an option to check apps that use admin or non admin?

**Comment by sitiom** [comment]
> > Not all nonportable Scoop applications need admin.
> 
> is there an option to check apps that use admin or non admin?

There are [checks](https://github.com/ScoopInstaller/Nonportable/search?q=is_admin) in the manifests to check if you are running as admin and stop installation when it fails.

**Comment by martinet101** [comment]
Not default options

**Comment by martinet101** [comment]
Done
