### ISSUE TITLE
v1.2 - Bug - Installed applications: Winget apps are missing

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#71]
![image](https://user-images.githubusercontent.com/67732686/179061140-ffd2fa78-1783-46aa-81b0-795bf2c060e3.png)

Tried restarting the app, didn't help.

**Comment by martinet101** [comment]
Weird...

I'll take a look, it might be winget just misbehaving or some wrong code from my side...

**Comment by martinet101** [comment]
Hi @RavenMacDaddy,

winget has been updated to a newer version (1.3.0.2), and (at least for me) this issue got partially fixed. When WingetUI updates to 1.3, please check if the issue still persists.

**Comment by martinet101** [comment]
Does this issue is still a thing?

**Comment by RavenMacDaddy** [comment]
![image](https://user-images.githubusercontent.com/67732686/192846998-8333aeae-2905-456f-a92b-754010e393a2.png)

Nope, closing.
