### ISSUE TITLE
v1.2 - Bug: Unable to use installation options for Scoop apps

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#73]
![image](https://user-images.githubusercontent.com/67732686/179065529-5b03d1b0-91c6-4897-b9f7-e8e4ad9d35d8.png)

This is a good example, cause many nonportable apps require Sudo, but it wasn't selectable.

With Winget apps the user can select all of the options (haven't had a reason to test anything but install as admin yet, which worked fine).

**Comment by martinet101** [comment]
I don't know if the apps require sudo, but the aim of scoop is making an admin-less, unattended package manager, so it does not have sense to add neither admin or interactive modes. For the force flag, it is specific on wingrt to bypass the hash check.

I don't know if I understood you well, but I guess that was what you meant

**Comment by candrapersada** [comment]
![image](https://user-images.githubusercontent.com/36833664/179117234-9ec661b1-c8e6-4999-82a7-fa42213afc27.png)
https://github.com/ScoopInstaller/Nonportable#readme

**Comment by martinet101** [comment]
Huh, didn't know that, then the request makes sense
