### ISSUE TITLE
disable automatic updates by default when installing WingetUI from Scoop

### ISSUE THREAD

**Issue by candrapersada** [martinet101/WingetUI#74]
does it disable automatic updates by default when installing WingetUI from Scoop?
![image](https://user-images.githubusercontent.com/36833664/179118824-06b09b78-2274-4713-90be-2ff6655b8cf8.png)

**Comment by martinet101** [comment]
It shouldn't, as far as I know. However, i did not publish WingetUI on scoop,so I cant say this for sure...

**Comment by martinet101** [comment]
It does not. That must be changed from the manifests, but as I said, i did not publish it there.
