### ISSUE TITLE
Fluent tray context menu

### ISSUE THREAD

**Issue by sitiom** [martinet101/WingetUI#75]
Is it possible to have a fluent tray context menu for WingetUI like how ElevenClock does?

![image](https://user-images.githubusercontent.com/56180050/179125129-7a4e62e5-1b07-4699-8a14-8ae25ebefbea.png)

**Comment by martinet101** [comment]
Yes, i could literally copy de code, but i haven't had time.

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/188267088-345f81cc-c193-4d1d-bbe8-128e3dce74a4.png)

It's coming...

**Comment by martinet101** [comment]
Done!

**Comment by sitiom** [comment]
> ![image](https://user-images.githubusercontent.com/53119851/188267088-345f81cc-c193-4d1d-bbe8-128e3dce74a4.png)
> 
> It's coming...

@martinet101 I didn't notice till now, that looks like a typo:
![image](https://user-images.githubusercontent.com/56180050/188438905-70e1259a-97b1-4973-b1f2-3e7d562b8a11.png)
