### ISSUE TITLE
Tray icon indication for outdated packages and when currently updating

### ISSUE THREAD

**Issue by sitiom** [martinet101/WingetUI#76]
Going back to my quote in https://github.com/martinet101/WingetUI/issues/44#issue-1266938891:
>
> 
> [zkokaja/Brewlet](https://github.com/zkokaja/Brewlet)
>
> > For example, you need to manually check if some of your packages can be updated. With Brewlet it's easy: if everything is working swimmingly, then you'll see the normal shadow  <img src="https://raw.githubusercontent.com/zkokaja/Brewlet/master/images/brewlet-black.svg" width="16px" /> icon. If updates are available to be installed, the icon will become colored, <img src="https://raw.githubusercontent.com/zkokaja/Brewlet/master/images/brewlet-color.svg" width="16px" /> , to get your attention – along with a notification if you wish. Once clicked, you'll be able to upgrade your packages, among other options. In addition, Brewlet will periodically check the status of packages in the background, so you don't have to.

> [cokelid/ChocoButler](https://github.com/cokelid/ChocoButler)
> When up-to-date:
> ![](https://github.com/cokelid/ChocoButler/raw/main/img/chocobutler_48x48.png) 
> When outdated:
> ![](https://github.com/cokelid/ChocoButler/raw/main/img/chocobutler_red_48x48.png)

It might be good to have an indication that packages need to be updated and WingetUI is updating by looking at the tray icon. It's an easy eye candy, and I wouldn't have to check the tray every time.

**Comment by martinet101** [comment]
Yes, could be a good idea

**Comment by martinet101** [comment]
Done!

The icon will have 4 status:
 - grey: idling
 - yellow: installing/updating/uninstalling
 - green: available updates
 - red: error occurred.

What changes is the color of the arrow on the icon
