### ISSUE TITLE
Enablew/disable startup switch ----- (DONE Run at startup and startup minimized to tray)

### ISSUE THREAD

**Issue by sitiom** [martinet101/WingetUI#77]
It would be nice to have an option to have WingetUI run at startup. I could do this by adding a startup shortcut menu or via the task scheduler, but it would be nice if this could be done from WingetUI. Additionally, there should be an option to run at startup minimized, assuming one only uses the tray application.

**Comment by martinet101** [comment]
Yes, this actually makes sense

**Comment by martinet101** [comment]
Done!

**Comment by sitiom** [comment]
Is this just a command-line argument? I would like to have a configurable option in the settings that adds a shortcut in the startup folder to start as a daemon.

**Comment by martinet101** [comment]
Yep, it is `--daemon` and you will be able to enable/disable from the task manager and startup apps on settings window

**Comment by sitiom** [comment]
It would be great if there was a checkbox to easily set that up like most other apps:
![image](https://user-images.githubusercontent.com/56180050/188417905-c3110146-a4ad-483b-8212-8d36ad539c86.png)

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/188577263-488af9b4-a283-4211-a4ff-8027f832d0a7.png)
I guess this checkbox makes more sense. 

The same that makes WingetUI always run or not will enable/disable startup load

**Comment by martinet101** [comment]
Done
