### ISSUE TITLE
Installing any app from the GUI crashes WingetUI

### ISSUE THREAD

**Issue by sitiom** [martinet101/WingetUI#79]
Can you investigate this? WingetUI seems to crash when I try to install **any** app.

**Comment by sitiom** [comment]
Apparently, it has to do something with my [Tiling Window Manager](https://github.com/LGUG2Z/komorebi).

**Comment by sitiom** [comment]
Related to #98, seems to be fixed in 1.3

**Comment by martinet101** [comment]
Possibly les

**Comment by martinet101** [comment]
*yes
