### ISSUE TITLE
Duplicated UI when run with Admin rights

### ISSUE THREAD

**Issue by donsequitur** [martinet101/WingetUI#8]
Running under Windows 11 with admin rights, installed via this scoop bucket https://github.com/hoilc/scoop-lemon/blob/master/bucket/wingetui.json

The app opens with traditional UI windows styling, After closing the warning popup, the Mica styled UI loads on top of this

![image](https://user-images.githubusercontent.com/9997705/168801050-358b5b1c-af89-460d-a18b-192009a94eec.png)

**Comment by martinet101** [comment]
if you do not open it as admin, does it work?

**Comment by martinet101** [comment]
Fixed in the upgrade from Qt5 to Qt6. The fix will come in the next version
