### ISSUE TITLE
Context menu tray icon doesn't update on new apps, uninstalled apps, and updated apps through WingetUI

### ISSUE THREAD

**Issue by sitiom** [martinet101/WingetUI#82]
The context menu should be updated to reflect the new changes.

**Comment by sitiom** [comment]
Additionally, WingetUI should check for app changes and updates for a set interval (realtime if possible) in case some external program does some installation, update, or uninstall.

**Comment by martinet101** [comment]
> Additionally, WingetUI should refresh for app changes and updates for a set interval (real time if possible) in case some external program does some installation, update, or uninstall. There is a refresh button in the GUI but it would be good if WingetUI automatically does this.


This is done on launch, and i'll add a button to do that from the context menu, but i don't think this is needed in a timed period

TODO:
 - [ ] Update menu list
 - [ ] Add a button to rescan updates

**Comment by sitiom** [comment]
> This is done on launch, and i'll add a button to do that from the context menu, but i don't think this is needed in a timed period

Well, if #76 is implemented, I would like the tray indicator to automatically show me updates instead of having to check for it myself. The point is I want to be notified about new updates without manually checking.

**Comment by martinet101** [comment]
Yes, if the app autostarts on launch in background it will do that

**Comment by sitiom** [comment]
> Yes, if the app autostarts on launch in background it will do that

Does it only check once or at a regular interval?

**Comment by martinet101** [comment]
on every launch databases are updated

**Comment by sitiom** [comment]
So just once? I usually keep my computer running for a long time. How should it automatically get updates?

**Comment by martinet101** [comment]
> for a long time
Like what do you mean?

**Comment by sitiom** [comment]
> > for a long time
> 
> Like what do you mean?

It means WingetUI is only launched once, and it won't get updated ever since, which is why I would like to have automatic checking of updates.

**Comment by martinet101** [comment]
Ok. I see

**Comment by martinet101** [comment]
Fixed!
