### ISSUE TITLE
Install hanging on loading UI components

### ISSUE THREAD

**Issue by aadvanraamt** [martinet101/WingetUI#86]
Install hanging on loading UI component
![Rambox_gzta01gQe7](https://user-images.githubusercontent.com/22995621/179234797-dfb1bfe3-9889-49ff-b455-32b05699b53f.png)
s

**Comment by martinet101** [comment]
Can you please send a screenshot?

**Comment by aadvanraamt** [comment]
[cid:2d4a719a-ce4c-4cd3-9601-39f36a7cac86]
________________________________
Van: Martí Climent ***@***.***>
Verzonden: vrijdag 15 juli 2022 11:28
Aan: martinet101/WingetUI ***@***.***>
CC: aadvanraamt ***@***.***>; Author ***@***.***>
Onderwerp: Re: [martinet101/WingetUI] Install hanging on loading UI components (Issue #86)


Can you please send a screenshot?

**Comment by martinet101** [comment]
Hi, can't see the image

**Comment by aadvanraamt** [comment]
________________________________
Van: Martí Climent ***@***.***>
Verzonden: vrijdag 15 juli 2022 13:08
Aan: martinet101/WingetUI ***@***.***>
CC: aadvanraamt ***@***.***>; Author ***@***.***>
Onderwerp: Re: [martinet101/WingetUI] Install hanging on loading UI components (Issue #86)


Hi, can't see the image

**Comment by martinet101** [comment]
Can you please attach the image as an URL or upload it to GitHub? It looks like email interactions don't work very well...

**Comment by martinet101** [comment]
Hi, this hang is permanent? Or it dures for a few seconds? Because this is expected, since the program has to load appproximately 5000 software entries

**Comment by aadvanraamt** [comment]
Its hangs permanent after about 3250 packeges
________________________________
Van: Martí Climent ***@***.***>
Verzonden: vrijdag 15 juli 2022 16:00
Aan: martinet101/WingetUI ***@***.***>
CC: aadvanraamt ***@***.***>; Author ***@***.***>
Onderwerp: Re: [martinet101/WingetUI] Install hanging on loading UI components (Issue #86)


Hi, this hang is permanent? Or it dures for a few seconds? Because this is expected, since the program has to load appproximately 5000 software entries

**Comment by martinet101** [comment]
What are your PC specs?

**Comment by aadvanraamt** [comment]
HP Intel(R) Core(TM) i7-8700T CPU @ 2.40GHz   2.40 GHz
16,0 GB (15,8 GB beschikbaar)
Windows 11 Pro Insider Preview DEV
________________________________
Van: Martí Climent ***@***.***>
Verzonden: vrijdag 15 juli 2022 20:38
Aan: martinet101/WingetUI ***@***.***>
CC: aadvanraamt ***@***.***>; Author ***@***.***>
Onderwerp: Re: [martinet101/WingetUI] Install hanging on loading UI components (Issue #86)


What are your PC specs?

**Comment by martinet101** [comment]
Could you please test version 1.4.2?

**Comment by aadvanraamt** [comment]
I have done and issues found
________________________________
Van: Martí Climent ***@***.***>
Verzonden: dinsdag 11 oktober 2022 10:34
Aan: martinet101/WingetUI ***@***.***>
CC: aadvanraamt ***@***.***>; Author ***@***.***>
Onderwerp: Re: [martinet101/WingetUI] Install hanging on loading UI components (Issue #86)


Reopened #86<https://github.com/martinet101/WingetUI/issues/86>.

**Comment by martinet101** [comment]
And no error report window pops up?
Can you try fully uninstallling, removing the .wingetui folder present in %userprofile% and then installing again?

**Comment by aadvanraamt** [comment]
No error report windows great app

________________________________
Van: Martí Climent ***@***.***>
Verzonden: dinsdag 11 oktober 2022 10:49
Aan: martinet101/WingetUI ***@***.***>
CC: aadvanraamt ***@***.***>; Author ***@***.***>
Onderwerp: Re: [martinet101/WingetUI] Install hanging on loading UI components (Issue #86)


And no error report window pops up?
Can you try fully uninstallling, removing the .wingetui folder present in %userprofile% and then installing again?

**Comment by martinet101** [comment]
So Is the app working again or it still fails?

**Comment by aadvanraamt** [comment]
The app is working again
________________________________
Van: Martí Climent ***@***.***>
Verzonden: dinsdag 11 oktober 2022 16:14
Aan: martinet101/WingetUI ***@***.***>
CC: aadvanraamt ***@***.***>; Author ***@***.***>
Onderwerp: Re: [martinet101/WingetUI] Install hanging on loading UI components (Issue #86)


So Is the app working again or it still fails?

**Comment by aadvanraamt** [comment]
Yes perfect app thanks
________________________________
Van: Martí Climent ***@***.***>
Verzonden: dinsdag 11 oktober 2022 18:06
Aan: martinet101/WingetUI ***@***.***>
CC: aadvanraamt ***@***.***>; Author ***@***.***>
Onderwerp: Re: [martinet101/WingetUI] Install hanging on loading UI components (Issue #86)


Closed #86<https://github.com/martinet101/WingetUI/issues/86> as completed.
