### ISSUE TITLE
UI design - Improvement: Remove active element-outline

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#88]
![image](https://user-images.githubusercontent.com/67732686/179342763-2343865c-43ed-410a-9b40-c046fecee97b.png)

![image](https://user-images.githubusercontent.com/67732686/179342868-4c949331-d7cd-4a99-a464-cf2a554528f8.png)

Is that possible?

It would look a lot better without the dots outlining the active element (which is already made clear with the lighter shade for tabs, and unnecessary for miscellaneous elements).

**Comment by martinet101** [comment]
I guess this can be removed, but i'm not really sure...

**Comment by martinet101** [comment]
Done!
