### ISSUE TITLE
v1.2 - Bug: WingetUI keeps running when closed (even when the option to keep it running in tray is disabled)

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#89]
![image](https://user-images.githubusercontent.com/67732686/179350206-171ea2a1-1af1-4d7a-9a77-c6db0183326a.png)

![image](https://user-images.githubusercontent.com/67732686/179350221-dd3ed222-e2eb-4719-8cc0-4990417fc292.png)

**Comment by martinet101** [comment]
Mhmm... there must be some extra thread running... I'll take a look

**Comment by RavenMacDaddy** [comment]
> But it does not consume any cpu, right?

Not of any concern CPU wise - but it does use RAM, and clutters the processes on the system.

**Comment by martinet101** [comment]
I'll take a look

> but it does use RAM, and clutters the processes on the system

Yes, it obviously needs to be fixed, but it was to know if the script was overloading the system entirely or it was an idle non-daemon thread that was left there

**Comment by martinet101** [comment]
The issue should be fixed. 

However, if it persists, please repoen
