### ISSUE TITLE
Feature request: Change double-click action

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#9]
Like updates, it would be great if you could double-click in the install view - maybe through a toggle at the top to give users the choice. ("Quick install with double-click" or something.)

This could be complemented with a right-click menu to show details for the app like the current behavior shows the user.

**Comment by martinet101** [comment]
Well, fast installl was supposed to be a feature in the context menu, but this kind of toggling could be a configurable behaviour

**Comment by martinet101** [comment]
Done!

**Comment by martinet101** [comment]
Made with context menus

![image](https://user-images.githubusercontent.com/53119851/170835301-60f0985e-25a2-4609-850c-f76937d997df.png)
![image](https://user-images.githubusercontent.com/53119851/170835305-e954ee2f-2717-4136-b018-fe9059a2111e.png)

**Comment by RavenMacDaddy** [comment]
Just to check, does this mean that the Install software section has double-click as well?

If it still uses double-click to show info instead, it creates a UX disconnect with double-click meaning install in the update section.

**Comment by martinet101** [comment]
> does this mean that the Install software section has double-click to install as well

This will be configurable, i'm working on it
