### ISSUE TITLE
scoop.fatal in the update section

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#92]
I'm using the latest version of WingetUI and Windows 10 x64 21h2 and I'm getting a bunch of scoop.fatal packages in the update section. There's also scoop.git and scoop.to. I can see the actual updates if I scroll down. Out of 37 updates availables only 3 are real packages.
![screenshot](https://user-images.githubusercontent.com/73800734/179646053-76c33a5d-cc40-4d1c-a39a-e008dee472c6.png)

**Comment by martinet101** [comment]
What happens if you run `scoop status` in a cmd window?

**Comment by ppvnf** [comment]
It seems scoop is not being properly detected by WingetUI. I did a few tests. I can update and uninstall scoop apps through WingetUI but if I try to install a new one nothing happens (I can still install through CMD tho). Winget works perfectly.
![screenshot 2](https://user-images.githubusercontent.com/73800734/179737340-83069f54-a7f7-41b4-8cb1-1b4f6a494f6a.png)
![nd1](https://user-images.githubusercontent.com/73800734/179738727-20659b44-16ef-41dc-a78c-de51083f199d.png)

**Comment by martinet101** [comment]
if you run "scoop status in `cmd` what happens?"

**Comment by martinet101** [comment]
cmd, not powershell

**Comment by martinet101** [comment]
weird... I'll take a look

**Comment by martinet101** [comment]
Does WingetUI 1.3 work now?

**Comment by ppvnf** [comment]
> Does WingetUI 1.3 work now?

Partially. I successfully used WingetUI 1.3 to install Google Chrome from scoop, which I couldn`t do previously through WingetUI 1.2. I can`t, however, uninstall scoop apps using WingetUI 1.3. I could uninstall using 1.2 though. Besides that there are still dummy packages in the update section and scoop isn`t properly detected as installed.

**Comment by ppvnf** [comment]
![Capture 2](https://user-images.githubusercontent.com/73800734/188620148-2502004f-fcf2-48f3-b97e-80f62407eb63.JPG)
![Screenshot 2022-09-06 072954](https://user-images.githubusercontent.com/73800734/188620169-8b7011db-747d-4ec9-8d63-04ba732ead6b.png)
![Screenshot 2022-09-06 073239](https://user-images.githubusercontent.com/73800734/188620173-57c03cf6-9e82-4e32-8e6b-e6be7b58da4f.png)
![Screenshot 2022-09-06 073331](https://user-images.githubusercontent.com/73800734/188620179-4356dbaa-8055-4c40-8bad-595669df645a.png)

**Comment by martinet101** [comment]
When uninstalling, are you using the "remove app data" context menu option or are you simply double-clicking?

**Comment by ppvnf** [comment]
> When uninstalling, are you using the "remove app data" context menu option or are you simply double-clicking?

I was double-clicking. I just tried the context menu option and it works!

**Comment by martinet101** [comment]
ah, that was not expected...

Amnyway, i'll take a look

**Comment by ppvnf** [comment]
> ah, that was not expected...
> 
> Amnyway, i'll take a look

I had this idea after reading another issue. I tried running WingetUI as administrator and all issues were solved! By the way, instead of always right-clicking to run as administrator you can do this [automatically](https://www.itproportal.com/guides/how-to-make-programs-always-run-as-admin-on-windows/). I would say my issue is mostly fixed, but I guess having to run as administrator is not ideal.

"Ok I think i've identified the problem.
If I start wingetUI from the start menu by searching for it, it shows scoop not found and unknown.

But if I right click on the start menu icon, click open file location and then run wingetui from the shorcut in windows explorer, It runs fine and detects scoop.

Really weird, but I  was able to reproduce it multiple times."

_Originally posted by @rp1231 in https://github.com/martinet101/WingetUI/issues/104#issuecomment-1238384644_

**Comment by martinet101** [comment]
Could you try uninstalling WingetUI from scoop and then installing from WingetUI or manually?

**Comment by ppvnf** [comment]
> Could you try uninstalling WingetUI from scoop and then installing from WingetUI or manually?

Same result. The problems are fixed only by running as administrator

**Comment by martinet101** [comment]
This issue should have been fixed (for users who are still experiencing it) and will be available in WingetUI 1.4

**Comment by ppvnf** [comment]
> This issue should have been fixed (for users who are still experiencing it) and will be available in WingetUI 1.4

Awesome!

**Comment by ppvnf** [comment]
I've tried 1.4 without admin privilages and scoop still isn't recognized and fake updates still appear =(.
[log.txt](https://github.com/martinet101/WingetUI/files/9691081/log.txt)

**Comment by ppvnf** [comment]
LMAO
Building WingetUI wasn't totally successful, but I accidentally fixed this issue on https://github.com/martinet101/WingetUI/issues/163#issuecomment-1264737794
I will left this open so you can decide if this "fix" can be applied to other users
Maybe it was because of git config --global --add safe.directory...

**Comment by martinet101** [comment]
Git should mark by default scoop dirs as safe, i guess this is more a scoop issue...

**Comment by ppvnf** [comment]
> Git should mark by default scoop dirs as safe, i guess this is more a scoop issue...

I believe so
