### ISSUE TITLE
Updating packages causes crash

### ISSUE THREAD

**Issue by NotNullBool** [martinet101/WingetUI#98]
Updating a individual package or all packages causes the program to crash and no update to occur

https://i.imgur.com/Guywl5O.gif

**Comment by martinet101** [comment]
does this happen with any package?

**Comment by NotNullBool** [comment]
Node.js -> Succeeds
Discord Canary -> Crashes then opens installer then fails

**Comment by NotNullBool** [comment]
Node.js -> Success
Discord Canary -> Crashes opens installer then fails
Winscp -> first wouldnt finish updating then press admin privilege then update now crashes
Microsoft c++ redist 2013 x86 -> Success
Microsoft c++ redist 2013 x64 -> Fails
 
All other not mentioned failed

After the x64 c++ failed x86 returned probably due to the version not updating so probably not important.

**Comment by martinet101** [comment]
This issue should have been fixed. 

Please try if this still happens in version 1.3

**Comment by NotNullBool** [comment]
It is fixed! Thank you love the work!
