### ISSUE TITLE
[Work Laptop] Non-admin account running this as Administrator cannot update any software - Failed when opening source(s)

### ISSUE THREAD

**Issue by ROBYER1** [martinet101/WingetUI#99]
When running this as Admin on a non admin account on a work managed machine (but I do have access to the admin password for UAC prompts and allow admin use), WingetUI cannot install anything when updating programs and always results with the same error. I always allow the UAC admin prompts for Admin access with the admin password, I am trying to update software installed on my local developer account and not the admin account. 

![image](https://user-images.githubusercontent.com/10745594/180813915-0520b82c-1d8e-4955-884a-c212f7ea79af.png)

For example when trying to update 7-Zip, this is the log:

> 
> -\|/- 
> 
>   ███████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 3.93 MB
>   ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 3.93 MB
>   ██████████████████████▒▒▒▒▒▒▒▒  3.00 MB / 3.93 MB
>   ██████████████████████████████  3.93 MB / 3.93 MB
>                                                               
> 
>   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  0%
>   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  0%
>   ███████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 3.93 MB
>   ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 3.93 MB
>   ██████████████████████▒▒▒▒▒▒▒▒  3.00 MB / 3.93 MB
>   ██████████████████████████████  3.93 MB / 3.93 MB
>                                                               
> 
>   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  0%
>   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  0%
>                                                               
> Failed when opening source(s); try the 'source reset' command if the problem persists.
> An unexpected error occurred while executing the command:
> 0x8a15000f : Data required by the source is missing

**Comment by martinet101** [comment]
Hi @ROBYER1, have you tried the admin flag?
![image](https://user-images.githubusercontent.com/53119851/182211333-d03bd475-a9d1-4029-92b1-cb2eefe58b0c.png)

**Comment by martinet101** [comment]
The elevation algorithm has been changed, could you please try it?

**Comment by ROBYER1** [comment]
Works great on my work laptop now as non admin user but using admin prompts!

**Comment by ALERTua** [comment]
The issue is not fixed for me, and the workaround does not work.
My user is a non-administrator. I have Plex installed in Program Files.
- While trying to update Plex normally, the installer asks for an elevation, I provide it using the administrator user credentials, and the installer cannot be launched due to the path not found error.
- While trying to update it using Update as administrator, the error is the same.
- While trying to update it via Show Info -> Run as admin -> Update - the error is the same.
All cases lead to this error:
```
[Window Title]
Network Error

[Main Instruction]
Windows cannot access C:\Users\(my_non_admin_user)~1\AppData\Local\Temp\WinGet\Plex.Plex.1.62.2\Plex-1.62.2.3451-fb8ac0ae-x86_64.exe

[Content]
Check the spelling of the name. Otherwise, there might be a problem with your network. To try to identify and resolve network problems, click Diagnose.

[^] Hide details  [Diagnose] [Cancel]

[Expanded Information]
Error code: 0x80070043
The network name cannot be found.

```

**Comment by marticliment** [comment]
yes, let's hope that they can fix that, because, as said, I can't do anything about it.
